### ISSUE TITLE
Prefetch is broken

### ISSUE THREAD

**Issue by DuckTheMug** [K1rakishou/Kuroba-Experimental#1020]
Exception: java.lang.IllegalArgumentException
Message: Bad chunkIndex for prefetch: 1

Stacktrace
```
java.lang.IllegalArgumentException: Bad chunkIndex for prefetch: 1
	at com.github.k1rakishou.chan.core.loader.impl.PrefetchLoader$startLoading$3$1.onProgress(SourceFile:67)
	at androidx.compose.material.DrawerKt$Scrim$1$1.invoke(SourceFile:61)
	at androidx.work.impl.WorkerWrapper$$ExternalSyntheticLambda0.run(SourceFile:1369)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7914)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

```

Logs
```
D/(07:43:13.029) KurobaEx-beta | Dependency Injection: Using HTTP_1_1
D/(07:43:13.051) KurobaEx-beta | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.beta/files/kurobaex_theme_light.json) does not exist on the disk
D/(07:43:13.052) KurobaEx-beta | ChanPostRepository: ChanPostRepository.initialize()
D/(07:43:13.054) KurobaEx-beta | SiteManager: SiteManager.initialize()
D/(07:43:13.055) KurobaEx-beta | BoardManager: BoardManager.initialize()
D/(07:43:13.055) KurobaEx-beta | SiteManager: loadSitesInternal() start
D/(07:43:13.055) KurobaEx-beta | BookmarksManager: BookmarksManager.initialize()
D/(07:43:13.055) KurobaEx-beta | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/(07:43:13.055) KurobaEx-beta | BookmarkWatcherCoordinator: BookmarkWatcherCoordinator.initialize()
D/(07:43:13.055) KurobaEx-beta | FilterWatcherCoordinator: FilterWatcherCoordinator.initialize()
D/(07:43:13.055) KurobaEx-beta | ArchivesManager: ArchivesManager.initialize()
D/(07:43:13.056) KurobaEx-beta | ChanFilterManager: ChanFilterManager.initialize()
D/(07:43:13.056) KurobaEx-beta | Chan: Application initialization took 94ms
D/(07:43:13.056) KurobaEx-beta | BoardManager: loadBoardsInternal() start
D/(07:43:13.056) KurobaEx-beta | BoardManager: loadBoardsInternal() siteDataListAsync.get() start
D/(07:43:13.056) KurobaEx-beta | BookmarksManager: initializeBookmarksInternal() start
D/(07:43:13.057) KurobaEx-beta | ArchivesManager: initializeArchivesManagerInternal() start
D/(07:43:13.057) KurobaEx-beta | ChanFilterManager: loadFiltersInternal() start
D/(07:43:13.063) KurobaEx-beta | ArchivesManager: SuspendableInitializer initWithModularResult() called
D/(07:43:13.063) KurobaEx-beta | ArchivesManager: SuspendableInitializer initWithValue() called
D/(07:43:13.063) KurobaEx-beta | ArchivesManager: notifyAllWaiters throwable==null: true, waiters=0
D/(07:43:13.063) KurobaEx-beta | ArchivesManager: SuspendableInitializer initWithValue() done
D/(07:43:13.063) KurobaEx-beta | ArchivesManager: initializeArchivesManagerInternal() done. Loaded 13 archives
D/(07:43:13.063) KurobaEx-beta | ArchivesManager: initializeArchivesManagerInternal() end, took 6.158333ms
D/(07:43:13.084) KurobaEx-beta | StartActivity: onCreate() start isFreshStart: false, initializing everything
D/(07:43:13.096) KurobaEx-beta | ChanPostRepository: Not enough posts to start deleting, posts in database amount: 11191, max allowed posts amount: 75000
D/(07:43:13.104) KurobaEx-beta | BookmarksRepository: initialize() -> 7 took 6.272656ms
D/(07:43:13.104) KurobaEx-beta | BookmarksManager: SuspendableInitializer initWithValue() called
D/(07:43:13.104) KurobaEx-beta | BookmarksManager: notifyAllWaiters throwable==null: true, waiters=0
D/(07:43:13.104) KurobaEx-beta | BookmarksManager: SuspendableInitializer initWithValue() done
D/(07:43:13.104) KurobaEx-beta | BookmarksManager: initializeBookmarksInternal() done. Loaded 7 bookmarks and 7 active bookmarks
D/(07:43:13.105) KurobaEx-beta | BookmarksManager: initializeBookmarksInternal() end, took 48.246667ms
D/(07:43:13.106) KurobaEx-beta | ChanFilterManager: SuspendableInitializer initWithValue() called
D/(07:43:13.106) KurobaEx-beta | ChanFilterManager: notifyAllWaiters throwable==null: true, waiters=0
D/(07:43:13.106) KurobaEx-beta | ChanFilterManager: SuspendableInitializer initWithValue() done
D/(07:43:13.106) KurobaEx-beta | ChanFilterManager: loadFiltersInternal() done. Loaded 0 filters
D/(07:43:13.107) KurobaEx-beta | NavigationControllerContainerLayout: initThreadControllerTracking()
D/(07:43:13.107) KurobaEx-beta | ChanFilterManager: loadFiltersInternal() end, took 49.471875ms
D/(07:43:13.109) KurobaEx-beta | SiteRepository: initializeSites() -> 26 took 2.241979ms
D/(07:43:13.109) KurobaEx-beta | allSitesLoadedInitializer: SuspendableInitializer initWithModularResult() called
D/(07:43:13.109) KurobaEx-beta | allSitesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(07:43:13.109) KurobaEx-beta | allSitesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(07:43:13.109) KurobaEx-beta | allSitesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(07:43:13.109) KurobaEx-beta | SiteRepository: allSitesLoadedInitializer initialized
D/(07:43:13.113) KurobaEx-beta | LynxchanSite: Using domain: 'https://yeshoney.xyz/'
D/(07:43:13.113) KurobaEx-beta | NavigationControllerContainerLayout: initThreadControllerTracking()
D/(07:43:13.113) KurobaEx-beta | ControllerNavigationManager: onControllerPushed(ThreadSlideController)
D/(07:43:13.115) KurobaEx-beta | NavigationControllerContainerLayout: initThreadControllerTracking()
D/(07:43:13.117) KurobaEx-beta | LynxchanSite: Using domain: 'https://kohlchan.net/'
D/(07:43:13.117) KurobaEx-beta | ThreadLayout: ThreadLayout.create(threadControllerType=Catalog)
D/(07:43:13.118) KurobaEx-beta | LynxchanSite: Using domain: 'https://endchan.net/'
D/(07:43:13.119) KurobaEx-beta | ChanPostRepository: Not enough threads to start deleting, threads in database amount: 11196, max allowed threads amount: 12500
D/(07:43:13.119) KurobaEx-beta | ChanPostRepository: SuspendableInitializer initWithValue() called
D/(07:43:13.120) KurobaEx-beta | ChanPostRepository: notifyAllWaiters throwable==null: true, waiters=0
D/(07:43:13.120) KurobaEx-beta | ChanPostRepository: SuspendableInitializer initWithValue() done
D/(07:43:13.132) KurobaEx-beta | Dvach: Using domain: 'https://2ch.hk/'
D/(07:43:13.137) KurobaEx-beta | SiteManager: SuspendableInitializer initWithValue() called
D/(07:43:13.137) KurobaEx-beta | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(07:43:13.137) KurobaEx-beta | BoardManager: loadBoardsInternal() siteDataListAsync.get() end
D/(07:43:13.137) KurobaEx-beta | SiteManager: SuspendableInitializer initWithValue() done
D/(07:43:13.137) KurobaEx-beta | SiteManager: siteRepository.initializeSites() done. Loaded 26 sites
D/(07:43:13.137) KurobaEx-beta | SiteManager: loadSitesInternal() end, took 82.718438ms
D/(07:43:13.191) KurobaEx-beta | BoardRepository: loadAllBoards() -> 1973 took 51.970365ms
D/(07:43:13.194) KurobaEx-beta | BoardManager: SuspendableInitializer initWithValue() called
D/(07:43:13.194) KurobaEx-beta | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(07:43:13.194) KurobaEx-beta | BoardManager: SuspendableInitializer initWithValue() done
D/(07:43:13.194) KurobaEx-beta | BoardManager: loadBoardsInternal() done. Loaded 1973 boards
D/(07:43:13.194) KurobaEx-beta | BoardManager: loadBoardsInternal() end, took 137.746667ms
D/(07:43:13.198) KurobaEx-beta | CacheHandler: diskCacheDir=/data/user/0/com.github.k1rakishou.chan.beta/files/disk_cache, totalFileCacheDiskSize=268.4 MB
D/(07:43:13.200) KurobaEx-beta | InnerCache{0}: cacheFileType=ThreadDownloaderThumbnail, fileCacheDiskSize=13.4 MB
D/(07:43:13.201) KurobaEx-beta | InnerCache{0}: recalculateSize() start
D/(07:43:13.201) KurobaEx-beta | InnerCache{0}: recalculateSize() end took 86.198us, filesOnDiskCount=0, fullyDownloadedFilesCount=0
D/(07:43:13.201) KurobaEx-beta | InnerCache{0}: clearChunksCacheDirInternal() start
D/(07:43:13.201) KurobaEx-beta | InnerCache{0}: clearChunksCacheDirInternal() end
D/(07:43:13.202) KurobaEx-beta | InnerCache{1}: cacheFileType=BookmarkThumbnail, fileCacheDiskSize=13.4 MB
D/(07:43:13.203) KurobaEx-beta | InnerCache{2}: cacheFileType=NavHistoryThumbnail, fileCacheDiskSize=13.4 MB
D/(07:43:13.203) KurobaEx-beta | InnerCache{1}: recalculateSize() start
D/(07:43:13.203) KurobaEx-beta | InnerCache{2}: recalculateSize() start
D/(07:43:13.205) KurobaEx-beta | InnerCache{3}: cacheFileType=SiteIcon, fileCacheDiskSize=13.4 MB
D/(07:43:13.206) KurobaEx-beta | InnerCache{3}: recalculateSize() start
D/(07:43:13.209) KurobaEx-beta | InnerCache{4}: cacheFileType=PostMediaThumbnail, fileCacheDiskSize=13.4 MB
D/(07:43:13.210) KurobaEx-beta | InnerCache{4}: recalculateSize() start
D/(07:43:13.211) KurobaEx-beta | InnerCache{5}: cacheFileType=PostMediaFull, fileCacheDiskSize=174.5 MB
D/(07:43:13.212) KurobaEx-beta | InnerCache{5}: recalculateSize() start
D/(07:43:13.213) KurobaEx-beta | InnerCache{6}: cacheFileType=Other, fileCacheDiskSize=26.8 MB
D/(07:43:13.213) KurobaEx-beta | CacheHandler: CacheHandler.init() took 35.677552ms
D/(07:43:13.216) KurobaEx-beta | NavigationControllerContainerLayout: initBrowseControllerTracker()
E/(07:43:13.217) KurobaEx-beta | ThreadPresenter: isBound() currentChanDescriptor == null
D/(07:43:13.217) KurobaEx-beta | NavigationControllerContainerLayout: initThreadControllerTracking()
D/(07:43:13.219) KurobaEx-beta | ControllerNavigationManager: onControllerSwipedTo(BrowseController)
D/(07:43:13.220) KurobaEx-beta | StartActivity: createUi took 134.849687ms
D/(07:43:13.221) KurobaEx-beta | InnerCache{6}: recalculateSize() start
D/(07:43:13.222) KurobaEx-beta | UpdateManager: autoUpdateCheck()
D/(07:43:13.222) KurobaEx-beta | UpdateManager: autoUpdateCheck() isStableBuild(): false, isBetaBuild(): true, apkUpdateInfo: null
D/(07:43:13.223) KurobaEx-beta | StartActivity: initializeDependencies took 665.834us
D/(07:43:13.223) KurobaEx-beta | StartActivityStartupHandlerHelper: setupFromStateOrFreshLaunch(intent==null: false, savedInstanceState==null: false)
D/(07:43:13.223) KurobaEx-beta | StartActivityStartupHandlerHelper: onNewIntentInternal() -> false
D/(07:43:13.223) KurobaEx-beta | StartActivityStartupHandlerHelper: restoreFromSavedState()
D/(07:43:13.223) KurobaEx-beta | BrowseController: setCatalog(CD{4chan/u})
D/(07:43:13.223) KurobaEx-beta | BrowseController: loadCatalog(CD{4chan/u})
D/(07:43:13.224) KurobaEx-beta | ThreadPresenter: bindChanDescriptor(chanDescriptor=CD{4chan/u})
D/(07:43:13.224) KurobaEx-beta | ThreadPresenter: chanThreadTicker.startTicker(CD{4chan/u})
D/(07:43:13.224) KurobaEx-beta | PageRequestManager: Requesting new board pages for /u/
D/(07:43:13.224) KurobaEx-beta | ChanTicker: startTicker(CD{4chan/u})
D/(07:43:13.224) KurobaEx-beta | ChanTicker: kickTicker(false)
D/(07:43:13.224) KurobaEx-beta | ChanTicker: kickTicker() called with catalog descriptor, ticking right away
D/(07:43:13.230) KurobaEx-beta | BrowseController: showThread(TD{4chan/a/263023116}, ShowThreadOptions(switchToThreadController=true, pushControllerWithAnimation=false))
D/(07:43:13.231) KurobaEx-beta | InnerCache{6}: recalculateSize() end took 9.383854ms, filesOnDiskCount=4, fullyDownloadedFilesCount=0
D/(07:43:13.231) KurobaEx-beta | InnerCache{6}: clearChunksCacheDirInternal() start
D/(07:43:13.231) KurobaEx-beta | InnerCache{6}: clearChunksCacheDirInternal() end
D/(07:43:13.231) KurobaEx-beta | ThreadLayout: ThreadLayout.create(threadControllerType=Thread)
D/(07:43:13.253) KurobaEx-beta | InnerCache{3}: recalculateSize() end took 46.795520ms, filesOnDiskCount=58, fullyDownloadedFilesCount=0
D/(07:43:13.254) KurobaEx-beta | InnerCache{3}: clearChunksCacheDirInternal() start
D/(07:43:13.254) KurobaEx-beta | InnerCache{3}: clearChunksCacheDirInternal() end
D/(07:43:13.253) KurobaEx-beta | ProxyStorage: loadProxies()
D/(07:43:13.255) KurobaEx-beta | ProxyStorage: proxiesFile does not exist, nothing to load
D/(07:43:13.256) KurobaEx-beta | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(07:43:13.258) KurobaEx-beta | CompositeDnsSelector: lookup okHttpUseDnsOverHttps: false
D/(07:43:13.258) KurobaEx-beta | Dependency Injection: Using DnsSelector.Mode.SYSTEM
D/(07:43:13.259) KurobaEx-beta | NavigationControllerContainerLayout: initThreadControllerTracking()
D/(07:43:13.262) KurobaEx-beta | ControllerNavigationManager: onControllerSwipedFrom(BrowseController)
D/(07:43:13.262) KurobaEx-beta | ControllerNavigationManager: onControllerSwipedTo(ViewThreadController)
D/(07:43:13.262) KurobaEx-beta | StartActivity: onCreate() end isFreshStart: false
D/(07:43:13.262) KurobaEx-beta | InnerCache{1}: recalculateSize() end took 59.147864ms, filesOnDiskCount=129, fullyDownloadedFilesCount=0
D/(07:43:13.262) KurobaEx-beta | InnerCache{1}: clearChunksCacheDirInternal() start
D/(07:43:13.262) KurobaEx-beta | InnerCache{1}: clearChunksCacheDirInternal() end
D/(07:43:13.264) KurobaEx-beta | Chan: ^^^ App went foreground ^^^
E/(07:43:13.264) KurobaEx-beta | ThreadPresenter: isBound() currentChanDescriptor (CD{4chan/u}) is not cached
E/(07:43:13.264) KurobaEx-beta | ThreadPresenter: isBound() currentChanDescriptor == null
D/(07:43:13.264) KurobaEx-beta | ApplicationVisibilityManager: onEnteredForeground() callback execution took 143.333us, callbacks count: 5
D/(07:43:13.264) KurobaEx-beta | StartActivity: start
D/(07:43:13.269) KurobaEx-beta | StartActivity: onNewIntent() -> false
D/(07:43:13.323) KurobaEx-beta | InnerCache{5}: recalculateSize() end took 108.925ms, filesOnDiskCount=272, fullyDownloadedFilesCount=0
D/(07:43:13.323) KurobaEx-beta | InnerCache{5}: clearChunksCacheDirInternal() start
D/(07:43:13.323) KurobaEx-beta | InnerCache{5}: clearChunksCacheDirInternal() end
D/(07:43:13.486) KurobaEx-beta | BottomMenuPanel: updatePaddings() state=NotInitialized
D/(07:43:13.486) KurobaEx-beta | BottomMenuPanel: updatePaddings() state=Hidden, visibility: 0, translationY=145.0
D/(07:43:13.521) KurobaEx-beta | InnerCache{4}: recalculateSize() end took 310.959791ms, filesOnDiskCount=2520, fullyDownloadedFilesCount=0
D/(07:43:13.521) KurobaEx-beta | InnerCache{4}: clearChunksCacheDirInternal() start
D/(07:43:13.521) KurobaEx-beta | InnerCache{4}: clearChunksCacheDirInternal() end
D/(07:43:13.550) KurobaEx-beta | InnerCache{2}: recalculateSize() end took 347.091875ms, filesOnDiskCount=1257, fullyDownloadedFilesCount=0
D/(07:43:13.551) KurobaEx-beta | InnerCache{2}: clearChunksCacheDirInternal() start
D/(07:43:13.551) KurobaEx-beta | InnerCache{2}: clearChunksCacheDirInternal() end
D/(07:43:13.553) KurobaEx-beta | AppModuleAndroidUtils: waitForLayout requested a re-layout by returning false
D/(07:43:13.554) KurobaEx-beta | viewModelInitialized: SuspendableInitializer initWithValue() called
D/(07:43:13.555) KurobaEx-beta | viewModelInitialized: notifyAllWaiters throwable==null: true, waiters=0
D/(07:43:13.555) KurobaEx-beta | viewModelInitialized: SuspendableInitializer initWithValue() done
D/(07:43:13.555) KurobaEx-beta | BookmarksManager: persistBookmarks async called
D/(07:43:13.555) KurobaEx-beta | ThreadBookmarkLocalSource: persist(7)
D/(07:43:13.555) KurobaEx-beta | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(07:43:13.556) KurobaEx-beta | BookmarksRepository: persist(7) took 402.24us
D/(07:43:13.556) KurobaEx-beta | ChanTicker: StopTicker
D/(07:43:13.556) KurobaEx-beta | UpdateManager: runUpdateApi() manual=false
D/(07:43:13.556) KurobaEx-beta | UpdateManager: Calling update API for beta (https://api.github.com/repos/K1rakishou/Kuroba-Experimental-beta/releases/latest)
D/(07:43:13.557) KurobaEx-beta | ViewThreadController: loadThread(TD{4chan/a/263023116})
D/(07:43:13.557) KurobaEx-beta | ThreadPresenter: bindChanDescriptor(chanDescriptor=TD{4chan/a/263023116})
D/(07:43:13.558) KurobaEx-beta | ThreadPresenter: chanThreadTicker.startTicker(TD{4chan/a/263023116})
D/(07:43:13.558) KurobaEx-beta | ChanTicker: startTicker(TD{4chan/a/263023116})
D/(07:43:13.558) KurobaEx-beta | ChanTicker: kickTicker(false)
D/(07:43:13.558) KurobaEx-beta | ThreadDownloadManager: initializeThreadDownloadManagerInternal() start
D/(07:43:13.558) KurobaEx-beta | ChanTicker: StartOrResetTicker chanDescriptor=TD{4chan/a/263023116}
D/(07:43:13.558) KurobaEx-beta | CompositeDnsSelector: lookup okHttpUseDnsOverHttps: false
D/(07:43:13.558) KurobaEx-beta | Dependency Injection: Using DnsSelector.Mode.SYSTEM
D/(07:43:13.560) KurobaEx-beta | ThreadDownloadManager: initializeThreadDownloadManagerInternal() end, took 1.825521ms
D/(07:43:13.662) KurobaEx-beta | BookmarksManager: subscriptions=3
D/(07:43:13.662) KurobaEx-beta | BookmarksManager: persistBookmarks async finished
D/(07:43:13.662) KurobaEx-beta | ChanTicker: startOrRestartTickerInternal scheduled, chanDescriptor=TD{4chan/a/263023116}, waiting 0ms
D/(07:43:13.662) KurobaEx-beta | ChanTicker: startOrRestartTickerInternal run action begin
D/(07:43:13.662) KurobaEx-beta | ThreadPresenter: onChanTickerTick(TD{4chan/a/263023116})
D/(07:43:13.662) KurobaEx-beta | ThreadPresenter: normalLoad() start
D/(07:43:13.663) KurobaEx-beta | ThreadPresenter: normalLoad(currentChanDescriptor=TD{4chan/a/263023116}
D/(07:43:13.663) KurobaEx-beta | ThreadPresenter: showLoading=false
D/(07:43:13.663) KurobaEx-beta | ThreadPresenter: chanCacheUpdateOptions=UpdateCache
D/(07:43:13.663) KurobaEx-beta | ThreadPresenter: chanLoadOptions=ChanLoadOptions(chanLoadOption=RetainAll)
D/(07:43:13.663) KurobaEx-beta | ThreadPresenter: chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache])
D/(07:43:13.663) KurobaEx-beta | ThreadPresenter: chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(07:43:13.663) KurobaEx-beta | ChanTicker: startOrRestartTickerInternal run action end
D/(07:43:13.663) KurobaEx-beta | ChanTicker: startOrRestartTickerInternal done, nextTimeoutIndex=1, nextWaitTimeSeconds=20
D/(07:43:13.672) KurobaEx-beta | BookmarkWatcherCoordinator: Calling onBookmarksChanged() because bookmarks have actually changed
D/(07:43:13.672) KurobaEx-beta | BookmarkWatcherCoordinator: onBookmarksChanged() start hasCreateBookmarkChange: false, alreadyRunning: false
D/(07:43:13.673) KurobaEx-beta | ChanThreadManager: loadThreadOrCatalog(null, null, TD{4chan/a/263023116}, UpdateCache, ChanLoadOptions(chanLoadOption=RetainAll), ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(07:43:13.673) KurobaEx-beta | ChanThreadManager: loadInternal() Requested thread /TD{4chan/a/263023116}/
D/(07:43:13.673) KurobaEx-beta | ThreadDataPreloadUseCase: preloadThreadInfo(TD{4chan/a/263023116}) begin
D/(07:43:13.673) KurobaEx-beta | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() start
D/(07:43:13.673) KurobaEx-beta | SeenPostsManager: preloadForThread(TD{4chan/a/263023116}) begin
D/(07:43:13.675) KurobaEx-beta | ChanThreadViewableInfoManager: preloadForThread(TD{4chan/a/263023116}) begin
D/(07:43:13.675) KurobaEx-beta | PostHideManager: preloadForThread(TD{4chan/a/263023116}) begin
D/(07:43:13.675) KurobaEx-beta | SavedReplyManager: preloadForThread(TD{4chan/a/263023116}) begin
D/(07:43:13.676) KurobaEx-beta | ChanPostRepository: preloadForThread(TD{4chan/a/263023116}) begin
D/(07:43:13.680) KurobaEx-beta | BookmarkWatcherCoordinator: onBookmarksChanged() calling startWatchingIfNotWatchingYet()
D/(07:43:13.681) KurobaEx-beta | ThreadLayout: handleLoadProgressEvent() Begin(chanDescriptor=TD{4chan/a/263023116})
D/(07:43:13.692) KurobaEx-beta | ChanPostRepository: preloadForThread(TD{4chan/a/263023116}) got 1 from DB
D/(07:43:13.693) KurobaEx-beta | ChanThread: Thread cache (TD{4chan/a/263023116}) Added 1 new posts, updated 0 posts, marked as deleted 0 posts.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/7cb4359c650371cd07d2d2fa5335a177c3cbdc67
