### ISSUE TITLE
Wrong URL(?) for Warosu.org Archive / No content is shown

### ISSUE THREAD

**Issue by hkvk20212024** [K1rakishou/Kuroba-Experimental#1051]
So I have noticed that in the past couple weeks the warosu.org archive, when I want to look at some deleted shitposts on /vt/, isn't accessible on my device. No update or resets helped but I think the url scheme might be the reason why it doesn't work. It also doesn't work for the other boards that are viewable on warosu. 

The url scheme for Warosu is: https://warosu.org/vt/thread/XXXXXXXX
The url scheme used in KurobaEx is: https://warosu.org/vt/XXXXXXXX

The actual url scheme shows up in the log but no content is shown.

```
[D] 17:32:53.398 CatalogDataPreloadUseCase postloadCatalogInfo(CD{4chan/vt}) begin
[D] 17:32:53.481 SeenPostsManager loadForCatalog(CD{4chan/vt}) threadDescriptorsToLoad=151, seenPostsGrouped=0, alreadyLoadedDescriptorsForUnlimitedCatalog=0
[D] 17:32:53.481 CatalogDataPreloadUseCase postloadCatalogInfo(CD{4chan/vt}) end, took 82.886198ms
[D] 17:32:53.481 ChanThreadManager loadThreadOrCatalog(), descriptor=CD{4chan/vt} postloadCatalogInfo took 83.044584ms
[D] 17:32:53.481 ThreadPresenter normalLoad() threadLoadResult=ThreadLoadResult.Loaded{chanDescriptor=CD{4chan/vt}} (currentChanDescriptor=CD{4chan/vt})
[D] 17:32:53.481 ThreadPresenter onChanLoaderData() called, loadedChanDescriptor=CD{4chan/vt}
[D] 17:32:53.481 KotlinExts awaitUntilGloballyLaidOut(com.github.k1rakishou.chan.ui.view.LoadView{73f0f15 V.E...... ........ 0,0-1020,2340 #7f0a01f2 app:id/loadview}) widthOk=true, width=1020, heightOk=true, height=2340
[D] 17:32:53.481 PostingServiceDelegate listenForPostingStatusUpdates(CD{4chan/vt})
[D] 17:32:53.481 ReplyLayoutViewModel listenForPostingStatusUpdates(CD{4chan/vt}) start
[D] 17:32:53.481 ReplyLayoutState bindChanDescriptor(CD{4chan/vt})
[D] 17:32:53.482 PostHideHelper processPostFilters(CD{4chan/vt}) start
[D] 17:32:53.483 ThreadLayout handleLoadProgressEvent() ApplyingFilters(chanDescriptor=CD{4chan/vt}, postHidesCount=0, postFiltersCount=0)
[D] 17:32:53.483 PostHideHelper processPostFilters(CD{4chan/vt}) end (hiddenPostsCount=0, removedPostsCount=0, normalPostsCount=151, total=151)
[D] 17:32:53.483 ThreadLayout handleLoadProgressEvent() RefreshingPosts(chanDescriptor=CD{4chan/vt})
[D] 17:32:53.483 PostAdapter setThread() notifyDataSetChanged called, postIndexedList.size=151
[D] 17:32:53.483 ThreadCellData runPreloading() start
[D] 17:32:53.483 ThreadCellData runPreloading() startingPosition=0, dataListSize=151
[D] 17:32:53.484 ThreadLayout showPostsForChanDescriptor() showPosts(CD{4chan/vt}) -> true applyFilterDuration=592.083us, setThreadPostsDuration=357.188us, totalDuration=3.051146ms
[D] 17:32:53.485 ThreadPresenter onChanLoaderData(CD{4chan/vt}) end, took 4.441510ms
[D] 17:32:53.485 ThreadPresenter normalLoad() end
[D] 17:32:53.485 ThreadLayout handleLoadProgressEvent() End(chanDescriptor=CD{4chan/vt})
[V] 17:32:53.500 ThumbnailView setUrlInternal(https://i.4cdn.org/vt/1611919211191s.jpg) attempt: 0
[V] 17:32:53.500 ThumbnailView setUrlInternal(https://i.4cdn.org/vt/1711898217535679s.jpg) attempt: 0
[V] 17:32:53.500 ThumbnailView setUrlInternal(https://i.4cdn.org/vt/1711895564672772s.jpg) attempt: 0
[V] 17:32:53.501 CatalogReplyLayoutGlobalState updateCurrentReplyLayoutHeight() height: 0
[V] 17:32:53.501 CatalogReplyLayoutGlobalState updateReplyLayoutVisibility() replyLayoutVisibility: Collapsed
[D] 17:32:53.507 ThreadCellData runPreloading() end, took 23.337552ms
[V] 17:32:53.509 ThumbnailView setUrlInternal(https://i.4cdn.org/vt/1711895564672772s.jpg) attempt: 0, success
[V] 17:32:53.509 ThumbnailView setUrlInternal(https://i.4cdn.org/vt/1611919211191s.jpg) attempt: 0, success
[V] 17:32:53.509 ThumbnailView setUrlInternal(https://i.4cdn.org/vt/1711898217535679s.jpg) attempt: 0, success
[V] 17:32:54.232 MainUiState updateTouchPosition() ACTION_DOWN at Offset(911.0, 470.2)
[V] 17:32:54.904 MainUiState updateTouchPosition() ACTION_UP at Offset.Unspecified
[D] 17:32:54.951 ControllerNavigationManager onControllerPresented(FloatingListMenuController)
[V] 17:32:55.575 MainUiState updateTouchPosition() ACTION_DOWN at Offset(764.1, 1004.9)
[V] 17:32:55.646 MainUiState updateTouchPosition() ACTION_UP at Offset.Unspecified
[D] 17:32:55.653 ControllerNavigationManager onControllerUnpresented(FloatingListMenuController)
[D] 17:32:55.653 ThreadController showAvailableArchivesList(PD(4chan/vt/72654039/72654039,0), false, true)
[D] 17:32:55.653 OpenExternalThreadHelper openExternalThread(PD(warosu.org/vt/72654039/72654039,0))
[D] 17:32:55.654 OpenExternalThreadHelper openExternalThread() loading external thread PD(warosu.org/vt/72654039/72654039,0) from TD{4chan/vt/72654039}
[D] 17:32:55.654 ViewThreadController loadThread(TD{warosu.org/vt/72654039})
[D] 17:32:55.654 ThreadPresenter bindChanDescriptor(chanDescriptor=TD{warosu.org/vt/72654039})
[D] 17:32:55.656 ThreadPresenter unbindChanDescriptor(isDestroying=false) currentChanDescriptor=TD{4chan/vt/72654039}
[D] 17:32:55.656 ThreadPresenter chanThreadTicker.stopTicker(TD{4chan/vt/72654039})
[D] 17:32:55.656 ChanTicker stopTicker(resetCurrentChanDescriptor=true)
[D] 17:32:55.656 ThreadPresenter chanThreadTicker.startTicker(TD{warosu.org/vt/72654039})
[D] 17:32:55.656 ChanTicker startTicker(TD{warosu.org/vt/72654039})
[D] 17:32:55.656 ChanTicker kickTicker(false)
[D] 17:32:55.657 ChanTicker StopTicker
[D] 17:32:55.657 ChanTicker StartOrResetTicker chanDescriptor=TD{warosu.org/vt/72654039}
[D] 17:32:55.657 RefreshChan4CaptchaTicketUseCase Refreshing 4chan captcha ticket, chanDescriptor: TD{warosu.org/vt/72654039}
[D] 17:32:55.657 LoadChan4CaptchaUseCase loadCaptcha(TD{warosu.org/vt/72654039}) requesting https://sys.4chan.org/captcha?framed=1&board=vt&thread_id=72654039
[D] 17:32:55.658 ChanTicker startOrRestartTickerInternal scheduled, chanDescriptor=TD{warosu.org/vt/72654039}, waiting 0ms
[D] 17:32:55.658 ChanTicker startOrRestartTickerInternal run action begin
[D] 17:32:55.658 ThreadPresenter onChanTickerTick(TD{warosu.org/vt/72654039})
[D] 17:32:55.658 ThreadPresenter normalLoad() start
[D] 17:32:55.658 ThreadPresenter normalLoad(currentChanDescriptor=TD{warosu.org/vt/72654039}
showLoading=false
chanCacheUpdateOptions=UpdateCache
chanLoadOptions=ChanLoadOptions(chanLoadOption=RetainAll)
chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache])
chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
[D] 17:32:55.658 ChanTicker startOrRestartTickerInternal run action end
[D] 17:32:55.658 ChanTicker startOrRestartTickerInternal done, nextTimeoutIndex=1, nextWaitTimeSeconds=120
[W] 17:32:55.658 SiteRequestModifier addCloudFlareCookie() cookieForDomain '4chan.org' is null or empty: 'null'
[D] 17:32:55.659 ChanThreadManager loadThreadOrCatalog(null, null, TD{warosu.org/vt/72654039}, UpdateCache, ChanLoadOptions(chanLoadOption=RetainAll), ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
[D] 17:32:55.659 ChanThreadManager loadInternal() Requested thread /TD{warosu.org/vt/72654039}/
[D] 17:32:55.659 ThreadDataPreloadUseCase preloadThreadInfo(TD{warosu.org/vt/72654039}) begin
[D] 17:32:55.659 SavedReplyManager preloadForThread(TD{warosu.org/vt/72654039}) begin
[D] 17:32:55.659 SeenPostsManager preloadForThread(TD{warosu.org/vt/72654039}) begin
[D] 17:32:55.659 PostHideManager preloadForThread(TD{warosu.org/vt/72654039}) begin
[D] 17:32:55.659 ThreadLayout handleLoadProgressEvent() Begin(chanDescriptor=TD{warosu.org/vt/72654039})
[D] 17:32:55.660 SeenPostsManager preloadForThread(TD{warosu.org/vt/72654039}) end, took 681.302us
[D] 17:32:55.660 PostHideManager chanPostHideRepository.preloadForThreadInternal() preloaded 0 post hides
[D] 17:32:55.660 PostHideManager preloadForThread(TD{warosu.org/vt/72654039}) end, took 1.201302ms
[D] 17:32:55.661 SavedReplyManager preloadForThread(TD{warosu.org/vt/72654039}) end, took 1.742031ms
[D] 17:32:55.661 ChanPostRepository preloadForThread(TD{warosu.org/vt/72654039}) begin
[D] 17:32:55.661 ChanPostRepository preloadForThread(TD{warosu.org/vt/72654039}) got 0 from DB
[D] 17:32:55.661 ChanPostRepository preloadForThread(TD{warosu.org/vt/72654039}) end, took 140.468us
[D] 17:32:55.663 ThreadDataPreloadUseCase preloadThreadInfo(TD{warosu.org/vt/72654039}) end, took 4.217344ms
[D] 17:32:55.663 ChanThreadManager loadInternal(), chanDescriptor=TD{warosu.org/vt/72654039} preloadThreadInfo took 4.343906ms
[D] 17:32:55.663 ChanThreadManager loadInternal() chanThreadsCache.cacheNeedsUpdate(TD{warosu.org/vt/72654039}, UpdateCache) -> true
[D] 17:32:55.663 ChanThreadLoaderCoordinator loadThreadOrCatalog(chanLoadUrl=ChanLoadUrl(url=https://warosu.org/vt/thread/72654039, isIncremental=false, page=null), compositeCatalogDescriptor=null, chanDescriptor=TD{warosu.org/vt/72654039}, chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), chanCacheUpdateOptions=UpdateCache, chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647), chanReader=FuukaApi, postProcessFlags=null)
[D] 17:32:55.664 ThreadLayout handleLoadProgressEvent() Loading(chanDescriptor=TD{warosu.org/vt/72654039})
[W] 17:32:55.664 SiteRequestModifier addCloudFlareCookie() cookieForDomain 'warosu.org' is null or empty: 'null'
[D] 17:32:55.708 CloudFlareHandlerInterceptor Ignoring CloudFlare bot detection errors for request 'https://sys.4chan.org/captcha?framed=1&board=vt&thread_id=72654039'
[D] 17:32:55.709 RefreshChan4CaptchaTicketUseCase Refreshing 4chan captcha ticket done, chanDescriptor: TD{warosu.org/vt/72654039}
[E] 17:32:55.709 RefreshChan4CaptchaTicketUseCase loadChan4CaptchaUseCase.await() error: Bad status: 403 (BadStatusResponseException) 
[D] 17:32:56.731 ThreadLayout handleLoadProgressEvent() Reading(chanDescriptor=TD{warosu.org/vt/72654039})
[D] 17:32:56.915 ChanThreadLoaderCoordinator loadThreadOrCatalog(chanLoadUrl='ChanLoadUrl(url=https://warosu.org/vt/thread/72654039, isIncremental=false, page=null)') chanReaderProcessor=ChanReaderProcessor{chanDescriptor=TD{warosu.org/vt/72654039}, toParse=0, closed=false, deleted=false, archived=false, error=null}
[D] 17:32:56.915 NormalPostLoader persistPosts(TD{warosu.org/vt/72654039}, ChanReaderProcessor{chanDescriptor=TD{warosu.org/vt/72654039}, toParse=0, closed=false, deleted=false, archived=false, error=null}, ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), UpdateCache, DefaultPostParser)
[D] 17:32:56.915 StoreNewPostsUseCase storePosts(parsedPostsCount=0, chanDescriptor=TD{warosu.org/vt/72654039}) -> 0
[D] 17:32:56.915 ThreadLayout handleLoadProgressEvent() PersistingPosts(chanDescriptor=TD{warosu.org/vt/72654039}, postsCount=0)
[E] 17:32:56.915 FuukaApi parserCommandExecutor.executeCommands() error
Exception title: IllegalCallableAccessException
Exception body: Failed to execute command: StepCommand{htmlElement=table{matchables=[PatternMatchable(attrName=itemtype, matcher=KurobaStringContains{string=http://schema.org/Comment})], extractor=Extractor{extractorParams=KurobaAttribute{checkAttributeKeysMap={}, extractAttributeValues=[]}}}}, nodesCount: 766, startIndex=0, commandIndex=40, (url='null') kotlin.reflect.full.IllegalCallableAccessException: Failed to execute command: StepCommand{htmlElement=table{matchables=[PatternMatchable(attrName=itemtype, matcher=KurobaStringContains{string=http://schema.org/Comment})], extractor=Extractor{extractorParams=KurobaAttribute{checkAttributeKeysMap={}, extractAttributeValues=[]}}}}, nodesCount: 766, startIndex=0, commandIndex=40, (url='null') 
	at com.github.k1rakishou.core_parser.html.KurobaHtmlParserCommandExecutor.executeCommands(SourceFile:602)
	at com.github.k1rakishou.chan.core.site.sites.fuuka.FuukaApi$loadThreadFresh$2.invokeSuspend(SourceFile:80)
	at com.github.k1rakishou.chan.core.site.sites.fuuka.FuukaApi.loadThreadFresh(SourceFile:83)
	at com.github.k1rakishou.chan.core.site.loader.ChanThreadLoaderCoordinator.readPostsFromResponse(SourceFile:175)
	at com.github.k1rakishou.chan.core.site.loader.ChanThreadLoaderCoordinator$loadThreadOrCatalog$2.invokeSuspend(SourceFile:1785)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:94)
	at androidx.work.Worker$2.run(SourceFile:31)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:96)
 
 
[D] 17:32:56.916 ChanThreadLoaderCoordinator ChanReaderRequest.readJson() stats:
url = https://warosu.org/vt/thread/72654039.
Network request execution took 1.067030051s.
Json reading took 183.871979ms.
Store new posts took 72.083us (stored 0 posts).
Parse posts took 0s (parsed 0 out of 0 posts).
Filter processing took 0s (filers count: 0).
Total in-memory cached posts count: 877/13107.
Threads with more than one post count: (1/8), total cached threads count: 152.
Total local processing time: 183.944062ms
 
[D] 17:32:56.917 ThreadDataPreloadUseCase postloadThreadInfo(TD{warosu.org/vt/72654039}) begin
[D] 17:32:56.917 ThreadDataPreloadUseCase postloadThreadInfo(TD{warosu.org/vt/72654039}) end
[D] 17:32:56.917 ChanThreadManager loadThreadOrCatalog(), descriptor=TD{warosu.org/vt/72654039} postloadThreadInfo took 131.563us
[D] 17:32:56.917 ThreadPresenter normalLoad() threadLoadResult=ThreadLoadResult.Loaded{chanDescriptor=TD{warosu.org/vt/72654039}} (currentChanDescriptor=TD{warosu.org/vt/72654039})
[D] 17:32:56.917 ThreadPresenter onChanLoaderData() called, loadedChanDescriptor=TD{warosu.org/vt/72654039}
[D] 17:32:56.917 KotlinExts awaitUntilGloballyLaidOut(com.github.k1rakishou.chan.ui.view.LoadView{e68616 V.E...... .......D 0,0-1080,2340 #7f0a01f2 app:id/loadview}) widthOk=true, width=1080, heightOk=true, height=2340
[D] 17:32:56.918 ReplyLayoutViewModel listenForPostingStatusUpdates(TD{4chan/vt/72654039}) end
[D] 17:32:56.918 PostingServiceDelegate listenForPostingStatusUpdates(TD{warosu.org/vt/72654039})
[D] 17:32:56.919 ReplyLayoutViewModel listenForPostingStatusUpdates(TD{warosu.org/vt/72654039}) start
[D] 17:32:56.919 ReplyLayoutState bindChanDescriptor(TD{warosu.org/vt/72654039})
[D] 17:32:56.922 PostHideHelper processPostFilters(TD{warosu.org/vt/72654039}) start
[D] 17:32:56.922 ThreadLayout handleLoadProgressEvent() ApplyingFilters(chanDescriptor=TD{warosu.org/vt/72654039}, postHidesCount=0, postFiltersCount=0)
[D] 17:32:56.922 PostHideHelper processPostFilters(TD{warosu.org/vt/72654039}) end (hiddenPostsCount=0, removedPostsCount=0, normalPostsCount=0, total=0)
[D] 17:32:56.923 ThreadLayout handleLoadProgressEvent() RefreshingPosts(chanDescriptor=TD{warosu.org/vt/72654039})
[D] 17:32:56.923 PostAdapter setThread() notifyDataSetChanged called, postIndexedList.size=0
[D] 17:32:56.924 ThreadLayout showPostsForChanDescriptor() showPosts(TD{warosu.org/vt/72654039}) -> true applyFilterDuration=842.917us, setThreadPostsDuration=485.104us, totalDuration=6.329948ms
[E] 17:32:56.926 ThreadPresenter handleMarkedPost() Failed to find post (TD{warosu.org/vt/72654039}, 72654039)
[D] 17:32:56.934 ThreadPresenter onChanLoaderData(TD{warosu.org/vt/72654039}) end, took 16.800365ms
[D] 17:32:56.934 ThreadPresenter normalLoad() end
[D] 17:32:56.934 ThreadLayout handleLoadProgressEvent() End(chanDescriptor=TD{warosu.org/vt/72654039})
[V] 17:32:56.940 ThreadReplyLayoutGlobalState updateCurrentReplyLayoutHeight() height: 0
[V] 17:32:56.941 ThreadReplyLayoutGlobalState updateReplyLayoutVisibility() replyLayoutVisibility: Collapsed
[V] 17:32:57.645 MainUiState updateTouchPosition() ACTION_DOWN at Offset(995.4, 2260.6)
[V] 17:32:57.707 MainUiState updateTouchPosition() ACTION_UP at Offset.Unspecified
[D] 17:32:57.708 ControllerNavigationManager onCloseAllNonMainControllers()
[D] 17:32:57.715 ControllerNavigationManager onControllerPushed(MainSettingsControllerV2)
[D] 17:32:57.729 screensBuiltOnce SuspendableInitializer awaitUntilInitialized() called when not initialized, awaiting...
[D] 17:32:57.729 screensBuiltOnce SuspendableInitializer initWithValue() called
[D] 17:32:57.730 screensBuiltOnce notifyAllWaiters throwable==null: true, waiters=0
[D] 17:32:57.730 screensBuiltOnce SuspendableInitializer initWithValue() done
[D] 17:32:57.731 screensBuiltOnce SuspendableInitializer awaitUntilInitialized() called when not initialized, done (diffTime=2ms)
[D] 17:32:57.733 screensBuiltOnce SuspendableInitializer initWithValue() called
[D] 17:32:57.733 screensBuiltOnce SuspendableInitializer initWithValue() already completed, exiting
[V] 17:32:58.017 MainUiState updateTouchPosition() ACTION_DOWN at Offset(917.1, 1520.2)
[V] 17:32:58.103 MainUiState updateTouchPosition() ACTION_UP at Offset.Unspecified
[V] 17:33:01.642 MainUiState updateTouchPosition() ACTION_DOWN at Offset(827.7, 2066.9)
[V] 17:33:01.712 MainUiState updateTouchPosition() ACTION_UP at Offset.Unspecified
[D] 17:33:01.722 screensBuiltOnce SuspendableInitializer initWithValue() called
[D] 17:33:01.722 screensBuiltOnce SuspendableInitializer initWithValue() already completed, exiting
[V] 17:33:02.843 MainUiState updateTouchPosition() ACTION_DOWN at Offset(790.5, 1663.6)
[V] 17:33:02.897 MainUiState updateTouchPosition() ACTION_UP at Offset.Unspecified
[E] 17:33:02.922 Chan Unhandled exception in thread: main
Exception title: RuntimeException
Exception body: Exception while trying to handle coroutine exceptionjava.lang.RuntimeException: Exception while trying to handle coroutine exception
	at coil.size.-Sizes.handleCoroutineException(SourceFile:28)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Unknown Source:2)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(SourceFile:106)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(SourceFile:243)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(SourceFile:5)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(SourceFile:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:37)
	at coil.size.-Sizes.resume(SourceFile:1)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(SourceFile:81)
	at kotlinx.coroutines.CancellableContinuationImpl.completeResume(Unknown Source:2)
	at kotlinx.coroutines.channels.BufferedChannelKt.tryResume0(Unknown Source:6)
	at kotlinx.coroutines.channels.BufferedChannel.tryResumeReceiver(SourceFile:92)
	at kotlinx.coroutines.channels.BufferedChannel.access$updateCellSend(SourceFile:57)
	at kotlinx.coroutines.channels.BufferedChannel.trySend-JP2dKIU(SourceFile:115)
	at com.github.k1rakishou.chan.core.base.SerializedCoroutineExecutor.post(SourceFile:16)
	at androidx.compose.ui.window.AndroidPopup_androidKt$Popup$2$1.invoke(SourceFile:1011)
	at com.github.k1rakishou.chan.features.setup.epoxy.site.EpoxySiteView$$ExternalSyntheticLambda1.onClick(SourceFile:13)
	at android.view.View.performClick(View.java:7892)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30891)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: java.lang.RuntimeException: java.lang.RuntimeException: Debug crash
		at com.github.k1rakishou.chan.features.settings.MainSettingsControllerV2$postThrowable$1.invokeSuspend(SourceFile:43)
		at com.github.k1rakishou.chan.features.settings.MainSettingsControllerV2$postThrowable$1.invoke(SourceFile:11)
		at com.github.k1rakishou.chan.core.base.SerializedCoroutineExecutor$1.invokeSuspend(SourceFile:104)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
		... 22 more
	Caused by: java.lang.RuntimeException: Debug crash
		at com.github.k1rakishou.chan.features.settings.screens.DeveloperSettingsScreen$buildMainSettingsGroup$1$9.invokeSuspend(SourceFile:10)
		at com.github.k1rakishou.chan.features.settings.screens.DeveloperSettingsScreen$buildMainSettingsGroup$1$9.invoke(SourceFile:11)
		at com.github.k1rakishou.chan.features.settings.setting.LinkSettingV2$Companion$createBuilder$buildFunc$4.invokeSuspend(SourceFile:29)
		at com.github.k1rakishou.chan.features.settings.setting.LinkSettingV2$Companion$createBuilder$buildFunc$4.invoke(SourceFile:11)
		at com.github.k1rakishou.chan.features.settings.MainSettingsControllerV2$renderSettingInternal$1$1$1.invokeSuspend(SourceFile:37)
		at com.github.k1rakishou.chan.features.settings.MainSettingsControllerV2$renderSettingInternal$1$1$1.invoke(SourceFile:11)
		at com.github.k1rakishou.chan.features.settings.MainSettingsControllerV2$postThrowable$1.invokeSuspend(SourceFile:31)
		... 25 more
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.text.font.FontListFontFamilyTypefaceAdapter$special$$inlined$CoroutineExceptionHandler$1@24a99f6, StandaloneCoroutine{Cancelling}@ef0b1f7, Dispatchers.Main.immediate]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Debug crash
	at androidx.compose.ui.text.font.FontListFontFamilyTypefaceAdapter$special$$inlined$CoroutineExceptionHandler$1.handleException(SourceFile:20)
	at coil.size.-Sizes.handleCoroutineException(SourceFile:11)
	... 28 more
Caused by: [CIRCULAR REFERENCE: java.lang.RuntimeException: java.lang.RuntimeException: Debug crash]
 
 
[D] 17:33:02.948 CrashReportActivity CrashReportActivity launched
[E] 17:33:02.950 CrashReportActivity Got new exception: java.lang.RuntimeException
[D] 17:33:03.446 StartActivity stop
[D] 17:33:03.451 ReplyLayoutViewModel listenForPostingStatusUpdates(CD{4chan/vt}) end
[D] 17:33:03.453 ReplyLayoutViewModel listenForPostingStatusUpdates(TD{warosu.org/vt/72654039}) end
[D] 17:33:03.455 ThreadLayout ThreadLayout.destroy(threadControllerType=Catalog)
[D] 17:33:03.455 ThreadPresenter unbindChanDescriptor(isDestroying=true) currentChanDescriptor=CD{4chan/vt}
[D] 17:33:03.456 ThreadPresenter chanThreadTicker.stopTicker(CD{4chan/vt})
[D] 17:33:03.456 ChanTicker stopTicker(resetCurrentChanDescriptor=true)
[D] 17:33:03.459 NavigationControllerContainerLayout initThreadControllerTracking()
[D] 17:33:03.459 ThreadLayout ThreadLayout.destroy(threadControllerType=Thread)
[D] 17:33:03.460 ThreadPresenter unbindChanDescriptor(isDestroying=true) currentChanDescriptor=TD{warosu.org/vt/72654039}
[D] 17:33:03.460 ThreadPresenter chanThreadTicker.stopTicker(TD{warosu.org/vt/72654039})
[D] 17:33:03.460 ChanTicker stopTicker(resetCurrentChanDescriptor=true)
[D] 17:33:03.461 NavigationControllerContainerLayout initThreadControllerTracking()
[D] 17:33:03.461 NavigationControllerContainerLayout initThreadControllerTracking()
[D] 17:33:03.462 BottomMenuPanel hide(0), prevState=Hidden
[D] 17:33:03.463 StartActivity onDestroy()
```

**Comment by K1rakishou** [comment]
Will be fixed in the next beta.
