### ISSUE TITLE
Crash report "kotlin.UninitializedPropertyAccessException: lateinit property threadLayout has not been initialized"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#170]
Crash report
UUID: 4383d0c406b610161ec58008f06d752f
Build flavor: beta
Version name: v0.2.4
OS info: Android 9, sdk version: 28
Report description: No title
Logs:
```
=== LOGS(2020-09-27 10:11:11 UTC) ===
D/KurobaEx-beta | FileCacheV2: [main]: Downloading a file, url = https://i.4cdn.org/v/1601165077XXX.jpg
D/KurobaEx-beta | FileCacheV2: [main]: Downloading a file, url = https://i.4cdn.org/v/1601166025XXX.png
D/KurobaEx-beta | FileCacheV2: [pool-9-thread-1]: Downloading a file, url = https://i.4cdn.org/v/1601180903XXX.png
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-3]: Download ([FileDownloadRequest: url = https://i.4cdn.org/v/1601165077XXX.jpg, outputFileName = d8b8f6f2ce4fe974ff35e2b8960f98f9.cache]) has started. Chunks count = 2. Network class = WIFI. Downloads = 2
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-3]: Starting downloading (https://i.4cdn.org/v/1601165077XXX.jpg)
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-1]: Download ([FileDownloadRequest: url = https://i.4cdn.org/v/1601180903XXX.png, outputFileName = 1d08c15f8759dcb84d9bbd9a6afea440.cache]) has started. Chunks count = 2. Network class = WIFI. Downloads = 2
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-1]: Starting downloading (https://i.4cdn.org/v/1601180903XXX.png)
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-2]: Download ([FileDownloadRequest: url = https://i.4cdn.org/v/1601166025XXX.png, outputFileName = 4ae0d9a29a31831c621818f01d0ebdaf.cache]) has started. Chunks count = 2. Network class = WIFI. Downloads = 2
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-2]: Starting downloading (https://i.4cdn.org/v/1601166025XXX.png)
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-0]: storeChunkInFile(0) success, url = https://i.4cdn.org/v/1601165077XXX.jpg, chunk 0..89695
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-0]: storeChunkInFile(0) success, url = https://i.4cdn.org/v/1601166025XXX.png, chunk 0..5850
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-0]: storeChunkInFile(1) success, url = https://i.4cdn.org/v/1601166025XXX.png, chunk 5851..11701
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-0]: Success (downloaded = 11,7 kB (11702 B), total = 11,7 kB (11702 B), took 120ms, network class = WIFI, downloads = 2) for request [FileDownloadRequest: url = https://i.4cdn.org/v/1601166025XXX.png, outputFileName = 4ae0d9a29a31831c621818f01d0ebdaf.cache]
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-0]: Completed downloading (https://i.4cdn.org/v/1601166025XXX.png)
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-2]: storeChunkInFile(0) success, url = https://i.4cdn.org/v/1601180903XXX.png, chunk 0..199194
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-3]: storeChunkInFile(1) success, url = https://i.4cdn.org/v/1601165077XXX.jpg, chunk 89696..179392
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-1]: storeChunkInFile(1) success, url = https://i.4cdn.org/v/1601180903XXX.png, chunk 199195..398389
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-3]: Success (downloaded = 179,4 kB (179393 B), total = 179,4 kB (179393 B), took 184ms, network class = WIFI, downloads = 1) for request [FileDownloadRequest: url = https://i.4cdn.org/v/1601165077XXX.jpg, outputFileName = d8b8f6f2ce4fe974ff35e2b8960f98f9.cache]
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-3]: Completed downloading (https://i.4cdn.org/v/1601165077XXX.jpg)
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-1]: Success (downloaded = 398,4 kB (398390 B), total = 398,4 kB (398390 B), took 179ms, network class = WIFI, downloads = 0) for request [FileDownloadRequest: url = https://i.4cdn.org/v/1601180903XXX.png, outputFileName = 1d08c15f8759dcb84d9bbd9a6afea440.cache]
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-1]: Completed downloading (https://i.4cdn.org/v/1601180903XXX.png)
D/KurobaEx-beta | CustomScaleImageView: onImageLoaded
D/KurobaEx-beta | FileCacheV2: [pool-9-thread-1]: Downloading a file, url = https://i.4cdn.org/v/1601192193XXX.jpg
D/KurobaEx-beta | FileCacheV2: [main]: Downloading a file, url = https://i.4cdn.org/v/1601184025XXX.jpg
D/KurobaEx-beta | FileCacheV2: [main]: Downloading a file, url = https://i.4cdn.org/v/1601186586XXX.png
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-1]: Download ([FileDownloadRequest: url = https://i.4cdn.org/v/1601192193XXX.jpg, outputFileName = f6aca257dbbbc4b60338e2190182a70c.cache]) has started. Chunks count = 2. Network class = WIFI. Downloads = 2
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-1]: Starting downloading (https://i.4cdn.org/v/1601192193XXX.jpg)
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-1]: Download ([FileDownloadRequest: url = https://i.4cdn.org/v/1601186586XXX.png, outputFileName = b143efa2f36d6e0c9822becebb587ae1.cache]) has started. Chunks count = 2. Network class = WIFI. Downloads = 2
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-3]: Starting downloading (https://i.4cdn.org/v/1601186586XXX.png)
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-0]: Download ([FileDownloadRequest: url = https://i.4cdn.org/v/1601184025XXX.jpg, outputFileName = b5063d0c3500f3429e0bebd69511ff9f.cache]) has started. Chunks count = 2. Network class = WIFI. Downloads = 2
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-0]: Starting downloading (https://i.4cdn.org/v/1601184025XXX.jpg)
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-1]: storeChunkInFile(1) success, url = https://i.4cdn.org/v/1601192193XXX.jpg, chunk 140225..280449
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-2]: storeChunkInFile(1) success, url = https://i.4cdn.org/v/1601184025XXX.jpg, chunk 49057..98113
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-3]: storeChunkInFile(0) success, url = https://i.4cdn.org/v/1601192193XXX.jpg, chunk 0..140224
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-2]: storeChunkInFile(0) success, url = https://i.4cdn.org/v/1601184025XXX.jpg, chunk 0..49056
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-0]: storeChunkInFile(1) success, url = https://i.4cdn.org/v/1601186586XXX.png, chunk 241050..482099
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-1]: storeChunkInFile(0) success, url = https://i.4cdn.org/v/1601186586XXX.png, chunk 0..241049
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-2]: Success (downloaded = 98,1 kB (98114 B), total = 98,1 kB (98114 B), took 217ms, network class = WIFI, downloads = 2) for request [FileDownloadRequest: url = https://i.4cdn.org/v/1601184025XXX.jpg, outputFileName = b5063d0c3500f3429e0bebd69511ff9f.cache]
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-3]: Success (downloaded = 280,5 kB (280450 B), total = 280,5 kB (280450 B), took 244ms, network class = WIFI, downloads = 2) for request [FileDownloadRequest: url = https://i.4cdn.org/v/1601192193XXX.jpg, outputFileName = f6aca257dbbbc4b60338e2190182a70c.cache]
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-3]: Completed downloading (https://i.4cdn.org/v/1601192193XXX.jpg)
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-2]: Completed downloading (https://i.4cdn.org/v/1601184025XXX.jpg)
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-1]: Success (downloaded = 482,1 kB (482100 B), total = 482,1 kB (482100 B), took 233ms, network class = WIFI, downloads = 0) for request [FileDownloadRequest: url = https://i.4cdn.org/v/1601186586XXX.png, outputFileName = b143efa2f36d6e0c9822becebb587ae1.cache]
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-1]: Completed downloading (https://i.4cdn.org/v/1601186586XXX.png)
D/KurobaEx-beta | CustomScaleImageView: onReady
D/KurobaEx-beta | CustomScaleImageView: onImageLoaded
D/KurobaEx-beta | BrowseController: loadBoard(BD{4chan/b})
D/KurobaEx-beta | ThreadPresenter: chanLoaderManager.release(CD{4chan/v})
D/KurobaEx-beta | ThreadPresenter: chanLoaderManager.obtain(CD{4chan/b})
D/KurobaEx-beta | PostHideManager: chanPostHideRepository.preloadForCatalogInternal() preloaded 0 post hides
D/KurobaEx-beta | ChanThreadLoader: Requested catalog /CD{4chan/b}/
D/KurobaEx-beta | ChanThreadLoaderCoordinator: loadThread(https://a.4cdn.org/b/catalog.json, ChanLoaderRequestParams{chanDescriptor=CD{4chan/b}, chanReader=FutabaChanReader, cached.size=0})
D/KurobaEx-beta | BrowseController: loadBoard(BD{4chan/b})
D/KurobaEx-beta | ChanThreadLoader: Requested catalog /CD{4chan/b}/
D/KurobaEx-beta | ChanThreadLoaderCoordinator: loadThread(https://a.4cdn.org/b/catalog.json, ChanLoaderRequestParams{chanDescriptor=CD{4chan/b}, chanReader=FutabaChanReader, cached.size=0})
D/KurobaEx-beta | ChanThreadLoader: Request canceled
D/KurobaEx-beta | ChanThreadLoaderCoordinator: loadThread from network took 214ms
D/KurobaEx-beta | StoreNewPostsUseCase: storePosts(postsCount=150, isCatalog=true)
D/KurobaEx-beta | HistoryNavigationManager: persistNavigationStack async called
D/KurobaEx-beta | HistoryNavigationManager: persistNavigationStack async finished
D/KurobaEx-beta | NormalPostLoader: ChanReaderRequest.readJson() stats: url = <url hidden>.
D/KurobaEx-beta | NormalPostLoader: Store new posts took 356ms (stored 150 posts).
D/KurobaEx-beta | NormalPostLoader: Reload posts took 141ms, (reloaded 150 posts, from cache: 150, from database: 0).
D/KurobaEx-beta | NormalPostLoader: Parse posts took = 132ms, (parsed 150 out of 150 posts).
D/KurobaEx-beta | NormalPostLoader: Total in-memory cached posts count = (802/19660).
D/KurobaEx-beta | ThreadPresenter: onChanLoaderData() called
D/KurobaEx-beta | PageRequestManager: Requesting new board pages for /b/
D/KurobaEx-beta | JsonReaderRequest: Request "Chan4Pages" to "https://a.4cdn.org/b/threads.json" took 68.883854ms
D/KurobaEx-beta | PageRequestManager: Got pages for 4chan/b/
D/KurobaEx-beta | FileCacheV2: [pool-9-thread-1]: Downloading a file, url = https://i.4cdn.org/b/1601192291XXX.jpg
D/KurobaEx-beta | FileCacheV2: [main]: Downloading a file, url = https://i.4cdn.org/b/1601177330XXX.jpg
D/KurobaEx-beta | FileCacheV2: [main]: Downloading a file, url = https://i.4cdn.org/b/1601188947XXX.jpg
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-1]: Download ([FileDownloadRequest: url = https://i.4cdn.org/b/1601192291XXX.jpg, outputFileName = 45af012d2e0daa4bb872bec456728da3.cache]) has started. Chunks count = 2. Network class = WIFI. Downloads = 2
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-1]: Starting downloading (https://i.4cdn.org/b/1601192291XXX.jpg)
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-2]: Download ([FileDownloadRequest: url = https://i.4cdn.org/b/1601188947XXX.jpg, outputFileName = bedc7c619cd43106be70b434dad26974.cache]) has started. Chunks count = 2. Network class = WIFI. Downloads = 2
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-3]: Download ([FileDownloadRequest: url = https://i.4cdn.org/b/1601177330XXX.jpg, outputFileName = 0e3e4261552aef0a937293e234fd1909.cache]) has started. Chunks count = 2. Network class = WIFI. Downloads = 2
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-3]: Starting downloading (https://i.4cdn.org/b/1601188947XXX.jpg)
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-1]: Starting downloading (https://i.4cdn.org/b/1601177330XXX.jpg)
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-0]: storeChunkInFile(0) success, url = https://i.4cdn.org/b/1601192291XXX.jpg, chunk 0..103446
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-3]: storeChunkInFile(0) success, url = https://i.4cdn.org/b/1601188947XXX.jpg, chunk 0..71059
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-2]: storeChunkInFile(1) success, url = https://i.4cdn.org/b/1601192291XXX.jpg, chunk 103447..206893
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-0]: storeChunkInFile(1) success, url = https://i.4cdn.org/b/1601188947XXX.jpg, chunk 71060..142120
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-2]: Success (downloaded = 206,9 kB (206894 B), total = 206,9 kB (206894 B), took 140ms, network class = WIFI, downloads = 2) for request [FileDownloadRequest: url = https://i.4cdn.org/b/1601192291XXX.jpg, outputFileName = 45af012d2e0daa4bb872bec456728da3.cache]
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-2]: Completed downloading (https://i.4cdn.org/b/1601192291XXX.jpg)
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-0]: Success (downloaded = 142,1 kB (142121 B), total = 142,1 kB (142121 B), took 124ms, network class = WIFI, downloads = 1) for request [FileDownloadRequest: url = https://i.4cdn.org/b/1601188947XXX.jpg, outputFileName = bedc7c619cd43106be70b434dad26974.cache]
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-0]: Completed downloading (https://i.4cdn.org/b/1601188947XXX.jpg)
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-1]: storeChunkInFile(1) success, url = https://i.4cdn.org/b/1601177330XXX.jpg, chunk 156774..313547
D/KurobaEx-beta | ChunkReader: [NormalFileCacheV2Thread-3]: storeChunkInFile(0) success, url = https://i.4cdn.org/b/1601177330XXX.jpg, chunk 0..156773
D/KurobaEx-beta | FileCacheV2: [NormalFileCacheV2Thread-3]: Success (downloaded = 313,5 kB (313548 B), total = 313,5 kB (313548 B), took 173ms, network class = WIFI, downloads = 0) for request [FileDownloadRequest: url = https://i.4cdn.org/b/1601177330XXX.jpg, outputFileName = 0e3e4261552aef0a937293e234fd1909.cache]
D/KurobaEx-beta | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-3]: Completed downloading (https://i.4cdn.org/b/1601177330XXX.jpg)
D/KurobaEx-beta | CustomScaleImageView: onReady
D/KurobaEx-beta | CustomScaleImageView: onImageLoaded
D/KurobaEx-beta | ThreadLayout: showThread(TD{4chan/b/836744207})
D/KurobaEx-beta | BrowseController: showThread(TD{4chan/b/836744207}, true)
D/KurobaEx-beta | ViewThreadController: loadThread(TD{4chan/b/836744207})
D/KurobaEx-beta | ThreadPresenter: chanLoaderManager.obtain(TD{4chan/b/836744207})
D/KurobaEx-beta | PostHideManager: chanPostHideRepository.preloadForThreadInternal() preloaded 0 post hides
D/KurobaEx-beta | ChanThreadLoader: Requested thread /TD{4chan/b/836744207}/
D/KurobaEx-beta | ChanThreadLoaderCoordinator: loadThread(https://a.4cdn.org/b/thread/836744207.json, ChanLoaderRequestParams{chanDescriptor=TD{4chan/b/836744207}, chanReader=FutabaChanReader, cached.size=0})
D/KurobaEx-beta | ThreadLayout: showThread(TD{4chan/b/836744207})
D/KurobaEx-beta | BrowseController: showThread(TD{4chan/b/836744207}, true)
E/KurobaEx-beta | Chan: Unhandled exception
E/KurobaEx-beta | Chan: kotlin.UninitializedPropertyAccessException: lateinit property threadLayout has not been initialized
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.ui.controller.ThreadController.setDrawerCallbacks(ThreadController.kt:70)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.ui.controller.BrowseController$showThread$2.invokeSuspend(BrowseController.kt:736)
E/KurobaEx-beta | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:333)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:49)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.ui.controller.BrowseController.showThread(BrowseController.kt:670)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.ui.layout.ThreadLayout.showThread(ThreadLayout.kt:433)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.presenter.ThreadPresenter$onPostClicked$1.invokeSuspend(ThreadPresenter.kt:833)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.presenter.ThreadPresenter$onPostClicked$1.invoke(Unknown Source:10)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.base.SerializedCoroutineExecutor$1.invokeSuspend(SerializedCoroutineExecutor.kt:22)
E/KurobaEx-beta | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
E/KurobaEx-beta | Chan: 	at android.os.Handler.handleCallback(Handler.java:907)
E/KurobaEx-beta | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/KurobaEx-beta | Chan: 	at android.os.Looper.loop(Looper.java:216)
E/KurobaEx-beta | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/KurobaEx-beta | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaEx-beta | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/KurobaEx-beta | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/KurobaEx-beta | UNCAUGHT: Called from unhandled exception handler.
E/KurobaEx-beta | UNCAUGHT: kotlin.UninitializedPropertyAccessException: lateinit property threadLayout has not been initialized
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.ui.controller.ThreadController.setDrawerCallbacks(ThreadController.kt:70)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.ui.controller.BrowseController$showThread$2.invokeSuspend(BrowseController.kt:736)
E/KurobaEx-beta | UNCAUGHT: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:333)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:49)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.ui.controller.BrowseController.showThread(BrowseController.kt:670)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.ui.layout.ThreadLayout.showThread(ThreadLayout.kt:433)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.core.presenter.ThreadPresenter$onPostClicked$1.invokeSuspend(ThreadPresenter.kt:833)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.core.presenter.ThreadPresenter$onPostClicked$1.invoke(Unknown Source:10)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.core.base.SerializedCoroutineExecutor$1.invokeSuspend(SerializedCoroutineExecutor.kt:22)
E/KurobaEx-beta | UNCAUGHT: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:907)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:216)
E/KurobaEx-beta | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/KurobaEx-beta | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaEx-beta | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/KurobaEx-beta | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/KurobaEx-beta | UNCAUGHT: ------------------------------
E/KurobaEx-beta | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/KurobaEx-beta | UNCAUGHT: ------------------------------
E/KurobaEx-beta | UNCAUGHT: Android API Level: 28
E/KurobaEx-beta | UNCAUGHT: App Version: v0.2.4.2105
D/KurobaEx-beta | AndroidUtils: Build Signature: DC5195CC40E42B95267D500B6E93E46EC51028C67BDD3D09BBB9C208BF20C8FE
E/KurobaEx-beta | UNCAUGHT: Development Build: Debug
E/KurobaEx-beta | UNCAUGHT: Phone Model: HUAWEI CMR-W09


=== SETTINGS ===
Prefetching enabled: false
Hi-res thumbnails enabled: true
Youtube titles and durations parsing enabled: true
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: "/storage/emulated/0/KurobaEx-beta/files", SAF location: "", active: Java API
Phone layout mode: PHONE
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
```

**Comment by K1rakishou** [comment]
This one is already fixed in the branch with the new theme engine
