### ISSUE TITLE
Crash report "java.util.ConcurrentModificationException at com.github.k1rakishou.chan.ui.cell.ThreadStatusCell.update(ThreadStatusCell.java:62)"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#217]
Crash report
UUID: 5fcbeb9d845264716199ee7da1c34f2c
Build flavor: stable
Version name: v0.2.10
OS info: Android 5.0.2, sdk version: 21
Report description: No title
Logs:
```
=== LOGS(2020-10-16 04:10:21 UTC) ===
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | Chan: Unhandled exception
E/KurobaEx | Chan: java.util.ConcurrentModificationException
E/KurobaEx | Chan: 	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
E/KurobaEx | Chan: 	at com.github.k1rakishou.chan.ui.cell.ThreadStatusCell.update(ThreadStatusCell.java:62)
E/KurobaEx | Chan: 	at com.github.k1rakishou.chan.ui.cell.-$$Lambda$ThreadStatusCell$LTxUV9meYHZYlQoO7uMNPj549Lo.handleMessage(lambda:3)
E/KurobaEx | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/KurobaEx | Chan: 	at android.os.Looper.loop(Looper.java:145)
E/KurobaEx | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:6141)
E/KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Method.java:372)
E/KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
E/KurobaEx | Chan: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:95)
E/KurobaEx | UNCAUGHT: Called from unhandled exception handler.
E/KurobaEx | UNCAUGHT: java.util.ConcurrentModificationException
E/KurobaEx | UNCAUGHT: 	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
E/KurobaEx | UNCAUGHT: 	at com.github.k1rakishou.chan.ui.cell.ThreadStatusCell.update(ThreadStatusCell.java:62)
E/KurobaEx | UNCAUGHT: 	at com.github.k1rakishou.chan.ui.cell.-$$Lambda$ThreadStatusCell$LTxUV9meYHZYlQoO7uMNPj549Lo.handleMessage(lambda:3)
E/KurobaEx | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/KurobaEx | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:145)
E/KurobaEx | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6141)
E/KurobaEx | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaEx | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Method.java:372)
E/KurobaEx | UNCAUGHT: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/KurobaEx | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
E/KurobaEx | UNCAUGHT: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:95)
E/KurobaEx | UNCAUGHT: ------------------------------
E/KurobaEx | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/KurobaEx | UNCAUGHT: ------------------------------
E/KurobaEx | UNCAUGHT: Android API Level: 21
E/KurobaEx | UNCAUGHT: App Version: v0.2.10.3058
E/KurobaEx | UNCAUGHT: Development Build: Release
E/KurobaEx | UNCAUGHT: Phone Model: samsung SM-A310F


=== STACKTRACE ===
Called from unhandled exception handler.
java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
	at com.github.k1rakishou.chan.ui.cell.ThreadStatusCell.update(ThreadStatusCell.java:62)
	at com.github.k1rakishou.chan.ui.cell.-$$Lambda$ThreadStatusCell$LTxUV9meYHZYlQoO7uMNPj549Lo.handleMessage(lambda:3)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6141)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:95)


=== SETTINGS ===
Prefetching enabled: false
Hi-res thumbnails enabled: false
Youtube titles and durations parsing enabled: true
Concurrent file loading chunks count: 1
WEBM streaming enabled: true
Saved files base dir info: Java API location: "/storage/emulated/0/Download/4chan", SAF location: "", active: Java API
Phone layout mode: PHONE
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: false
```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/a8d0e6645dffc2421d9d28c774011f76eda9c261
