### ISSUE TITLE
Crash report "java.lang.IllegalArgumentException: Stack is empty"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#247]
Crash report
UUID: d5b45912825c40f5aec43e43aa779290
Build flavor: beta
Version name: v0.3.1
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
=== LOGS(2020-11-14 12:52:17 UTC) ===
D/KurobaEx-beta | AndroidUtils: Build Signature: DC5195CC40E42B95267D500B6E93E46EC51028C67BDD3D09BBB9C208BF20C8FE
D/KurobaEx-beta | Chan: maxPostsCountInPostsCache = 16384
D/KurobaEx-beta | Chan: maxAmountOfPostsInDatabase = 125000
D/KurobaEx-beta | Chan: maxAmountOfThreadsInDatabase = 12500
D/KurobaEx-beta | Chan: userAgent = Mozilla/5.0 (Linux; Android 10; HD1910) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.127 Mobile Safari/537.36
D/KurobaEx-beta | Dependency Injection: Using DnsSelector.Mode.IPV4_ONLY
D/KurobaEx-beta | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/KurobaEx-beta | Dependency Injection: App Context
D/KurobaEx-beta | Dependency Injection: App CoroutineScope
D/KurobaEx-beta | Dependency Injection: ApplicationVisibilityManager
D/KurobaEx-beta | Dependency Injection: Gson module
D/KurobaEx-beta | Dependency Injection: Archives manager
D/KurobaEx-beta | Dependency Injection: BookmarksManager
D/KurobaEx-beta | Dependency Injection: Site manager
D/KurobaEx-beta | Dependency Injection: LastViewedPostNoInfoHolder
D/KurobaEx-beta | Dependency Injection: Site resolver
D/KurobaEx-beta | Dependency Injection: ProxyStorage
D/KurobaEx-beta | Dependency Injection: RealProxiedOkHttpClient
D/KurobaEx-beta | Dependency Injection: FetchThreadBookmarkInfoUseCase
D/KurobaEx-beta | Dependency Injection: Mock reply manager
D/KurobaEx-beta | Dependency Injection: ParserRepository
D/KurobaEx-beta | Dependency Injection: ReplyParser
D/KurobaEx-beta | Dependency Injection: SavedReplyManager
D/KurobaEx-beta | Dependency Injection: ParsePostRepliesUseCase
D/KurobaEx-beta | Dependency Injection: CoilOkHttpClient
D/KurobaEx-beta | Dependency Injection: Coil Image loader
D/KurobaEx-beta | Dependency Injection: ThemeParser
D/KurobaEx-beta | Dependency Injection: ThemeEngine
D/KurobaEx-beta | Dependency Injection: Image loader v2
D/KurobaEx-beta | Dependency Injection: ReplyNotificationsHelper
D/KurobaEx-beta | Dependency Injection: Board manager
D/KurobaEx-beta | Dependency Injection: Page request manager
D/KurobaEx-beta | Dependency Injection: LastPageNotificationsHelper
D/KurobaEx-beta | Dependency Injection: BookmarkWatcherDelegate
D/KurobaEx-beta | Dependency Injection: BookmarkForegroundWatcher
D/KurobaEx-beta | Dependency Injection: BookmarkWatcherController
D/KurobaEx-beta | Dependency Injection: PostFilterManager
D/KurobaEx-beta | Dependency Injection: ChanFilterManager
D/KurobaEx-beta | Dependency Injection: Report manager
D/KurobaEx-beta | Dependency Injection: Available space for cache dir: 132323606528 bytes, cacheDirPath = /storage/emulated/0/Android/data/com.github.k1rakishou.chan.beta/cache
D/KurobaEx-beta | Dependency Injection: HistoryNavigationManager
D/KurobaEx-beta | Dependency Injection: ThreadBookmarkGroupEntryManager
D/KurobaEx-beta | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.beta/files/kurobaex_theme_dark.json) does not exist on the disk
D/KurobaEx-beta | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.beta/files/kurobaex_theme_light.json) does not exist on the disk
D/KurobaEx-beta | SiteManager: SiteManager.initialize()
D/KurobaEx-beta | BoardManager: BoardManager.initialize()
D/KurobaEx-beta | SiteManager: loadSites() start
D/KurobaEx-beta | BookmarksManager: BookmarksManager.initialize()
D/KurobaEx-beta | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/KurobaEx-beta | BoardManager: loadBoards() start
D/KurobaEx-beta | BookmarkWatcherController: BookmarkWatcherCoordinator.initialize()
D/KurobaEx-beta | ArchivesManager: ArchivesManager.initialize()
D/KurobaEx-beta | ChanFilterManager: ChanFilterManager.initialize()
D/KurobaEx-beta | Chan: Application initialization took 91ms
D/KurobaEx-beta | StartActivity: onCreate() start savedInstanceState==null: true
D/KurobaEx-beta | Dependency Injection: DialogFactory
D/KurobaEx-beta | Dependency Injection: ChanThreadViewableInfoManager
D/KurobaEx-beta | Dependency Injection: ControllerNavigationManager
D/KurobaEx-beta | Dependency Injection: ReplyViewStateManager
D/KurobaEx-beta | Dependency Injection: GlobalWindowInsetsManager
D/KurobaEx-beta | StartActivity: inject took 3.46ms
D/KurobaEx-beta | Dependency Injection: Connectivity Manager
D/KurobaEx-beta | Dependency Injection: Cache handler
D/KurobaEx-beta | Dependency Injection: Available space for cache dir: 132323635200 bytes, cacheDirPath = /storage/emulated/0/Android/data/com.github.k1rakishou.chan.beta/cache
D/KurobaEx-beta | Dependency Injection: DownloaderOkHttp client
D/KurobaEx-beta | Dependency Injection: File cache V2
D/KurobaEx-beta | FileCacheV2: [main]: chunksCount = 2
D/KurobaEx-beta | Dependency Injection: Reply manager
D/KurobaEx-beta | Dependency Injection: Http call manager
D/KurobaEx-beta | SiteManager: loadSites() took 146ms
D/KurobaEx-beta | Dependency Injection: Android10GesturesExclusionZonesHolder
D/KurobaEx-beta | Android10GesturesExclusionZonesHolder: Json setting string is empty, reset.
D/KurobaEx-beta | Dependency Injection: LocalSearchManager
D/KurobaEx-beta | Dependency Injection: PostHideManager
D/KurobaEx-beta | Dependency Injection: Chan loader factory
D/KurobaEx-beta | Dependency Injection: PrefetchIndicatorAnimationManager
D/KurobaEx-beta | Dependency Injection: OnDemandContentLoaderExecutor
D/KurobaEx-beta | Dependency Injection: PrefetchLoader
D/KurobaEx-beta | ThreadBookmarkGroupEntryManager: ThreadBookmarkGroupEntryManager initialized! Loaded 1 total bookmark groups
D/KurobaEx-beta | ChanFilterManager: loadFilters() took 270ms
D/KurobaEx-beta | Dependency Injection: YoutubeMediaServiceExtraInfoFetcher
D/KurobaEx-beta | Dependency Injection: SoundCloudMediaServiceExtraInfoFetcher
D/KurobaEx-beta | Dependency Injection: StreamableMediaServiceExtraInfoFetcher
D/KurobaEx-beta | Dependency Injection: PostExtraContentLoader
D/KurobaEx-beta | Dependency Injection: InlinedFileInfoLoader
D/KurobaEx-beta | Dependency Injection: Chan4CloudFlareImagePreloaderManager
D/KurobaEx-beta | Dependency Injection: Chan4CloudFlareImagePreloader
D/KurobaEx-beta | Dependency Injection: OnDemandContentLoaderManager
D/KurobaEx-beta | OnDemandContentLoaderManager: Loaders count = 4
D/KurobaEx-beta | Dependency Injection: SeenPostsManager
D/KurobaEx-beta | Dependency Injection: Captcha holder
D/KurobaEx-beta | Dependency Injection: Last reply repository
D/KurobaEx-beta | Dependency Injection: ExtractPostMapInfoHolderUseCase
D/KurobaEx-beta | StartActivity: createUi took 503ms
D/KurobaEx-beta | StartActivity: initializeDependencies took 8.92ms
D/KurobaEx-beta | BoardManager: BoardManager is not ready yet, waiting...
D/KurobaEx-beta | StartActivity: onCreate() end savedInstanceState==null: true
D/KurobaEx-beta | Chan: ^^^ App went foreground ^^^
D/KurobaEx-beta | ApplicationVisibilityManager: onEnteredForeground() callback execution took 47.1us, callbacks count: 1
D/KurobaEx-beta | StartActivity: start
D/KurobaEx-beta | BookmarksManager: BookmarksManager is not ready yet, waiting...
D/KurobaEx-beta | BoardManager: BoardManager is not ready yet, waiting...
E/KurobaEx-beta | Chan: Unhandled exception
E/KurobaEx-beta | Chan: java.lang.IllegalArgumentException: Stack is empty
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.features.settings.SettingsCoordinator.rebuildCurrentScreen(SettingsCoordinator.kt:341)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.features.settings.SettingsCoordinator$onCreate$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:133)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.reactive.PublisherAsFlow.collectImpl(ReactiveFlow.kt:96)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.reactive.PublisherAsFlow$collectImpl$1.invokeSuspend(Unknown Source:12)
E/KurobaEx-beta | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
E/KurobaEx-beta | Chan: 	at android.os.Handler.handleCallback(Handler.java:883)
E/KurobaEx-beta | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/KurobaEx-beta | Chan: 	at android.os.Looper.loop(Looper.java:214)
E/KurobaEx-beta | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:7710)
E/KurobaEx-beta | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaEx-beta | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/KurobaEx-beta | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/KurobaEx-beta | UNCAUGHT: Called from unhandled exception handler.
E/KurobaEx-beta | UNCAUGHT: java.lang.IllegalArgumentException: Stack is empty
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.features.settings.SettingsCoordinator.rebuildCurrentScreen(SettingsCoordinator.kt:341)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.features.settings.SettingsCoordinator$onCreate$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:133)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.reactive.PublisherAsFlow.collectImpl(ReactiveFlow.kt:96)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.reactive.PublisherAsFlow$collectImpl$1.invokeSuspend(Unknown Source:12)
E/KurobaEx-beta | UNCAUGHT: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:883)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:214)
E/KurobaEx-beta | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7710)
E/KurobaEx-beta | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaEx-beta | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/KurobaEx-beta | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/KurobaEx-beta | UNCAUGHT: ------------------------------
E/KurobaEx-beta | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/KurobaEx-beta | UNCAUGHT: ------------------------------
E/KurobaEx-beta | UNCAUGHT: Android API Level: 29
E/KurobaEx-beta | UNCAUGHT: App Version: v0.3.1.4138
D/KurobaEx-beta | AndroidUtils: Build Signature: DC5195CC40E42B95267D500B6E93E46EC51028C67BDD3D09BBB9C208BF20C8FE
E/KurobaEx-beta | UNCAUGHT: Development Build: Debug
E/KurobaEx-beta | UNCAUGHT: Phone Model: OnePlus HD1910
D/KurobaEx-beta | ReportManager: Stored new crash log, path = /storage/emulated/0/Android/data/com.github.k1rakishou.chan.beta/cache/crashlogs/crashlog_1605358335015.txt
D/KurobaEx-beta | AndroidUtils: Build Signature: DC5195CC40E42B95267D500B6E93E46EC51028C67BDD3D09BBB9C208BF20C8FE
D/KurobaEx-beta | Chan: maxPostsCountInPostsCache = 16384
D/KurobaEx-beta | Chan: maxAmountOfPostsInDatabase = 125000
D/KurobaEx-beta | Chan: maxAmountOfThreadsInDatabase = 12500
D/KurobaEx-beta | Chan: userAgent = Mozilla/5.0 (Linux; Android 10; HD1910) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.127 Mobile Safari/537.36
D/KurobaEx-beta | Dependency Injection: Using DnsSelector.Mode.IPV4_ONLY
D/KurobaEx-beta | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/KurobaEx-beta | Dependency Injection: App Context
D/KurobaEx-beta | Dependency Injection: App CoroutineScope
D/KurobaEx-beta | Dependency Injection: ApplicationVisibilityManager
D/KurobaEx-beta | Dependency Injection: Gson module
D/KurobaEx-beta | Dependency Injection: Archives manager
D/KurobaEx-beta | Dependency Injection: BookmarksManager
D/KurobaEx-beta | Dependency Injection: Site manager
D/KurobaEx-beta | Dependency Injection: LastViewedPostNoInfoHolder
D/KurobaEx-beta | Dependency Injection: Site resolver
D/KurobaEx-beta | Dependency Injection: ProxyStorage
D/KurobaEx-beta | Dependency Injection: RealProxiedOkHttpClient
D/KurobaEx-beta | Dependency Injection: FetchThreadBookmarkInfoUseCase
D/KurobaEx-beta | Dependency Injection: Mock reply manager
D/KurobaEx-beta | Dependency Injection: ParserRepository
D/KurobaEx-beta | Dependency Injection: ReplyParser
D/KurobaEx-beta | Dependency Injection: SavedReplyManager
D/KurobaEx-beta | Dependency Injection: ParsePostRepliesUseCase
D/KurobaEx-beta | Dependency Injection: CoilOkHttpClient
D/KurobaEx-beta | Dependency Injection: Coil Image loader
D/KurobaEx-beta | Dependency Injection: ThemeParser
D/KurobaEx-beta | Dependency Injection: ThemeEngine
D/KurobaEx-beta | Dependency Injection: Image loader v2
D/KurobaEx-beta | Dependency Injection: ReplyNotificationsHelper
D/KurobaEx-beta | Dependency Injection: Board manager
D/KurobaEx-beta | Dependency Injection: Page request manager
D/KurobaEx-beta | Dependency Injection: LastPageNotificationsHelper
D/KurobaEx-beta | Dependency Injection: BookmarkWatcherDelegate
D/KurobaEx-beta | Dependency Injection: BookmarkForegroundWatcher
D/KurobaEx-beta | Dependency Injection: BookmarkWatcherController
D/KurobaEx-beta | Dependency Injection: PostFilterManager
D/KurobaEx-beta | Dependency Injection: ChanFilterManager
D/KurobaEx-beta | Dependency Injection: Report manager
D/KurobaEx-beta | Dependency Injection: Available space for cache dir: 132319227904 bytes, cacheDirPath = /storage/emulated/0/Android/data/com.github.k1rakishou.chan.beta/cache
D/KurobaEx-beta | Dependency Injection: HistoryNavigationManager
D/KurobaEx-beta | Dependency Injection: ThreadBookmarkGroupEntryManager
D/KurobaEx-beta | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.beta/files/kurobaex_theme_dark.json) does not exist on the disk
D/KurobaEx-beta | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.beta/files/kurobaex_theme_light.json) does not exist on the disk
D/KurobaEx-beta | SiteManager: SiteManager.initialize()
D/KurobaEx-beta | BoardManager: BoardManager.initialize()
D/KurobaEx-beta | BookmarksManager: BookmarksManager.initialize()
D/KurobaEx-beta | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/KurobaEx-beta | SiteManager: loadSites() start
D/KurobaEx-beta | BoardManager: loadBoards() start
D/KurobaEx-beta | BookmarkWatcherController: BookmarkWatcherCoordinator.initialize()
D/KurobaEx-beta | ArchivesManager: ArchivesManager.initialize()
D/KurobaEx-beta | ChanFilterManager: ChanFilterManager.initialize()
D/KurobaEx-beta | SettingsNotificationManager: Added CrashLog notification
D/KurobaEx-beta | Chan: Application initialization took 97ms
D/KurobaEx-beta | Dependency Injection: Http call manager
D/KurobaEx-beta | StartActivity: onCreate() start savedInstanceState==null: true
D/KurobaEx-beta | Dependency Injection: DialogFactory
D/KurobaEx-beta | Dependency Injection: ChanThreadViewableInfoManager
D/KurobaEx-beta | Dependency Injection: ControllerNavigationManager
D/KurobaEx-beta | Dependency Injection: ReplyViewStateManager
D/KurobaEx-beta | Dependency Injection: GlobalWindowInsetsManager
D/KurobaEx-beta | StartActivity: inject took 3.65ms
D/KurobaEx-beta | Dependency Injection: Connectivity Manager
D/KurobaEx-beta | Dependency Injection: Cache handler
D/KurobaEx-beta | Dependency Injection: Available space for cache dir: 132324159488 bytes, cacheDirPath = /storage/emulated/0/Android/data/com.github.k1rakishou.chan.beta/cache
D/KurobaEx-beta | Dependency Injection: DownloaderOkHttp client
D/KurobaEx-beta | Dependency Injection: File cache V2
D/KurobaEx-beta | FileCacheV2: [main]: chunksCount = 2
D/KurobaEx-beta | Dependency Injection: Reply manager
D/KurobaEx-beta | ChanFilterManager: loadFilters() took 90.5ms
D/KurobaEx-beta | SiteManager: loadSites() took 111ms
D/KurobaEx-beta | Dependency Injection: Android10GesturesExclusionZonesHolder
D/KurobaEx-beta | Android10GesturesExclusionZonesHolder: Json setting string is empty, reset.
D/KurobaEx-beta | Dependency Injection: LocalSearchManager
D/KurobaEx-beta | Dependency Injection: PostHideManager
D/KurobaEx-beta | Dependency Injection: Chan loader factory
D/KurobaEx-beta | Dependency Injection: PrefetchIndicatorAnimationManager
D/KurobaEx-beta | Dependency Injection: OnDemandContentLoaderExecutor
D/KurobaEx-beta | Dependency Injection: PrefetchLoader
D/KurobaEx-beta | Dependency Injection: YoutubeMediaServiceExtraInfoFetcher
D/KurobaEx-beta | Dependency Injection: SoundCloudMediaServiceExtraInfoFetcher
D/KurobaEx-beta | Dependency Injection: StreamableMediaServiceExtraInfoFetcher
D/KurobaEx-beta | Dependency Injection: PostExtraContentLoader
D/KurobaEx-beta | Dependency Injection: InlinedFileInfoLoader
D/KurobaEx-beta | Dependency Injection: Chan4CloudFlareImagePreloaderManager
D/KurobaEx-beta | Dependency Injection: Chan4CloudFlareImagePreloader
D/KurobaEx-beta | Dependency Injection: OnDemandContentLoaderManager
D/KurobaEx-beta | OnDemandContentLoaderManager: Loaders count = 4
D/KurobaEx-beta | Dependency Injection: SeenPostsManager
D/KurobaEx-beta | Dependency Injection: Captcha holder
D/KurobaEx-beta | Dependency Injection: Last reply repository
D/KurobaEx-beta | Dependency Injection: ExtractPostMapInfoHolderUseCase
D/KurobaEx-beta | StartActivity: createUi took 491ms
D/KurobaEx-beta | BoardManager: BoardManager is not ready yet, waiting...
D/KurobaEx-beta | StartActivity: initializeDependencies took 5.10ms
D/KurobaEx-beta | StartActivity: onCreate() end savedInstanceState==null: true
D/KurobaEx-beta | Chan: ^^^ App went foreground ^^^
D/KurobaEx-beta | ApplicationVisibilityManager: onEnteredForeground() callback execution took 52.8us, callbacks count: 1
D/KurobaEx-beta | StartActivity: start
D/KurobaEx-beta | BookmarksManager: BookmarksManager is not ready yet, waiting...
D/KurobaEx-beta | BoardManager: BoardManager is not ready yet, waiting...
E/KurobaEx-beta | Chan: Unhandled exception
E/KurobaEx-beta | Chan: java.lang.IllegalArgumentException: Stack is empty
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.features.settings.SettingsCoordinator.rebuildCurrentScreen(SettingsCoordinator.kt:341)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.features.settings.SettingsCoordinator$onCreate$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:133)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.reactive.PublisherAsFlow.collectImpl(ReactiveFlow.kt:96)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.reactive.PublisherAsFlow$collectImpl$1.invokeSuspend(Unknown Source:12)
E/KurobaEx-beta | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
E/KurobaEx-beta | Chan: 	at android.os.Handler.handleCallback(Handler.java:883)
E/KurobaEx-beta | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/KurobaEx-beta | Chan: 	at android.os.Looper.loop(Looper.java:214)
E/KurobaEx-beta | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:7710)
E/KurobaEx-beta | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaEx-beta | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/KurobaEx-beta | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/KurobaEx-beta | UNCAUGHT: Called from unhandled exception handler.
E/KurobaEx-beta | UNCAUGHT: java.lang.IllegalArgumentException: Stack is empty
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.features.settings.SettingsCoordinator.rebuildCurrentScreen(SettingsCoordinator.kt:341)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.features.settings.SettingsCoordinator$onCreate$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:133)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.reactive.PublisherAsFlow.collectImpl(ReactiveFlow.kt:96)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.reactive.PublisherAsFlow$collectImpl$1.invokeSuspend(Unknown Source:12)
E/KurobaEx-beta | UNCAUGHT: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:883)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:214)
E/KurobaEx-beta | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7710)
E/KurobaEx-beta | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaEx-beta | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/KurobaEx-beta | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/KurobaEx-beta | UNCAUGHT: ------------------------------
E/KurobaEx-beta | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/KurobaEx-beta | UNCAUGHT: ------------------------------
E/KurobaEx-beta | UNCAUGHT: Android API Level: 29
E/KurobaEx-beta | UNCAUGHT: App Version: v0.3.1.4138
D/KurobaEx-beta | AndroidUtils: Build Signature: DC5195CC40E42B95267D500B6E93E46EC51028C67BDD3D09BBB9C208BF20C8FE
E/KurobaEx-beta | UNCAUGHT: Development Build: Debug
E/KurobaEx-beta | UNCAUGHT: Phone Model: OnePlus HD1910


=== SETTINGS ===
Prefetching enabled: false
Hi-res thumbnails enabled: false
Youtube titles and durations parsing enabled: WIFI
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: "/storage/emulated/0/KurobaEx-beta/files", SAF location: "", active: Java API
Phone layout mode: PHONE
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/e7862ea9492ac2cbfa553276ffa7527ab707f116
