### ISSUE TITLE
Report "This thread on Lainchan doesn't open"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#255]
UUID: 65a40626cef99caf20ed0a5d1c355969
Build flavor: stable
Version name: v0.3.2
OS info: Android 10, sdk version: 29
Report description: https://lainchan.org/%CE%94/res/3039.html
Logs:
```
E/KurobaEx | BookmarkWatcherDelegate: fetchThreadBookmarkInfoUseCase.execute() error: Job was cancelled
E/KurobaEx | ChanThreadLoader: onChanLoaderError()
E/KurobaEx | ChanThreadLoader: com.github.k1rakishou.chan.core.site.loader.ChanLoaderException: java.lang.IllegalStateException: Bad serverFilename, null or empty
E/KurobaEx | ChanThreadLoader: 	at com.github.k1rakishou.chan.core.site.loader.ChanThreadLoaderCoordinator$loadThread$1.invokeSuspend(ChanThreadLoaderCoordinator.kt:46)
E/KurobaEx | ChanThreadLoader: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/KurobaEx | ChanThreadLoader: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
E/KurobaEx | ChanThreadLoader: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
E/KurobaEx | ChanThreadLoader: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
E/KurobaEx | ChanThreadLoader: Caused by: java.lang.IllegalStateException: Bad serverFilename, null or empty
E/KurobaEx | ChanThreadLoader: 	at com.github.k1rakishou.chan.core.model.PostImage$Builder.build(PostImage.java:7)
E/KurobaEx | ChanThreadLoader: 	at com.github.k1rakishou.chan.core.site.common.vichan.VichanApi.readPostImage(VichanApi.kt:35)
E/KurobaEx | ChanThreadLoader: 	at com.github.k1rakishou.chan.core.site.common.vichan.VichanApi.readPostObject(VichanApi.kt:24)
E/KurobaEx | ChanThreadLoader: 	at com.github.k1rakishou.chan.core.site.common.vichan.VichanApi$loadThread$2.invokeSuspend(VichanApi.kt:5)
E/KurobaEx | ChanThreadLoader: 	at com.github.k1rakishou.chan.core.site.common.vichan.VichanApi$loadThread$2.invoke(VichanApi.kt:2)
E/KurobaEx | ChanThreadLoader: 	at com.github.k1rakishou.chan.core.site.common.vichan.VichanReaderExtensions.iteratePostsInThread(VichanReaderExtensions.kt:11)
E/KurobaEx | ChanThreadLoader: 	at com.github.k1rakishou.chan.core.site.common.vichan.VichanApi.loadThread(VichanApi.kt:2)
E/KurobaEx | ChanThreadLoader: 	at com.github.k1rakishou.chan.core.site.loader.ChanThreadLoaderCoordinator.readPostsFromResponse(ChanThreadLoaderCoordinator.kt:16)
E/KurobaEx | ChanThreadLoader: 	at com.github.k1rakishou.chan.core.site.loader.ChanThreadLoaderCoordinator$loadThread$1.invokeSuspend(ChanThreadLoaderCoordinator.kt:30)
E/KurobaEx | ChanThreadLoader: 	... 4 more
```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/80acb3cc649dc20623c6eb516bb9f6a5e9f96a26
