### ISSUE TITLE
Crash report "java.lang.IllegalAccessException: Bug in BoardDescriptorsComparator"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#256]
Crash report
UUID: 3c2fab6656c063f102c72176ae9eb163
Build flavor: stable
Version name: v0.3.2
OS info: Android 9, sdk version: 28
Report description: No title
Logs:
```
=== LOGS(2020-11-30 05:56:35 UTC) ===
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setEditTextCursorColor() failure, error=No field mDrawableForCursor in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setEditTextCursorColor() failure, error=No field mDrawableForCursor in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
E/KurobaEx | ViewUtils: setEditTextCursorColor() failure, error=No field mDrawableForCursor in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
E/KurobaEx | ViewUtils: setEditTextCursorColor() failure, error=No field mDrawableForCursor in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
E/KurobaEx | ViewUtils: setEditTextCursorColor() failure, error=No field mDrawableForCursor in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
E/KurobaEx | ViewUtils: setEditTextCursorColor() failure, error=No field mDrawableForCursor in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
E/KurobaEx | ViewUtils: setEditTextCursorColor() failure, error=No field mDrawableForCursor in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setEditTextCursorColor() failure, error=No field mDrawableForCursor in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setEditTextCursorColor() failure, error=No field mDrawableForCursor in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setEditTextCursorColor() failure, error=No field mDrawableForCursor in class Landroid/widget/Editor; (declaration of 'android.widget.Editor' appears in /system/framework/framework.jar!classes2.dex)
E/KurobaEx | Chan: Unhandled exception
E/KurobaEx | Chan: java.lang.IllegalAccessException: Bug in BoardDescriptorsComparator, query=n, descriptors=[BD{8kun/interracial}, BD{8kun/warlearn}, BD{8kun/1825kun}, BD{8kun/kemono}, BD{8kun/thedonald}, BD{8kun/tenda}, BD{8kun/kukichan}, BD{8kun/instruments}, BD{8kun/animu}, BD{8kun/satsukichan}, BD{8kun/frenzone}, BD{8kun/hentaiclub}, BD{8kun/brains}, BD{8kun/pundit}, BD{8kun/kingcrimson}, BD{8kun/underground}, BD{8kun/cafechan}, BD{8kun/sonyeon}, BD{8kun/genesis}, BD{8kun/n0thingness}, BD{8kun/ntr}, BD{8kun/monster}, BD{8kun/ebon}, BD{8kun/inflg}, BD{8kun/tripfriend}, BD{8kun/language}, BD{8kun/hentaiporn}, BD{8kun/india}, BD{8kun/rusrandom}, BD{8kun/monarchy}, BD{8kun/demonp}, BD{8kun/kohlchan}, BD{8kun/zundel}, BD{8kun/newsplus}, BD{8kun/rzabczan}, BD{8kun/liveanarchy}, BD{8kun/reimuchan}, BD{8kun/earthlibfront}, BD{8kun/newhomosuck}, BD{8kun/cicachan}, BD{8kun/indochinaexpats}, BD{8kun/danpu}, BD{8kun/nep}, BD{8kun/nanachi}, BD{8kun/fashionplus}, BD{8kun/qresearch2gen}, BD{8kun/tulpamancers}, BD{8kun/vivian}, BD{8kun/jumpchen}, BD{8kun/jobventing}, BD{8kun/55sync}, BD{8kun/mental}, BD{8kun/amichan}, BD{8kun/gendercritical}, BD{8kun/aneki}, BD{8kun/8bantb}, BD{8kun/tarhana}, BD{8kun/christian}, BD{8kun/nohup}, BD{8kun/truthlegion}, BD{8kun/clang}, BD{8kun/bpink}, BD{8kun/draftnote}, BD{8kun/anime12345}, BD{8kun/pnd}, BD{8kun/libertedexpression}, BD{8kun/hentai}, BD{8kun/tingles}, BD{8kun/moldnet}, BD{8kun/soapboxbanhammer}, BD{8kun/pokeporn}, BD{8kun/vietnam}, BD{8kun/femaledomination}, BD{8kun/animation}, BD{8kun/nobody}, BD{8kun/panconleche}, BD{8kun/unlightopen}, BD{8kun/greenbreeze}, BD{8kun/newsci}, BD{8kun/sakurachan}, BD{8kun/jozsicsan}, BD{8kun/vietkong}, BD{8kun/vichan}, BD{8kun/random}, BD{8kun/freedomzine}, BD{8kun/qrnews}, BD{8kun/canada}, BD{8kun/christianmeme}, BD{8kun/buddhismhotline}, BD{8kun/lain}, BD{8kun/55chan}, BD{8kun/bmn}, BD{8kun/pen}, BD{8kun/newbrit}, BD{8kun/ogfinance}, BD{8kun/tikilounge}, BD{8kun/hypno}, BD{8kun/fortnite}, BD{8kun/in}, BD{8kun/ausneets}, BD{8kun/whogen}, BD{8kun/fallen}, BD{8kun/sunflower}, BD{8kun/pone}, BD{8kun/bigwomen}, BD{8kun/onepiece}, BD{8kun/techan}, BD{8kun/redlands}, BD{8kun/accent}, BD{8kun/francofil}, BD{8kun/degen}, BD{8kun/tan}, BD{8kun/kind}, BD{8kun/techbunker}, BD{8kun/moonlight}, BD{8kun/indo}, BD{8kun/nofap}, BD{8kun/homeowner}, BD{8kun/fuckuchina}, BD{8kun/warfront666}, BD{8kun/natiofr}, BD{8kun/fringe}, BD{8kun/christianity}, BD{8kun/bunkers}, BD{8kun/argentina}, BD{8kun/an}, BD{8kun/futyitorna}, BD{8kun/hnt}, BD{8kun/zenczan}, BD{8kun/animus}, BD{8kun/nothingness}]
E/KurobaEx | Chan: 	at com.github.k1rakishou.chan.features.setup.AddBoardsPresenter.showBoardsWithSearchQuery(AddBoardsPresenter.kt:16)
E/KurobaEx | Chan: 	at com.github.k1rakishou.chan.features.setup.AddBoardsPresenter.showBoardsWithSearchQuery$default(AddBoardsPresenter.kt:1)
E/KurobaEx | Chan: 	at com.github.k1rakishou.chan.features.setup.AddBoardsController$onCreate$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:7)
E/KurobaEx | Chan: 	at kotlinx.coroutines.flow.FlowKt__DelayKt$debounce$2$invokeSuspend$$inlined$select$lambda$2.invokeSuspend(Delay.kt:8)
E/KurobaEx | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/KurobaEx | Chan: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
E/KurobaEx | Chan: 	at android.os.Handler.handleCallback(Handler.java:873)
E/KurobaEx | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/KurobaEx | Chan: 	at android.os.Looper.loop(Looper.java:235)
E/KurobaEx | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:6760)
E/KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaEx | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
E/KurobaEx | UNCAUGHT: Called from unhandled exception handler.
E/KurobaEx | UNCAUGHT: java.lang.IllegalAccessException: Bug in BoardDescriptorsComparator, query=n, descriptors=[BD{8kun/interracial}, BD{8kun/warlearn}, BD{8kun/1825kun}, BD{8kun/kemono}, BD{8kun/thedonald}, BD{8kun/tenda}, BD{8kun/kukichan}, BD{8kun/instruments}, BD{8kun/animu}, BD{8kun/satsukichan}, BD{8kun/frenzone}, BD{8kun/hentaiclub}, BD{8kun/brains}, BD{8kun/pundit}, BD{8kun/kingcrimson}, BD{8kun/underground}, BD{8kun/cafechan}, BD{8kun/sonyeon}, BD{8kun/genesis}, BD{8kun/n0thingness}, BD{8kun/ntr}, BD{8kun/monster}, BD{8kun/ebon}, BD{8kun/inflg}, BD{8kun/tripfriend}, BD{8kun/language}, BD{8kun/hentaiporn}, BD{8kun/india}, BD{8kun/rusrandom}, BD{8kun/monarchy}, BD{8kun/demonp}, BD{8kun/kohlchan}, BD{8kun/zundel}, BD{8kun/newsplus}, BD{8kun/rzabczan}, BD{8kun/liveanarchy}, BD{8kun/reimuchan}, BD{8kun/earthlibfront}, BD{8kun/newhomosuck}, BD{8kun/cicachan}, BD{8kun/indochinaexpats}, BD{8kun/danpu}, BD{8kun/nep}, BD{8kun/nanachi}, BD{8kun/fashionplus}, BD{8kun/qresearch2gen}, BD{8kun/tulpamancers}, BD{8kun/vivian}, BD{8kun/jumpchen}, BD{8kun/jobventing}, BD{8kun/55sync}, BD{8kun/mental}, BD{8kun/amichan}, BD{8kun/gendercritical}, BD{8kun/aneki}, BD{8kun/8bantb}, BD{8kun/tarhana}, BD{8kun/christian}, BD{8kun/nohup}, BD{8kun/truthlegion}, BD{8kun/clang}, BD{8kun/bpink}, BD{8kun/draftnote}, BD{8kun/anime12345}, BD{8kun/pnd}, BD{8kun/libertedexpression}, BD{8kun/hentai}, BD{8kun/tingles}, BD{8kun/moldnet}, BD{8kun/soapboxbanhammer}, BD{8kun/pokeporn}, BD{8kun/vietnam}, BD{8kun/femaledomination}, BD{8kun/animation}, BD{8kun/nobody}, BD{8kun/panconleche}, BD{8kun/unlightopen}, BD{8kun/greenbreeze}, BD{8kun/newsci}, BD{8kun/sakurachan}, BD{8kun/jozsicsan}, BD{8kun/vietkong}, BD{8kun/vichan}, BD{8kun/random}, BD{8kun/freedomzine}, BD{8kun/qrnews}, BD{8kun/canada}, BD{8kun/christianmeme}, BD{8kun/buddhismhotline}, BD{8kun/lain}, BD{8kun/55chan}, BD{8kun/bmn}, BD{8kun/pen}, BD{8kun/newbrit}, BD{8kun/ogfinance}, BD{8kun/tikilounge}, BD{8kun/hypno}, BD{8kun/fortnite}, BD{8kun/in}, BD{8kun/ausneets}, BD{8kun/whogen}, BD{8kun/fallen}, BD{8kun/sunflower}, BD{8kun/pone}, BD{8kun/bigwomen}, BD{8kun/onepiece}, BD{8kun/techan}, BD{8kun/redlands}, BD{8kun/accent}, BD{8kun/francofil}, BD{8kun/degen}, BD{8kun/tan}, BD{8kun/kind}, BD{8kun/techbunker}, BD{8kun/moonlight}, BD{8kun/indo}, BD{8kun/nofap}, BD{8kun/homeowner}, BD{8kun/fuckuchina}, BD{8kun/warfront666}, BD{8kun/natiofr}, BD{8kun/fringe}, BD{8kun/christianity}, BD{8kun/bunkers}, BD{8kun/argentina}, BD{8kun/an}, BD{8kun/futyitorna}, BD{8kun/hnt}, BD{8kun/zenczan}, BD{8kun/animus}, BD{8kun/nothingness}]
E/KurobaEx | UNCAUGHT: 	at com.github.k1rakishou.chan.features.setup.AddBoardsPresenter.showBoardsWithSearchQuery(AddBoardsPresenter.kt:16)
E/KurobaEx | UNCAUGHT: 	at com.github.k1rakishou.chan.features.setup.AddBoardsPresenter.showBoardsWithSearchQuery$default(AddBoardsPresenter.kt:1)
E/KurobaEx | UNCAUGHT: 	at com.github.k1rakishou.chan.features.setup.AddBoardsController$onCreate$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:7)
E/KurobaEx | UNCAUGHT: 	at kotlinx.coroutines.flow.FlowKt__DelayKt$debounce$2$invokeSuspend$$inlined$select$lambda$2.invokeSuspend(Delay.kt:8)
E/KurobaEx | UNCAUGHT: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/KurobaEx | UNCAUGHT: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
E/KurobaEx | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:873)
E/KurobaEx | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/KurobaEx | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:235)
E/KurobaEx | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6760)
E/KurobaEx | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaEx | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/KurobaEx | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
E/KurobaEx | UNCAUGHT: ------------------------------
E/KurobaEx | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/KurobaEx | UNCAUGHT: ------------------------------
E/KurobaEx | UNCAUGHT: Android API Level: 28
E/KurobaEx | UNCAUGHT: App Version: v0.3.2.4143
E/KurobaEx | UNCAUGHT: Development Build: Release
E/KurobaEx | UNCAUGHT: Phone Model: motorola moto e(6) plus


=== SETTINGS ===
Prefetching enabled: false
Hi-res thumbnails enabled: false
Youtube titles and durations parsing enabled: WIFI
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: "/storage/emulated/0/KurobaEx/files", SAF location: "", active: Java API
Phone layout mode: SLIDE
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/b7abc9e8976e4db8e4cf08960964d49c2f316aec
