### ISSUE TITLE
Crash report "First post is not an original post! post=ChanPost{chanPostId=0, postDescriptor=PD(Lainchan/Î©/36474/36456,0), postImages=1, subject='Used/refurbished HP Z600 workstation', postComment=They have two Xeon sockets (12MB cache) and can accept soykafloa}"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#264]
Crash report
UUID: bc695d0e27477022229c4abfabd41cb9
Build flavor: beta
Version name: v0.4.2
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
=== LOGS(2021-01-09 08:07:17 UTC) ===
E/KurobaEx-beta | Chan: Unhandled exception
E/KurobaEx-beta | Chan: java.lang.IllegalArgumentException: First post is not an original post! post=ChanPost{chanPostId=0, postDescriptor=PD(Lainchan/Î©/36474/36456,0), postImages=1, subject='Used/refurbished HP Z600 workstation', postComment=They have two Xeon sockets (12MB cache) and can accept soykafloa}
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.model.data.thread.ChanThread.getOriginalPost(ChanThread.kt:175)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.model.data.thread.ChanThread.isClosed(ChanThread.kt:53)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.presenter.ThreadPresenter.isWatching(ThreadPresenter.kt:1553)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.presenter.ThreadPresenter.onChanLoaderData(ThreadPresenter.kt:695)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.presenter.ThreadPresenter$normalLoad$1$1.invokeSuspend(ThreadPresenter.kt:427)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.presenter.ThreadPresenter$normalLoad$1$1.invoke(Unknown Source:10)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.manager.ChanThreadManager.loadThreadOrCatalog(ChanThreadManager.kt:104)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.manager.ChanThreadManager$loadThreadOrCatalog$1.invokeSuspend(Unknown Source:18)
E/KurobaEx-beta | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/KurobaEx-beta | Chan: 	at android.os.Handler.handleCallback(Handler.java:900)
E/KurobaEx-beta | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/KurobaEx-beta | Chan: 	at android.os.Looper.loop(Looper.java:219)
E/KurobaEx-beta | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:8347)
E/KurobaEx-beta | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaEx-beta | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/KurobaEx-beta | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
E/KurobaEx-beta | UNCAUGHT: Called from unhandled exception handler.
E/KurobaEx-beta | UNCAUGHT: java.lang.IllegalArgumentException: First post is not an original post! post=ChanPost{chanPostId=0, postDescriptor=PD(Lainchan/Î©/36474/36456,0), postImages=1, subject='Used/refurbished HP Z600 workstation', postComment=They have two Xeon sockets (12MB cache) and can accept soykafloa}
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.model.data.thread.ChanThread.getOriginalPost(ChanThread.kt:175)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.model.data.thread.ChanThread.isClosed(ChanThread.kt:53)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.core.presenter.ThreadPresenter.isWatching(ThreadPresenter.kt:1553)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.core.presenter.ThreadPresenter.onChanLoaderData(ThreadPresenter.kt:695)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.core.presenter.ThreadPresenter$normalLoad$1$1.invokeSuspend(ThreadPresenter.kt:427)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.core.presenter.ThreadPresenter$normalLoad$1$1.invoke(Unknown Source:10)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.core.manager.ChanThreadManager.loadThreadOrCatalog(ChanThreadManager.kt:104)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.core.manager.ChanThreadManager$loadThreadOrCatalog$1.invokeSuspend(Unknown Source:18)
E/KurobaEx-beta | UNCAUGHT: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:900)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:219)
E/KurobaEx-beta | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:8347)
E/KurobaEx-beta | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaEx-beta | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/KurobaEx-beta | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
E/KurobaEx-beta | UNCAUGHT: ------------------------------
E/KurobaEx-beta | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/KurobaEx-beta | UNCAUGHT: ------------------------------
E/KurobaEx-beta | UNCAUGHT: Android API Level: 29
E/KurobaEx-beta | UNCAUGHT: App Version: v0.4.2.5643
E/KurobaEx-beta | UNCAUGHT: Development Build: Debug
E/KurobaEx-beta | UNCAUGHT: Phone Model: HUAWEI ELE-L29


=== SETTINGS ===
Prefetching enabled: false
Hi-res thumbnails enabled: false
Youtube titles and durations parsing enabled: WIFI
WEBM streaming enabled: false
Saved files base dir info: Java API location: "/storage/emulated/0/KurobaEx-beta/files", SAF location: "", active: Java API
Phone layout mode: SLIDE
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
```

**Comment by K1rakishou** [comment]
https://lainchan.org/%CE%A9/res/36474.html

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/ea755ed5c7a47e5209b2898a378951711db4c8a1
