### ISSUE TITLE
Crash report "java.lang.IllegalStateException: Bad descriptor: null"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#267]
Crash report
UUID: f453facad9d9e387c615eacb8dd4842e
Build flavor: beta
Version name: v0.4.3
OS info: Android 11, sdk version: 30
Report description: No title
Logs:
```
=== LOGS(2021-01-10 22:32:35 UTC) ===
D/KurobaEx-beta | AppModuleAndroidUtils: Signature hash: DC5195CC40E42B95267D500B6E93E46EC51028C67BDD3D09BBB9C208BF20C8FE
D/KurobaEx-beta | Chan: maxPostsCountInPostsCache = 16384
D/KurobaEx-beta | Chan: maxAmountOfPostsInDatabase = 125000
D/KurobaEx-beta | Chan: maxAmountOfThreadsInDatabase = 12500
D/KurobaEx-beta | Chan: userAgent = Mozilla/5.0 (Linux; Android 11; ASUS_I01WD) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.127 Mobile Safari/537.36
D/KurobaEx-beta | Chan: kurobaExUserAgent = KurobaEx-beta v0.4.3.5784
D/KurobaEx-beta | Dependency Injection: Using DnsSelector.Mode.IPV4_ONLY
D/KurobaEx-beta | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/KurobaEx-beta | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.beta/files/kurobaex_theme_dark.json) does not exist on the disk
D/KurobaEx-beta | ThemeParser: Theme (/data/user/0/com.github.k1rakishou.chan.beta/files/kurobaex_theme_light.json) does not exist on the disk
D/KurobaEx-beta | Dependency Injection: Available space for cache dir: 4581871616 bytes, cacheDirPath = /storage/emulated/0/Android/data/com.github.k1rakishou.chan.beta/cache
D/KurobaEx-beta | SiteManager: SiteManager.initialize()
D/KurobaEx-beta | BoardManager: BoardManager.initialize()
D/KurobaEx-beta | SiteManager: loadSites() start
D/KurobaEx-beta | BookmarksManager: BookmarksManager.initialize()
D/KurobaEx-beta | BoardManager: loadBoards() start
D/KurobaEx-beta | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/KurobaEx-beta | BookmarkWatcherController: BookmarkWatcherCoordinator.initialize()
D/KurobaEx-beta | ArchivesManager: ArchivesManager.initialize()
D/KurobaEx-beta | ChanFilterManager: ChanFilterManager.initialize()
D/KurobaEx-beta | Chan: Application initialization took 196ms
D/KurobaEx-beta | StartActivity: onCreate() start isFreshStart: false, initializing everything
D/KurobaEx-beta | ChanPostRepository: Not enough posts to start deleting, posts in database amount: 97364, max allowed posts amount: 125000
D/KurobaEx-beta | Dependency Injection: Available space for cache dir: 4581871616 bytes, cacheDirPath = /storage/emulated/0/Android/data/com.github.k1rakishou.chan.beta/cache
D/KurobaEx-beta | ChanThreadLoaderCoordinator: Thread count: 8
D/KurobaEx-beta | BoardRepository: loadAllBoards() -> 7 took 52.4ms
D/KurobaEx-beta | SiteRepository: initializeSites() -> 16 took 53.6ms
D/KurobaEx-beta | SiteRepository: allSitesLoadedInitializer initialized
D/KurobaEx-beta | ThreadBookmarkGroupRepository: initialize() -> 1 took 9.33ms
D/KurobaEx-beta | ThreadBookmarkGroupEntryManager: ThreadBookmarkGroupEntryManager initialized! Loaded 1 total bookmark groups
D/KurobaEx-beta | ChanFilterManager: loadFilters() took 197ms
D/KurobaEx-beta | SiteManager: loadSites() took 206ms
D/KurobaEx-beta | ChanPostRepository: Not enough threads to start deleting, threads in database amount: 6906, max allowed threads amount: 12500
D/KurobaEx-beta | Android10GesturesExclusionZonesHolder: Json setting string is empty, reset.
D/KurobaEx-beta | BoardManager: loadBoards() took 222ms
D/KurobaEx-beta | OnDemandContentLoaderManager: Loaders count = 4
D/KurobaEx-beta | StartActivity: createUi took 403ms
D/KurobaEx-beta | StartActivity: initializeDependencies took 773us
D/KurobaEx-beta | StartActivity: onCreate() end isFreshStart: false
D/KurobaEx-beta | Chan: ^^^ App went foreground ^^^
D/KurobaEx-beta | ApplicationVisibilityManager: onEnteredForeground() callback execution took 1.40ms, callbacks count: 1
D/KurobaEx-beta | StartActivity: start
D/KurobaEx-beta | StartActivity: onNewIntent() -> IntentNotHandled
D/KurobaEx-beta | BookmarksManager: BookmarksManager is not ready yet, waiting...
D/KurobaEx-beta | ThreadBookmarkLocalSource: siteNamesForNewGroups=[], maxOrder=16
D/KurobaEx-beta | BookmarksRepository: initialize() -> 1 took 6.54ms
D/KurobaEx-beta | BookmarksManager: BookmarksManager initialized! Loaded 1 total bookmarks and 1 active bookmarks
D/KurobaEx-beta | HistoryNavigationRepository: initialize() -> 128 took 22.2ms
D/KurobaEx-beta | HistoryNavigationManager: HistoryNavigationManager initialized!
D/KurobaEx-beta | AppModuleAndroidUtils: waitForLayout requested a re-layout by returning false
D/KurobaEx-beta | BookmarksManager: BookmarksManager initialization completed, took 70.6ms
D/KurobaEx-beta | BookmarksManager: persistBookmarks async called
D/KurobaEx-beta | StartActivityIntentHandlerHelper: setupFromStateOrFreshLaunch(intent==null: false, savedInstanceState==null: false)
D/KurobaEx-beta | StartActivityIntentHandlerHelper: onNewIntentInternal() -> IntentNotHandled
D/KurobaEx-beta | StartActivityIntentHandlerHelper: restoreFromSavedState()
W/KurobaEx-beta | StartActivityIntentHandlerHelper: savedInstanceState was not null, but no ChanState was found!
D/KurobaEx-beta | StartActivityIntentHandlerHelper: restoreFresh(allowedToOpenThread=true)
D/KurobaEx-beta | StartActivityIntentHandlerHelper: getBoardToOpen, loadLastOpenedBoardUponAppStart=true
D/KurobaEx-beta | StartActivityIntentHandlerHelper: getThreadToOpen, loadLastOpenedThreadUponAppStart=true
D/KurobaEx-beta | StartActivityIntentHandlerHelper: restoreFresh() getBoardToOpen returned BD{4chan/v}, getThreadToOpen returned TD{4chan/v/539940568}
D/KurobaEx-beta | BrowseController: showBoard(BD{4chan/v}, false)
D/KurobaEx-beta | BrowseController: showBoardInternal(BD{4chan/v}, false)
E/KurobaEx-beta | Chan: Unhandled exception
E/KurobaEx-beta | Chan: java.lang.IllegalStateException: Bad descriptor: null
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.ui.controller.BrowseController.onGainedFocus(BrowseController.kt:762)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.ui.controller.ThreadSlideController.notifyFocusGained(ThreadSlideController.java:365)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.ui.controller.ThreadSlideController.slideStateChanged(ThreadSlideController.java:339)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.ui.controller.ThreadSlideController.switchToController(ThreadSlideController.java:190)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.ui.controller.BrowseController.showBoardInternal(BrowseController.kt:739)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.ui.controller.BrowseController$showBoard$2.invokeSuspend(BrowseController.kt:625)
E/KurobaEx-beta | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:342)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:27)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:49)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.ui.controller.BrowseController.showBoard(BrowseController.kt:622)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.helper.StartActivityStartupHandlerHelper.restoreFresh(StartActivityStartupHandlerHelper.kt:120)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.helper.StartActivityStartupHandlerHelper.setupFromStateOrFreshLaunch(StartActivityStartupHandlerHelper.kt:96)
E/KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.helper.StartActivityStartupHandlerHelper$setupFromStateOrFreshLaunch$1.invokeSuspend(Unknown Source:12)
E/KurobaEx-beta | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
E/KurobaEx-beta | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
E/KurobaEx-beta | Chan: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/KurobaEx-beta | Chan: 	at android.os.Handler.handleCallback(Handler.java:938)
E/KurobaEx-beta | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/KurobaEx-beta | Chan: 	at android.os.Looper.loop(Looper.java:248)
E/KurobaEx-beta | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:7787)
E/KurobaEx-beta | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaEx-beta | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/KurobaEx-beta | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
E/KurobaEx-beta | UNCAUGHT: Called from unhandled exception handler.
E/KurobaEx-beta | UNCAUGHT: java.lang.IllegalStateException: Bad descriptor: null
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.ui.controller.BrowseController.onGainedFocus(BrowseController.kt:762)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.ui.controller.ThreadSlideController.notifyFocusGained(ThreadSlideController.java:365)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.ui.controller.ThreadSlideController.slideStateChanged(ThreadSlideController.java:339)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.ui.controller.ThreadSlideController.switchToController(ThreadSlideController.java:190)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.ui.controller.BrowseController.showBoardInternal(BrowseController.kt:739)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.ui.controller.BrowseController$showBoard$2.invokeSuspend(BrowseController.kt:625)
E/KurobaEx-beta | UNCAUGHT: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:342)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:27)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:49)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.ui.controller.BrowseController.showBoard(BrowseController.kt:622)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.core.helper.StartActivityStartupHandlerHelper.restoreFresh(StartActivityStartupHandlerHelper.kt:120)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.core.helper.StartActivityStartupHandlerHelper.setupFromStateOrFreshLaunch(StartActivityStartupHandlerHelper.kt:96)
E/KurobaEx-beta | UNCAUGHT: 	at com.github.k1rakishou.chan.core.helper.StartActivityStartupHandlerHelper$setupFromStateOrFreshLaunch$1.invokeSuspend(Unknown Source:12)
E/KurobaEx-beta | UNCAUGHT: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
E/KurobaEx-beta | UNCAUGHT: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
E/KurobaEx-beta | UNCAUGHT: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:938)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/KurobaEx-beta | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:248)
E/KurobaEx-beta | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:7787)
E/KurobaEx-beta | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/KurobaEx-beta | UNCAUGHT: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/KurobaEx-beta | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
E/KurobaEx-beta | UNCAUGHT: ------------------------------
E/KurobaEx-beta | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/KurobaEx-beta | UNCAUGHT: ------------------------------
E/KurobaEx-beta | UNCAUGHT: Android API Level: 30
E/KurobaEx-beta | UNCAUGHT: App Version: v0.4.3.5784
E/KurobaEx-beta | UNCAUGHT: Development Build: Debug
E/KurobaEx-beta | UNCAUGHT: Phone Model: asus ASUS_I01WD


=== SETTINGS ===
Prefetching enabled: true
Hi-res thumbnails enabled: false
Youtube titles and durations parsing enabled: WIFI
WEBM streaming enabled: false
Saved files base dir info: Java API location: "/storage/emulated/0/KurobaEx-beta/files", SAF location: "content://com.android.externalstorage.documents/tree/primary%3AKurobaEx-beta", active: SAF
Phone layout mode: SLIDE
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/70fc686cfd71f8b2a370f67b5499df0ecfe1638a
