### ISSUE TITLE
Crash report " java.lang.IllegalArgumentException: Stack is empty"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#372]
Crash report
UUID: 96d67f31978b34d1b9efa22029ffa116
Build flavor: fdroid
Version name: v0.8.2
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
=== LOGS(2021-05-04 17:03:40 UTC) ===
D/(19:03:37.254) KurobaEx-fdroid | AppModuleAndroidUtils: Signature hash: 5A4B2B8F667DBF9F4627A48FD85ABE9AE409E30857A1FD5B5384660AA6CFF4FC
D/(19:03:37.733) KurobaEx-fdroid | Chan: maxPostsCountInPostsCache = 10240
D/(19:03:37.733) KurobaEx-fdroid | Chan: maxAmountOfPostsInDatabase = 125000
D/(19:03:37.733) KurobaEx-fdroid | Chan: maxAmountOfThreadsInDatabase = 12500
D/(19:03:37.733) KurobaEx-fdroid | Chan: diskCacheCleanupRemovePercent = 25
D/(19:03:37.734) KurobaEx-fdroid | Chan: databasePostsCleanupRemovePercent = 25
D/(19:03:37.734) KurobaEx-fdroid | Chan: userAgent = Mozilla/5.0 (Linux; Android 10; Redmi 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.127 Mobile Safari/537.36
D/(19:03:37.734) KurobaEx-fdroid | Chan: kurobaExUserAgent = KurobaEx-fdroid v0.8.2.10398
D/(19:03:37.734) KurobaEx-fdroid | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/(19:03:37.788) KurobaEx-fdroid | ChanPostRepository: ChanPostRepository.initialize()
D/(19:03:37.946) KurobaEx-fdroid | Dependency Injection: Available space for cache dir: 13526843392 bytes, cacheDirPath = /data/user/0/com.github.k1rakishou.chan.fdroid/cache
D/(19:03:37.948) KurobaEx-fdroid | CacheHandler: fileCacheDiskSizeMBytes=512
D/(19:03:37.965) KurobaEx-fdroid | SiteManager: SiteManager.initialize()
D/(19:03:37.965) KurobaEx-fdroid | AnrSupervisorRunnable: ANR supervision started
D/(19:03:37.966) KurobaEx-fdroid | BoardManager: BoardManager.initialize()
D/(19:03:37.966) KurobaEx-fdroid | SiteManager: loadSitesInternal() start
D/(19:03:37.967) KurobaEx-fdroid | BookmarksManager: BookmarksManager.initialize()
D/(19:03:37.967) KurobaEx-fdroid | BoardManager: loadBoardsInternal() start
D/(19:03:37.967) KurobaEx-fdroid | BoardManager: loadBoardsInternal() siteDataListAsync.get() start
D/(19:03:37.968) KurobaEx-fdroid | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/(19:03:37.968) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() start
D/(19:03:37.970) KurobaEx-fdroid | BookmarkWatcherController: BookmarkWatcherCoordinator.initialize()
D/(19:03:37.971) KurobaEx-fdroid | HistoryNavigationManager: initializeHistoryNavigationManagerInternal() start
D/(19:03:37.972) KurobaEx-fdroid | FilterWatcherCoordinator: FilterWatcherCoordinator.initialize()
D/(19:03:37.974) KurobaEx-fdroid | ArchivesManager: ArchivesManager.initialize()
D/(19:03:37.975) KurobaEx-fdroid | ChanFilterManager: ChanFilterManager.initialize()
D/(19:03:37.975) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() start
D/(19:03:37.976) KurobaEx-fdroid | ThreadBookmarkGroupEntryManager: ThreadBookmarkGroupManager.initialize()
D/(19:03:37.977) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() start
D/(19:03:37.980) KurobaEx-fdroid | ThreadBookmarkGroupEntryManager: loadThreadBookmarkGroupsInternal() start
D/(19:03:37.982) KurobaEx-fdroid | AnrSupervisorRunnable: onApplicationLoaded() switching to interval 3000ms
D/(19:03:37.982) KurobaEx-fdroid | Chan: Application initialization took 261ms
D/(19:03:38.003) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithModularResult() called
D/(19:03:38.003) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithValue() called
D/(19:03:38.003) KurobaEx-fdroid | ArchivesManager: notifyAllWaiters throwable==null: true, waiters=0
D/(19:03:38.004) KurobaEx-fdroid | ArchivesManager: SuspendableInitializer initWithValue() done
D/(19:03:38.004) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() done. Loaded 14 archives
D/(19:03:38.004) KurobaEx-fdroid | ArchivesManager: initializeArchivesManagerInternal() end
D/(19:03:38.015) KurobaEx-fdroid | ChanPostRepository: Not enough posts to start deleting, posts in database amount: 95102, max allowed posts amount: 125000
D/(19:03:38.036) KurobaEx-fdroid | SiteRepository: initializeSites() -> 19 took 12.4ms
D/(19:03:38.039) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithModularResult() called
D/(19:03:38.040) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(19:03:38.041) KurobaEx-fdroid | allSitesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(19:03:38.041) KurobaEx-fdroid | allSitesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(19:03:38.042) KurobaEx-fdroid | SiteRepository: allSitesLoadedInitializer initialized
D/(19:03:38.048) KurobaEx-fdroid | ThreadBookmarkLocalSource: siteNamesForNewGroups=[], maxOrder=19
D/(19:03:38.051) KurobaEx-fdroid | StartActivity: onCreate() start isFreshStart: true, initializing everything
D/(19:03:38.235) KurobaEx-fdroid | CacheHandler: recalculateSize() took 284ms, filesOnDiskCount=2539, fullyDownloadedFilesCount=0
D/(19:03:38.304) KurobaEx-fdroid | SiteManager: SuspendableInitializer initWithValue() called
D/(19:03:38.304) KurobaEx-fdroid | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(19:03:38.304) KurobaEx-fdroid | SiteManager: SuspendableInitializer initWithValue() done
D/(19:03:38.305) KurobaEx-fdroid | BoardManager: loadBoardsInternal() siteDataListAsync.get() end
D/(19:03:38.305) KurobaEx-fdroid | SiteManager: siteRepository.initializeSites() done. Loaded 19 sites
D/(19:03:38.321) KurobaEx-fdroid | SiteManager: loadSitesInternal() took 354ms
D/(19:03:38.406) KurobaEx-fdroid | ControllerNavigationManager: onControllerPushed(ThreadSlideController)
D/(19:03:38.443) KurobaEx-fdroid | OnDemandContentLoaderManager: Loaders count = 4
D/(19:03:38.466) KurobaEx-fdroid | BookmarksRepository: initialize() -> 337 took 421ms
D/(19:03:38.477) KurobaEx-fdroid | BookmarksManager: SuspendableInitializer initWithValue() called
D/(19:03:38.478) KurobaEx-fdroid | BookmarksManager: notifyAllWaiters throwable==null: true, waiters=0
D/(19:03:38.478) KurobaEx-fdroid | BookmarksManager: SuspendableInitializer initWithValue() done
D/(19:03:38.497) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() done. Loaded 337 bookmarks and 337 active bookmarks
D/(19:03:38.498) KurobaEx-fdroid | BookmarksManager: initializeBookmarksInternal() end
D/(19:03:38.514) KurobaEx-fdroid | HistoryNavigationRepository: initialize() -> 128 took 34.3ms
D/(19:03:38.518) KurobaEx-fdroid | HistoryNavigationManager: SuspendableInitializer initWithValue() called
D/(19:03:38.519) KurobaEx-fdroid | HistoryNavigationManager: notifyAllWaiters throwable==null: true, waiters=0
D/(19:03:38.519) KurobaEx-fdroid | HistoryNavigationManager: SuspendableInitializer initWithValue() done
D/(19:03:38.519) KurobaEx-fdroid | HistoryNavigationManager: initializeHistoryNavigationManagerInternal() done. Loaded 128 history nav elements
D/(19:03:38.519) KurobaEx-fdroid | HistoryNavigationManager: initializeHistoryNavigationManagerInternal() end
D/(19:03:38.528) KurobaEx-fdroid | ChanFilterManager: SuspendableInitializer initWithValue() called
D/(19:03:38.529) KurobaEx-fdroid | ChanFilterManager: notifyAllWaiters throwable==null: true, waiters=0
D/(19:03:38.530) KurobaEx-fdroid | ChanFilterManager: SuspendableInitializer initWithValue() done
D/(19:03:38.530) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() done. Loaded 0 filters
D/(19:03:38.534) KurobaEx-fdroid | ChanFilterManager: loadFiltersInternal() end, took 555ms
D/(19:03:38.692) KurobaEx-fdroid | StartActivity: createUi took 589ms
D/(19:03:38.694) KurobaEx-fdroid | UpdateManager: autoUpdateCheck()
D/(19:03:38.695) KurobaEx-fdroid | UpdateManager: Updater is disabled for fdroid builds!
D/(19:03:38.698) KurobaEx-fdroid | StartActivity: initializeDependencies took 3.59ms
D/(19:03:38.699) KurobaEx-fdroid | HistoryNavigationManager: notifyAllWaiters throwable==null: true, waiters=0
D/(19:03:38.700) KurobaEx-fdroid | BoardManager: BoardManager is not ready yet, waiting...
D/(19:03:38.701) KurobaEx-fdroid | BoardManager: SuspendableInitializer awaitUntilInitialized() called when not initialized, awaiting...
D/(19:03:38.702) KurobaEx-fdroid | StartActivity: onCreate() end isFreshStart: true
D/(19:03:38.709) KurobaEx-fdroid | Chan: ^^^ App went foreground ^^^
D/(19:03:38.713) KurobaEx-fdroid | ApplicationVisibilityManager: onEnteredForeground() callback execution took 3.00ms, callbacks count: 3
D/(19:03:38.715) KurobaEx-fdroid | StartActivity: start
D/(19:03:38.768) KurobaEx-fdroid | BookmarksManager: persistBookmarks async called
D/(19:03:38.831) KurobaEx-fdroid | AppModuleAndroidUtils: waitForLayout requested a re-layout by returning false
D/(19:03:38.974) KurobaEx-fdroid | BookmarkWatcherController: restartBackgroundWork() called tag=BookmarkWatcherController_Fdroid
D/(19:03:38.975) KurobaEx-fdroid | BookmarkWatcherController: restartBackgroundWork() cannot restart watcher because one of the required settings is turned off (watchEnabled=false, watchBackground=false)
D/(19:03:38.976) KurobaEx-fdroid | BookmarkWatcherController: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Fdroid
D/(19:03:38.983) KurobaEx-fdroid | FilterWatcherCoordinator: cancelFilterWatching() called tag=FilterWatcherController_Fdroid
D/(19:03:39.016) KurobaEx-fdroid | BookmarkWatcherController: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Fdroid canceled
D/(19:03:39.019) KurobaEx-fdroid | BookmarkWatcherController: restartBackgroundWork() called tag=BookmarkWatcherController_Fdroid
D/(19:03:39.019) KurobaEx-fdroid | BookmarkWatcherController: restartBackgroundWork() cannot restart watcher because one of the required settings is turned off (watchEnabled=false, watchBackground=false)
D/(19:03:39.019) KurobaEx-fdroid | BookmarkWatcherController: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Fdroid
D/(19:03:39.034) KurobaEx-fdroid | FilterWatcherCoordinator: cancelFilterWatching() work with tag FilterWatcherController_Fdroid canceled
D/(19:03:39.046) KurobaEx-fdroid | BookmarkWatcherController: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Fdroid canceled
D/(19:03:39.047) KurobaEx-fdroid | BookmarkWatcherController: restartBackgroundWork() called tag=BookmarkWatcherController_Fdroid
D/(19:03:39.048) KurobaEx-fdroid | BookmarkWatcherController: restartBackgroundWork() cannot restart watcher because one of the required settings is turned off (watchEnabled=false, watchBackground=false)
D/(19:03:39.048) KurobaEx-fdroid | BookmarkWatcherController: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Fdroid
D/(19:03:39.058) KurobaEx-fdroid | BookmarkWatcherController: onBookmarksChanged() watchEnabled is false, stopping foreground watcher
D/(19:03:39.058) KurobaEx-fdroid | BookmarkWatcherController: cancelForegroundBookmarkWatching() called
D/(19:03:39.058) KurobaEx-fdroid | BookmarkWatcherController: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Fdroid
D/(19:03:39.060) KurobaEx-fdroid | BookmarkWatcherController: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Fdroid canceled
D/(19:03:39.070) KurobaEx-fdroid | BookmarkWatcherController: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Fdroid canceled
D/(19:03:39.088) KurobaEx-fdroid | HistoryNavigationManager: notifyAllWaiters throwable==null: true, waiters=0
D/(19:03:39.452) KurobaEx-fdroid | BookmarkWatcherController: onBookmarksChanged() watchEnabled is false, stopping foreground watcher
D/(19:03:39.452) KurobaEx-fdroid | BookmarkWatcherController: cancelForegroundBookmarkWatching() called
D/(19:03:39.453) KurobaEx-fdroid | BookmarkWatcherController: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Fdroid
D/(19:03:39.554) KurobaEx-fdroid | BookmarkWatcherController: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Fdroid canceled
D/(19:03:40.021) KurobaEx-fdroid | FilterWatcherCoordinator: restartFilterWatcherWithTinyDelay() no watch filters found, canceling the work
D/(19:03:40.022) KurobaEx-fdroid | FilterWatcherCoordinator: cancelFilterWatching() called tag=FilterWatcherController_Fdroid
D/(19:03:40.030) KurobaEx-fdroid | FilterWatcherCoordinator: cancelFilterWatching() work with tag FilterWatcherController_Fdroid canceled
D/(19:03:40.141) KurobaEx-fdroid | ControllerNavigationManager: onCloseAllNonMainControllers()
D/(19:03:40.177) KurobaEx-fdroid | ThreadBookmarkGroupRepository: initialize() -> 337 took 1.65s
D/(19:03:40.179) KurobaEx-fdroid | BoardManager: BoardManager is not ready yet, waiting...
D/(19:03:40.180) KurobaEx-fdroid | BoardManager: SuspendableInitializer awaitUntilInitialized() called when not initialized, awaiting...
D/(19:03:40.182) KurobaEx-fdroid | ControllerNavigationManager: onControllerPushed(MainSettingsControllerV2)
D/(19:03:40.183) KurobaEx-fdroid | ThreadBookmarkGroupManager: SuspendableInitializer initWithValue() called
D/(19:03:40.183) KurobaEx-fdroid | ThreadBookmarkGroupManager: notifyAllWaiters throwable==null: true, waiters=0
D/(19:03:40.183) KurobaEx-fdroid | ThreadBookmarkGroupManager: SuspendableInitializer initWithValue() done
D/(19:03:40.183) KurobaEx-fdroid | ThreadBookmarkGroupEntryManager: loadThreadBookmarkGroupsInternal() done. Loaded 1 bookmark groups
D/(19:03:40.184) KurobaEx-fdroid | ThreadBookmarkGroupEntryManager: loadThreadBookmarkGroupsInternal() end
D/(19:03:40.209) KurobaEx-fdroid | ChanPostRepository: Not enough threads to start deleting, threads in database amount: 12121, max allowed threads amount: 12500
D/(19:03:40.212) KurobaEx-fdroid | ChanPostRepository: SuspendableInitializer initWithValue() called
D/(19:03:40.212) KurobaEx-fdroid | ChanPostRepository: notifyAllWaiters throwable==null: true, waiters=0
D/(19:03:40.212) KurobaEx-fdroid | ChanPostRepository: SuspendableInitializer initWithValue() done
D/(19:03:40.277) KurobaEx-fdroid | screensBuiltOnce: SuspendableInitializer awaitUntilInitialized() called when not initialized, awaiting...
D/(19:03:40.412) KurobaEx-fdroid | BoardRepository: loadAllBoards() -> 703 took 195ms
D/(19:03:40.417) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist(337)
D/(19:03:40.427) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() called
D/(19:03:40.428) KurobaEx-fdroid | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(19:03:40.429) KurobaEx-fdroid | BoardManager: SuspendableInitializer awaitUntilInitialized() called when not initialized, done (diffTime=1728ms)
D/(19:03:40.429) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() done
D/(19:03:40.429) KurobaEx-fdroid | BoardManager: BoardManager initialization completed, took 1.73s
D/(19:03:40.429) KurobaEx-fdroid | BoardManager: loadBoardsInternal() done. Loaded 703 boards
D/(19:03:40.430) KurobaEx-fdroid | StartActivityIntentHandlerHelper: setupFromStateOrFreshLaunch(intent==null: false, savedInstanceState==null: true)
D/(19:03:40.430) KurobaEx-fdroid | BoardManager: loadBoardsInternal() took 2.46s
D/(19:03:40.430) KurobaEx-fdroid | StartActivityIntentHandlerHelper: onNewIntentInternal() -> false
D/(19:03:40.431) KurobaEx-fdroid | StartActivityIntentHandlerHelper: restoreFresh(allowedToOpenThread=true)
D/(19:03:40.431) KurobaEx-fdroid | StartActivityIntentHandlerHelper: getBoardToOpen(), loadLastOpenedBoardUponAppStart=true
D/(19:03:40.432) KurobaEx-fdroid | StartActivityIntentHandlerHelper: getThreadToOpen(), loadLastOpenedThreadUponAppStart=true
D/(19:03:40.433) KurobaEx-fdroid | StartActivityIntentHandlerHelper: restoreFresh() getBoardToOpen returned BD{4chan/o}, getThreadToOpen returned TD{4chan/o/23998522}
D/(19:03:40.434) KurobaEx-fdroid | BrowseController: showBoard(BD{4chan/o}, false)
D/(19:03:40.434) KurobaEx-fdroid | BrowseController: showBoardInternal(BD{4chan/o}, false)
D/(19:03:40.435) KurobaEx-fdroid | BrowseController: setBoard(BD{4chan/o})
D/(19:03:40.437) KurobaEx-fdroid | BrowseController: loadBoard(BD{4chan/o})
D/(19:03:40.449) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(19:03:40.450) KurobaEx-fdroid | BookmarksRepository: persist(337) took 32.8ms
D/(19:03:40.453) KurobaEx-fdroid | ThreadPresenter: chanThreadTicker.startTicker(CD{4chan/o})
D/(19:03:40.454) KurobaEx-fdroid | ChanTicker: startTicker(CD{4chan/o})
D/(19:03:40.454) KurobaEx-fdroid | ChanTicker: kickTicker(false)
D/(19:03:40.455) KurobaEx-fdroid | ChanTicker: kickTicker() called with catalog descriptor, ticking right away
D/(19:03:40.458) KurobaEx-fdroid | BoardManager: SuspendableInitializer awaitUntilInitialized() called when not initialized, done (diffTime=278ms)
D/(19:03:40.459) KurobaEx-fdroid | BoardManager: BoardManager initialization completed, took 279ms
D/(19:03:40.499) KurobaEx-fdroid | screensBuiltOnce: SuspendableInitializer initWithValue() called
D/(19:03:40.500) KurobaEx-fdroid | screensBuiltOnce: notifyAllWaiters throwable==null: true, waiters=0
D/(19:03:40.500) KurobaEx-fdroid | screensBuiltOnce: SuspendableInitializer initWithValue() done
D/(19:03:40.510) KurobaEx-fdroid | BookmarksManager: persistBookmarks async finished
D/(19:03:40.511) KurobaEx-fdroid | ChanTicker: StopTicker
D/(19:03:40.512) KurobaEx-fdroid | ControllerNavigationManager: onCloseAllNonMainControllers()
D/(19:03:40.531) KurobaEx-fdroid | BrowseController: showThread(TD{4chan/o/23998522}, false)
D/(19:03:40.667) KurobaEx-fdroid | ControllerNavigationManager: onControllerSwipedFrom(BrowseController)
D/(19:03:40.668) KurobaEx-fdroid | ControllerNavigationManager: onControllerSwipedTo(ViewThreadController)
D/(19:03:40.670) KurobaEx-fdroid | ViewThreadController: loadThread(TD{4chan/o/23998522})
D/(19:03:40.674) KurobaEx-fdroid | ThreadPresenter: chanThreadTicker.startTicker(TD{4chan/o/23998522})
D/(19:03:40.674) KurobaEx-fdroid | ChanTicker: startTicker(TD{4chan/o/23998522})
D/(19:03:40.674) KurobaEx-fdroid | ChanTicker: kickTicker(false)
D/(19:03:40.676) KurobaEx-fdroid | screensBuiltOnce: SuspendableInitializer awaitUntilInitialized() called when not initialized, done (diffTime=398ms)
E/(19:03:40.680) KurobaEx-fdroid | Chan: Unhandled exception
E/(19:03:40.680) KurobaEx-fdroid | Chan: java.lang.IllegalArgumentException: Stack is empty
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.features.settings.SettingsCoordinator.rebuildCurrentScreen(SettingsCoordinator.kt:5)
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.features.settings.SettingsCoordinator$onCreate$2$invokeSuspend$$inlined$collect$1.emit(Collect.kt:9)
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.features.settings.SettingsCoordinator$onCreate$2$invokeSuspend$$inlined$collect$1$1.invokeSuspend(Unknown Source:12)
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:11)
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:3)
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:11)
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at android.os.Handler.handleCallback(Handler.java:883)
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at android.os.Looper.loop(Looper.java:214)
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
E/(19:03:40.680) KurobaEx-fdroid | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)


------------------------------
Android API Level: 29
App Version: v0.8.2.10398
Development Build: Unknown
Phone Model: Xiaomi Redmi 7
------------------------------
Current layout mode: SLIDE
Board view mode: GRID
Prefetching enabled: false
Hi-res thumbnails enabled: false
CloudFlare force preload enabled: true
diskCacheSizeMegabytes: 512
prefetchDiskCacheSizeMegabytes: 1024
diskCacheCleanupRemovePercent: 25
databasePostCachingEnabled: true
databaseMaxPostsCount: 125000
databaseMaxThreadsCount: 12500
databasePostsCleanupRemovePercent: 25
WEBM streaming enabled: false
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3AReadChan
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: false
Background watcher enabled: false
Filter watch enabled: false
------------------------------
```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/3afc3bcba23a309fc86a2d5aa5f7c6c5bcb8869c
