### ISSUE TITLE
Report "bookmarks not working correctly"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#397]
UUID: a400424fd1b272822df16c2720a40cdb
Build flavor: beta
Version name: v0.8.7
OS info: Android 10, sdk version: 29
Report description: New bookmarks do not show up in the bookmark tab, only in the side rail, and are cleared upon app shutdown. Occasionally, the unread replies count still displays unread posts even though there are none.
Logs:
```
E/(17:57:06.225) KurobaEx-beta | BookmarksManager: Failed to persist bookmarks
E/(17:57:06.225) KurobaEx-beta | BookmarksManager: java.lang.IllegalArgumentException: chanDescriptorCache does not contain threadDatabaseId for threadDescriptor: TD{4chan/vg/335068212}
E/(17:57:06.225) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource.insertOrUpdateBookmarks(ThreadBookmarkLocalSource.kt:37)
E/(17:57:06.225) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource.persist(ThreadBookmarkLocalSource.kt:45)
E/(17:57:06.225) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource$persist$1.invokeSuspend(Unknown Source:12)
E/(17:57:06.225) KurobaEx-beta | BookmarksManager: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/(17:57:06.225) KurobaEx-beta | BookmarksManager: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(17:57:06.225) KurobaEx-beta | BookmarksManager: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:22)
E/(17:57:06.225) KurobaEx-beta | BookmarksManager: 	at android.support.v4.media.session.MediaSessionCompat.runBlocking(MediaSessionCompat.java:18)
E/(17:57:06.225) KurobaEx-beta | BookmarksManager: 	at androidx.room.RoomDatabaseKt$acquireTransactionThread$$inlined$suspendCancellableCoroutine$lambda$2.run(RoomDatabase.kt:2)
E/(17:57:06.225) KurobaEx-beta | BookmarksManager: 	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
E/(17:57:06.225) KurobaEx-beta | BookmarksManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/(17:57:06.225) KurobaEx-beta | BookmarksManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/(17:57:06.225) KurobaEx-beta | BookmarksManager: 	at java.lang.Thread.run(Thread.java:929)
E/(17:57:06.852) KurobaEx-beta | BookmarksManager: Failed to persist bookmarks
E/(17:57:06.852) KurobaEx-beta | BookmarksManager: java.lang.IllegalArgumentException: chanDescriptorCache does not contain threadDatabaseId for threadDescriptor: TD{4chan/vg/335068212}
E/(17:57:06.852) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource.insertOrUpdateBookmarks(ThreadBookmarkLocalSource.kt:37)
E/(17:57:06.852) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource.persist(ThreadBookmarkLocalSource.kt:45)
E/(17:57:06.852) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource$persist$1.invokeSuspend(Unknown Source:12)
E/(17:57:06.852) KurobaEx-beta | BookmarksManager: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/(17:57:06.852) KurobaEx-beta | BookmarksManager: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(17:57:06.852) KurobaEx-beta | BookmarksManager: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:22)
E/(17:57:06.852) KurobaEx-beta | BookmarksManager: 	at android.support.v4.media.session.MediaSessionCompat.runBlocking(MediaSessionCompat.java:18)
E/(17:57:06.852) KurobaEx-beta | BookmarksManager: 	at androidx.room.RoomDatabaseKt$acquireTransactionThread$$inlined$suspendCancellableCoroutine$lambda$2.run(RoomDatabase.kt:2)
E/(17:57:06.852) KurobaEx-beta | BookmarksManager: 	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
E/(17:57:06.852) KurobaEx-beta | BookmarksManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/(17:57:06.852) KurobaEx-beta | BookmarksManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/(17:57:06.852) KurobaEx-beta | BookmarksManager: 	at java.lang.Thread.run(Thread.java:929)
E/(17:57:07.883) KurobaEx-beta | BookmarksManager: Failed to persist bookmarks
E/(17:57:07.883) KurobaEx-beta | BookmarksManager: java.lang.IllegalArgumentException: chanDescriptorCache does not contain threadDatabaseId for threadDescriptor: TD{4chan/vg/335068212}
E/(17:57:07.883) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource.insertOrUpdateBookmarks(ThreadBookmarkLocalSource.kt:37)
E/(17:57:07.883) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource.persist(ThreadBookmarkLocalSource.kt:45)
E/(17:57:07.883) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource$persist$1.invokeSuspend(Unknown Source:12)
E/(17:57:07.883) KurobaEx-beta | BookmarksManager: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/(17:57:07.883) KurobaEx-beta | BookmarksManager: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(17:57:07.883) KurobaEx-beta | BookmarksManager: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:22)
E/(17:57:07.883) KurobaEx-beta | BookmarksManager: 	at android.support.v4.media.session.MediaSessionCompat.runBlocking(MediaSessionCompat.java:18)
E/(17:57:07.883) KurobaEx-beta | BookmarksManager: 	at androidx.room.RoomDatabaseKt$acquireTransactionThread$$inlined$suspendCancellableCoroutine$lambda$2.run(RoomDatabase.kt:2)
E/(17:57:07.883) KurobaEx-beta | BookmarksManager: 	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
E/(17:57:07.883) KurobaEx-beta | BookmarksManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/(17:57:07.883) KurobaEx-beta | BookmarksManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/(17:57:07.883) KurobaEx-beta | BookmarksManager: 	at java.lang.Thread.run(Thread.java:929)
E/(17:57:10.122) KurobaEx-beta | BookmarksManager: Failed to persist bookmarks
E/(17:57:10.122) KurobaEx-beta | BookmarksManager: java.lang.IllegalArgumentException: chanDescriptorCache does not contain threadDatabaseId for threadDescriptor: TD{4chan/vg/335068212}
E/(17:57:10.122) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource.insertOrUpdateBookmarks(ThreadBookmarkLocalSource.kt:37)
E/(17:57:10.122) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource.persist(ThreadBookmarkLocalSource.kt:45)
E/(17:57:10.122) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource$persist$1.invokeSuspend(Unknown Source:12)
E/(17:57:10.122) KurobaEx-beta | BookmarksManager: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/(17:57:10.122) KurobaEx-beta | BookmarksManager: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(17:57:10.122) KurobaEx-beta | BookmarksManager: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:22)
E/(17:57:10.122) KurobaEx-beta | BookmarksManager: 	at android.support.v4.media.session.MediaSessionCompat.runBlocking(MediaSessionCompat.java:18)
E/(17:57:10.122) KurobaEx-beta | BookmarksManager: 	at androidx.room.RoomDatabaseKt$acquireTransactionThread$$inlined$suspendCancellableCoroutine$lambda$2.run(RoomDatabase.kt:2)
E/(17:57:10.122) KurobaEx-beta | BookmarksManager: 	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
E/(17:57:10.122) KurobaEx-beta | BookmarksManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/(17:57:10.122) KurobaEx-beta | BookmarksManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/(17:57:10.122) KurobaEx-beta | BookmarksManager: 	at java.lang.Thread.run(Thread.java:929)
E/(17:57:10.554) KurobaEx-beta | BookmarksManager: Failed to persist bookmarks
E/(17:57:10.554) KurobaEx-beta | BookmarksManager: java.lang.IllegalArgumentException: chanDescriptorCache does not contain threadDatabaseId for threadDescriptor: TD{4chan/vg/335068212}
E/(17:57:10.554) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource.insertOrUpdateBookmarks(ThreadBookmarkLocalSource.kt:37)
E/(17:57:10.554) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource.persist(ThreadBookmarkLocalSource.kt:45)
E/(17:57:10.554) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource$persist$1.invokeSuspend(Unknown Source:12)
E/(17:57:10.554) KurobaEx-beta | BookmarksManager: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/(17:57:10.554) KurobaEx-beta | BookmarksManager: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(17:57:10.554) KurobaEx-beta | BookmarksManager: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:22)
E/(17:57:10.554) KurobaEx-beta | BookmarksManager: 	at android.support.v4.media.session.MediaSessionCompat.runBlocking(MediaSessionCompat.java:18)
E/(17:57:10.554) KurobaEx-beta | BookmarksManager: 	at androidx.room.RoomDatabaseKt$acquireTransactionThread$$inlined$suspendCancellableCoroutine$lambda$2.run(RoomDatabase.kt:2)
E/(17:57:10.554) KurobaEx-beta | BookmarksManager: 	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
E/(17:57:10.554) KurobaEx-beta | BookmarksManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/(17:57:10.554) KurobaEx-beta | BookmarksManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/(17:57:10.554) KurobaEx-beta | BookmarksManager: 	at java.lang.Thread.run(Thread.java:929)
E/(17:57:11.208) KurobaEx-beta | BookmarksManager: Failed to persist bookmarks
E/(17:57:11.208) KurobaEx-beta | BookmarksManager: java.lang.IllegalArgumentException: chanDescriptorCache does not contain threadDatabaseId for threadDescriptor: TD{4chan/vg/335068212}
E/(17:57:11.208) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource.insertOrUpdateBookmarks(ThreadBookmarkLocalSource.kt:37)
E/(17:57:11.208) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource.persist(ThreadBookmarkLocalSource.kt:45)
E/(17:57:11.208) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource$persist$1.invokeSuspend(Unknown Source:12)
E/(17:57:11.208) KurobaEx-beta | BookmarksManager: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/(17:57:11.208) KurobaEx-beta | BookmarksManager: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(17:57:11.208) KurobaEx-beta | BookmarksManager: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:22)
E/(17:57:11.208) KurobaEx-beta | BookmarksManager: 	at android.support.v4.media.session.MediaSessionCompat.runBlocking(MediaSessionCompat.java:18)
E/(17:57:11.208) KurobaEx-beta | BookmarksManager: 	at androidx.room.RoomDatabaseKt$acquireTransactionThread$$inlined$suspendCancellableCoroutine$lambda$2.run(RoomDatabase.kt:2)
E/(17:57:11.208) KurobaEx-beta | BookmarksManager: 	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
E/(17:57:11.208) KurobaEx-beta | BookmarksManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/(17:57:11.208) KurobaEx-beta | BookmarksManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/(17:57:11.208) KurobaEx-beta | BookmarksManager: 	at java.lang.Thread.run(Thread.java:929)
E/(17:57:11.334) KurobaEx-beta | BookmarksManager: Failed to persist bookmarks
E/(17:57:11.334) KurobaEx-beta | BookmarksManager: java.lang.IllegalArgumentException: chanDescriptorCache does not contain threadDatabaseId for threadDescriptor: TD{4chan/vg/335068212}
E/(17:57:11.334) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource.insertOrUpdateBookmarks(ThreadBookmarkLocalSource.kt:37)
E/(17:57:11.334) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource.persist(ThreadBookmarkLocalSource.kt:45)
E/(17:57:11.334) KurobaEx-beta | BookmarksManager: 	at com.github.k1rakishou.model.source.local.ThreadBookmarkLocalSource$persist$1.invokeSuspend(Unknown Source:12)
E/(17:57:11.334) KurobaEx-beta | BookmarksManager: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/(17:57:11.334) KurobaEx-beta | BookmarksManager: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(17:57:11.334) KurobaEx-beta | BookmarksManager: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:22)
E/(17:57:11.334) KurobaEx-beta | BookmarksManager: 	at android.support.v4.media.session.MediaSessionCompat.runBlocking(MediaSessionCompat.java:18)
E/(17:57:11.334) KurobaEx-beta | BookmarksManager: 	at androidx.room.RoomDatabaseKt$acquireTransactionThread$$inlined$suspendCancellableCoroutine$lambda$2.run(RoomDatabase.kt:2)
E/(17:57:11.334) KurobaEx-beta | BookmarksManager: 	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
E/(17:57:11.334) KurobaEx-beta | BookmarksManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/(17:57:11.334) KurobaEx-beta | BookmarksManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/(17:57:11.334) KurobaEx-beta | BookmarksManager: 	at java.lang.Thread.run(Thread.java:929)
------------------------------
Android API Level: 29
App Version: v0.8.7.10529
Development Build: Release
Phone Model: HUAWEI ANA-NX9
------------------------------
Current layout mode: SLIDE
Board view mode: GRID
Prefetching enabled: false
Hi-res thumbnails enabled: false
CloudFlare force preload enabled: true
diskCacheSizeMegabytes: 512
prefetchDiskCacheSizeMegabytes: 1024
diskCacheCleanupRemovePercent: 25
databasePostCachingEnabled: false
WEBM streaming enabled: false
ImageSaver root directory: content://com.android.providers.downloads.documents/tree/msd%3A92051
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: true
Watch foreground interval: 60000
Watch foreground adaptive interval: false
Background watcher enabled: false
Filter watch enabled: false
------------------------------
```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/db197b298d454327e365c587b9d7ae6e10127818
