### ISSUE TITLE
Bunch of IOOB exceptions

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#410]
Crash report
UUID: fc9192c53243ce49f102b226bf368e2f
Build flavor: stable
Version name: v0.8.9
OS info: Android 5.0.2, sdk version: 21
Report description: No title
Logs:
```
=== LOGS(2021-05-17 07:39:34 UTC) ===
D/(10:39:28.217) KurobaEx | BookmarkWatcherCoordinator: listenForBookmarksChanges bookmarkChange=com.github.k1rakishou.chan.core.manager.BookmarksManager$BookmarkChange$BookmarksUpdated@133f4b57
D/(10:39:28.218) KurobaEx | ReplyNotificationsHelper: bookmarksManager.listenForBookmarksChanges(), bookmarkChange=BookmarksUpdated
D/(10:39:28.225) KurobaEx | ChunkReader: [NormalFileCacheV2Thread-0]: storeChunkInFile(0) success, url=https://i.4cdn.org/vg/1621182611869.png, chunk 0..180661
D/(10:39:28.242) KurobaEx | FileCacheV2: [NormalFileCacheV2Thread-0]: Success (downloaded = 361.3 kB (361324 B), total = 361.3 kB (361324 B), took 2001ms, network class = WIFI, downloads = 0) for request [FileDownloadRequest: url=https://i.4cdn.org/vg/1621182611869.png, outputFileName = c8d307a9b0f1810384b436f84bc9159f.cache]
D/(10:39:28.243) KurobaEx | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-0]: Completed downloading (https://i.4cdn.org/vg/1621182611869.png)
D/(10:39:29.237) KurobaEx | ReplyNotificationsHelper: showOrUpdateNotificationsInternal() ChanSettings.replyNotifications == false
D/(10:39:29.338) KurobaEx | HistoryNavigationManager: notifyAllWaiters throwable==null: true, waiters=0
D/(10:39:30.247) KurobaEx | ControllerNavigationManager: onControllerUnpresented(ImageViewerNavigationController)
D/(10:39:30.987) KurobaEx | ChanThreadViewableInfoLocalSource: Updating ChanThreadViewableInfo for TD{4chan/vg/335178318}
D/(10:39:32.702) KurobaEx | ChanThreadViewableInfoLocalSource: Updating ChanThreadViewableInfo for TD{4chan/vg/335178318}
D/(10:39:33.152) KurobaEx | BookmarksManager: persistBookmarks async called
D/(10:39:33.156) KurobaEx | ThreadBookmarkLocalSource: persist(8)
D/(10:39:33.159) KurobaEx | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(10:39:33.160) KurobaEx | BookmarksRepository: persist(8) took 3.38ms
D/(10:39:33.189) KurobaEx | PostsFilter: originalPosts.size=757, retainedPosts.size=757, chanDescriptor=TD{4chan/vg/335178318}
D/(10:39:33.200) KurobaEx | BookmarksManager: subscriptions=5
D/(10:39:33.200) KurobaEx | BookmarksManager: persistBookmarks async finished
D/(10:39:33.210) KurobaEx | BookmarkWatcherCoordinator: listenForBookmarksChanges bookmarkChange=com.github.k1rakishou.chan.core.manager.BookmarksManager$BookmarkChange$BookmarksUpdated@2c39693f
D/(10:39:33.210) KurobaEx | ReplyNotificationsHelper: bookmarksManager.listenForBookmarksChanges(), bookmarkChange=BookmarksUpdated
D/(10:39:33.306) KurobaEx | ChanThreadViewableInfoLocalSource: Updating ChanThreadViewableInfo for TD{4chan/vg/335178318}
D/(10:39:33.626) KurobaEx | PostAdapter: setThread() notifyDataSetChanged called, postIndexedList.size=757
E/(10:39:33.630) KurobaEx | Chan: Unhandled exception
E/(10:39:33.630) KurobaEx | Chan: java.lang.IndexOutOfBoundsException: Invalid index 758, size is 757
E/(10:39:33.630) KurobaEx | Chan: 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
E/(10:39:33.630) KurobaEx | Chan: 	at java.util.ArrayList.get(ArrayList.java:308)
E/(10:39:33.630) KurobaEx | Chan: 	at com.github.k1rakishou.chan.ui.cell.ThreadCellData.getPostCellData(ThreadCellData.kt:1)
E/(10:39:33.630) KurobaEx | Chan: 	at com.github.k1rakishou.chan.ui.adapter.PostAdapter.getItemViewTypeSafe(PostAdapter.kt:6)
E/(10:39:33.630) KurobaEx | Chan: 	at com.github.k1rakishou.chan.ui.layout.ThreadListLayout.lambda$3AqWWKxdZ5kiL3VZ2oXj8gOP7GI(ThreadListLayout.kt:18)
E/(10:39:33.630) KurobaEx | Chan: 	at com.github.k1rakishou.chan.ui.layout.-$$Lambda$ThreadListLayout$3AqWWKxdZ5kiL3VZ2oXj8gOP7GI.run(lambda)
E/(10:39:33.630) KurobaEx | Chan: 	at android.os.Handler.handleCallback(Handler.java:739)
E/(10:39:33.630) KurobaEx | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/(10:39:33.630) KurobaEx | Chan: 	at android.os.Looper.loop(Looper.java:145)
E/(10:39:33.630) KurobaEx | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:6141)
E/(10:39:33.630) KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(10:39:33.630) KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Method.java:372)
E/(10:39:33.630) KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/(10:39:33.630) KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
E/(10:39:33.630) KurobaEx | Chan: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:95)


------------------------------
Android API Level: 21
App Version: v0.8.9.10581
Development Build: Release
Phone Model: samsung SM-A310F
------------------------------
Current layout mode: SLIDE
Board view mode: GRID
Prefetching enabled: false
Hi-res thumbnails enabled: false
CloudFlare force preload enabled: true
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 1024
diskCacheCleanupRemovePercent: 50
databasePostCachingEnabled: false
WEBM streaming enabled: true
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3ADownload%2F4chan
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: false
Foreground watcher enabled: true
Watch foreground interval: 30000
Watch foreground adaptive interval: false
Background watcher enabled: false
Filter watch enabled: false
------------------------------
```

**Comment by K1rakishou** [comment]
Crash report
UUID: e241bf1654475fea18c9416b11157d11
Build flavor: stable
Version name: v0.8.9
OS info: Android 5.0.2, sdk version: 21
Report description: No title
Logs:
```
=== LOGS(2021-05-31 21:57:02 UTC) ===
D/(00:56:46.398) KurobaEx | ControllerNavigationManager: onControllerPresented(PostRepliesPopupController)
D/(00:56:54.051) KurobaEx | PostingServiceDelegate: runPostWaitQueueLoop(TD{4chan/vg/337412517}) oldest enqueued reply descriptor: TD{4chan/vg/337412517}
D/(00:56:54.051) KurobaEx | LastReplyRepository: getTimeUntilNextThreadCreationOrReply(TD{4chan/vg/337412517}, ReplyModeSolveCaptchaManually)
D/(00:56:54.052) KurobaEx | LastReplyRepository: getTimeUntilReply(BD{4chan/vg}, ReplyModeSolveCaptchaManually) actualWaitTime=16970, currentPostingCooldownMs=47000, now=1622498214052, lastReplyTimeMs=1622498184022
D/(00:56:54.052) KurobaEx | PostingServiceDelegate: runPostWaitQueueLoop(TD{4chan/vg/337412517}) waiting 10000ms...
D/(00:57:00.530) KurobaEx | ControllerNavigationManager: onControllerPresented(FloatingListMenuController)
D/(00:57:01.052) KurobaEx | ControllerNavigationManager: onControllerUnpresented(FloatingListMenuController)
D/(00:57:01.066) KurobaEx | ControllerNavigationManager: onControllerUnpresented(PostRepliesPopupController)
E/(00:57:01.186) KurobaEx | Chan: Unhandled exception
E/(00:57:01.186) KurobaEx | Chan: java.lang.StringIndexOutOfBoundsException: length=33; index=-1
E/(00:57:01.186) KurobaEx | Chan: 	at java.lang.AbstractStringBuilder.indexAndLength(AbstractStringBuilder.java:207)
E/(00:57:01.186) KurobaEx | Chan: 	at java.lang.AbstractStringBuilder.insert0(AbstractStringBuilder.java:352)
E/(00:57:01.186) KurobaEx | Chan: 	at java.lang.StringBuilder.insert(StringBuilder.java:587)
E/(00:57:01.186) KurobaEx | Chan: 	at com.github.k1rakishou.chan.features.reply.ReplyPresenter$handleQuote$resultLength$1.invoke(ReplyPresenter.kt:26)
E/(00:57:01.186) KurobaEx | Chan: 	at com.github.k1rakishou.chan.core.manager.ReplyManager.readReply(ReplyManager.kt:2)
E/(00:57:01.186) KurobaEx | Chan: 	at com.github.k1rakishou.chan.features.reply.ReplyPresenter.handleQuote(ReplyPresenter.kt:4)
E/(00:57:01.186) KurobaEx | Chan: 	at com.github.k1rakishou.chan.ui.layout.-$$Lambda$ThreadLayout$EUH58bKLDCW8dF3YZMa7xomrwSg.run(lambda:9)
E/(00:57:01.186) KurobaEx | Chan: 	at android.os.Handler.handleCallback(Handler.java:739)
E/(00:57:01.186) KurobaEx | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/(00:57:01.186) KurobaEx | Chan: 	at android.os.Looper.loop(Looper.java:145)
E/(00:57:01.186) KurobaEx | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:6141)
E/(00:57:01.186) KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(00:57:01.186) KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Method.java:372)
E/(00:57:01.186) KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/(00:57:01.186) KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
E/(00:57:01.186) KurobaEx | Chan: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:95)


------------------------------
Android API Level: 21
App Version: v0.8.9.10581
Development Build: Release
Phone Model: samsung SM-A310F
------------------------------
Current layout mode: SLIDE
Board view mode: GRID
Prefetching enabled: false
Hi-res thumbnails enabled: false
CloudFlare force preload enabled: true
diskCacheSizeMegabytes: 512
prefetchDiskCacheSizeMegabytes: 1024
diskCacheCleanupRemovePercent: 75
databasePostCachingEnabled: false
WEBM streaming enabled: true
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3ADownload%2F4chan
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: false
Foreground watcher enabled: true
Watch foreground interval: 30000
Watch foreground adaptive interval: false
Background watcher enabled: false
Filter watch enabled: false
------------------------------
```

**Comment by K1rakishou** [comment]
Crash report
UUID: bdfe2f008c1d5d88968768e02729b20b
Build flavor: stable
Version name: v0.8.9
OS info: Android 11, sdk version: 30
Report description: No title
Logs:
```
=== LOGS(2021-05-29 15:49:48 UTC) ===
D/(12:49:47.337) KurobaEx | CaptchaHolder: Timer stopped
E/(12:49:47.831) KurobaEx | Chan: Unhandled exception
E/(12:49:47.831) KurobaEx | Chan: java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
E/(12:49:47.831) KurobaEx | Chan: 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1340)
E/(12:49:47.831) KurobaEx | Chan: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:694)
E/(12:49:47.831) KurobaEx | Chan: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:686)
E/(12:49:47.831) KurobaEx | Chan: 	at android.text.Selection.setSelection(Selection.java:94)
E/(12:49:47.831) KurobaEx | Chan: 	at android.text.Selection.setSelection(Selection.java:78)
E/(12:49:47.831) KurobaEx | Chan: 	at android.widget.EditText.setSelection(EditText.java:152)
E/(12:49:47.831) KurobaEx | Chan: 	at com.github.k1rakishou.chan.features.reply.ReplyLayout$restoreComment$1.invoke(ReplyLayout.kt:9)
E/(12:49:47.831) KurobaEx | Chan: 	at com.github.k1rakishou.chan.utils.KtExtensionsKt.doIgnoringTextWatcher(KtExtensions.kt:2)
E/(12:49:47.831) KurobaEx | Chan: 	at com.github.k1rakishou.chan.features.reply.ReplyLayout.restoreComment(ReplyLayout.kt:1)
E/(12:49:47.831) KurobaEx | Chan: 	at com.github.k1rakishou.chan.features.reply.ReplyPresenter.restoreComment(ReplyPresenter.kt:1)
E/(12:49:47.831) KurobaEx | Chan: 	at com.github.k1rakishou.chan.features.reply.ReplyLayout$onClick$1.invokeSuspend(ReplyLayout.kt:41)
E/(12:49:47.831) KurobaEx | Chan: 	at com.github.k1rakishou.chan.features.reply.ReplyLayout$onClick$1.invoke(ReplyLayout.kt:2)
E/(12:49:47.831) KurobaEx | Chan: 	at com.github.k1rakishou.chan.core.base.DebouncingCoroutineExecutor$1$1$1.invokeSuspend(DebouncingCoroutineExecutor.kt:19)
E/(12:49:47.831) KurobaEx | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/(12:49:47.831) KurobaEx | Chan: 	at android.support.v4.media.session.MediaSessionCompat.resume(MediaSessionCompat.java:10)
E/(12:49:47.831) KurobaEx | Chan: 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:18)
E/(12:49:47.831) KurobaEx | Chan: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:6)
E/(12:49:47.831) KurobaEx | Chan: 	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:3)
E/(12:49:47.831) KurobaEx | Chan: 	at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(Runnable.kt:1)
E/(12:49:47.831) KurobaEx | Chan: 	at android.os.Handler.handleCallback(Handler.java:938)
E/(12:49:47.831) KurobaEx | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/(12:49:47.831) KurobaEx | Chan: 	at android.os.Looper.loop(Looper.java:246)
E/(12:49:47.831) KurobaEx | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:8512)
E/(12:49:47.831) KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(12:49:47.831) KurobaEx | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/(12:49:47.831) KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)


------------------------------
Android API Level: 30
App Version: v0.8.9.10581
Development Build: Release
Phone Model: samsung SM-G970F
------------------------------
Current layout mode: SLIDE
Board view mode: LIST
Prefetching enabled: false
Hi-res thumbnails enabled: false
CloudFlare force preload enabled: false
diskCacheSizeMegabytes: 512
prefetchDiskCacheSizeMegabytes: 1024
diskCacheCleanupRemovePercent: 25
databasePostCachingEnabled: false
WEBM streaming enabled: false
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3AKuroba%2F4chan
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: true
Watch foreground interval: 60000
Watch foreground adaptive interval: false
Background watcher enabled: false
Filter watch enabled: false
------------------------------
```

**Comment by K1rakishou** [comment]
Crash report
UUID: 52c3c82ab6f765eadafa04340d08547b
Build flavor: stable
Version name: v0.8.9
OS info: Android 11, sdk version: 30
Report description: No title
Logs:
```
=== LOGS(2021-05-29 05:49:17 UTC) ===
D/(00:49:04.041) KurobaEx | ControllerNavigationManager: onControllerPresented(CaptchaContainerController)
D/(00:49:04.820) KurobaEx | CaptchaNoJsPresenterV2: Got new challenge
D/(00:49:07.570) KurobaEx | ControllerNavigationManager: onControllerUnpresented(CaptchaContainerController)
D/(00:49:12.690) KurobaEx | ControllerNavigationManager: onControllerPresented(FloatingListMenuController)
D/(00:49:13.169) KurobaEx | ControllerNavigationManager: onControllerUnpresented(FloatingListMenuController)
D/(00:49:14.373) KurobaEx | ControllerNavigationManager: onControllerPresented(FloatingListMenuController)
D/(00:49:14.864) KurobaEx | ControllerNavigationManager: onControllerUnpresented(FloatingListMenuController)
D/(00:49:16.349) KurobaEx | ControllerNavigationManager: onControllerPresented(FloatingListMenuController)
D/(00:49:16.950) KurobaEx | ControllerNavigationManager: onControllerUnpresented(FloatingListMenuController)
E/(00:49:17.059) KurobaEx | Chan: Unhandled exception
E/(00:49:17.059) KurobaEx | Chan: java.lang.IndexOutOfBoundsException: dstOffset -1
E/(00:49:17.059) KurobaEx | Chan: 	at java.lang.AbstractStringBuilder.insert(AbstractStringBuilder.java:1156)
E/(00:49:17.059) KurobaEx | Chan: 	at java.lang.StringBuilder.insert(StringBuilder.java:321)
E/(00:49:17.059) KurobaEx | Chan: 	at java.lang.StringBuilder.insert(StringBuilder.java:77)
E/(00:49:17.059) KurobaEx | Chan: 	at java.lang.AbstractStringBuilder.insert(AbstractStringBuilder.java:1104)
E/(00:49:17.059) KurobaEx | Chan: 	at java.lang.StringBuilder.insert(StringBuilder.java:310)
E/(00:49:17.059) KurobaEx | Chan: 	at com.github.k1rakishou.chan.features.reply.ReplyPresenter$handleQuote$resultLength$1.invoke(ReplyPresenter.kt:26)
E/(00:49:17.059) KurobaEx | Chan: 	at com.github.k1rakishou.chan.core.manager.ReplyManager.readReply(ReplyManager.kt:2)
E/(00:49:17.059) KurobaEx | Chan: 	at com.github.k1rakishou.chan.features.reply.ReplyPresenter.handleQuote(ReplyPresenter.kt:4)
E/(00:49:17.059) KurobaEx | Chan: 	at com.github.k1rakishou.chan.ui.layout.-$$Lambda$ThreadLayout$EUH58bKLDCW8dF3YZMa7xomrwSg.run(lambda:9)
E/(00:49:17.059) KurobaEx | Chan: 	at android.os.Handler.handleCallback(Handler.java:938)
E/(00:49:17.059) KurobaEx | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/(00:49:17.059) KurobaEx | Chan: 	at android.os.Looper.loop(Looper.java:233)
E/(00:49:17.059) KurobaEx | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:8010)
E/(00:49:17.059) KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(00:49:17.059) KurobaEx | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/(00:49:17.059) KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)


------------------------------
Android API Level: 30
App Version: v0.8.9.10581
Development Build: Release
Phone Model: OnePlus HD1905
------------------------------
Current layout mode: SLIDE
Board view mode: GRID
Prefetching enabled: false
Hi-res thumbnails enabled: false
CloudFlare force preload enabled: true
diskCacheSizeMegabytes: 512
prefetchDiskCacheSizeMegabytes: 1024
diskCacheCleanupRemovePercent: 25
databasePostCachingEnabled: false
WEBM streaming enabled: false
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3APictures%2F4chan
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: false
Foreground watcher enabled: true
Watch foreground interval: 30000
Watch foreground adaptive interval: true
Background watcher enabled: true
Watch background interval: 900000
Filter watch enabled: false
------------------------------
```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/58622cb8d8a3f6f0571840005a2c8a568d3cd8c2
