### ISSUE TITLE
Crash report "java.lang.IllegalStateException: Unable to create layer for ColorizableEditText"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#418]
Crash report
UUID: 0798364a1ff94234a73f714bf6144fe9
Build flavor: stable
Version name: v0.8.9
OS info: Android 6.0.1, sdk version: 23
Report description: No title
Logs:
```
=== LOGS(2021-05-23 19:02:14 UTC) ===
D/(22:01:59.803) KurobaEx | StartActivity: createUi took 464ms
D/(22:01:59.803) KurobaEx | UpdateManager: autoUpdateCheck()
D/(22:01:59.804) KurobaEx | StartActivity: initializeDependencies took 1.10ms
D/(22:01:59.804) KurobaEx | UpdateManager: runUpdateApi() manual=false
D/(22:01:59.805) KurobaEx | HistoryNavigationManager: notifyAllWaiters throwable==null: true, waiters=0
D/(22:01:59.806) KurobaEx | StartActivityIntentHandlerHelper: setupFromStateOrFreshLaunch(intent==null: false, savedInstanceState==null: true)
D/(22:01:59.806) KurobaEx | StartActivityIntentHandlerHelper: onNewIntentInternal() -> false
D/(22:01:59.806) KurobaEx | StartActivityIntentHandlerHelper: restoreFresh(allowedToOpenThread=true)
D/(22:01:59.806) KurobaEx | StartActivityIntentHandlerHelper: getBoardToOpen(), loadLastOpenedBoardUponAppStart=true
D/(22:01:59.807) KurobaEx | StartActivityIntentHandlerHelper: getThreadToOpen(), loadLastOpenedThreadUponAppStart=true
D/(22:01:59.807) KurobaEx | StartActivityIntentHandlerHelper: restoreFresh() getBoardToOpen returned BD{4chan/vt}, getThreadToOpen returned TD{4chan/vt/4065855}
D/(22:01:59.808) KurobaEx | BrowseController: showBoard(BD{4chan/vt}, false)
D/(22:01:59.808) KurobaEx | BrowseController: showBoardInternal(BD{4chan/vt}, false)
D/(22:01:59.808) KurobaEx | BrowseController: setBoard(BD{4chan/vt})
D/(22:01:59.808) KurobaEx | BrowseController: loadBoard(BD{4chan/vt})
D/(22:01:59.819) KurobaEx | ThreadPresenter: chanThreadTicker.startTicker(CD{4chan/vt})
D/(22:01:59.819) KurobaEx | ChanTicker: startTicker(CD{4chan/vt})
D/(22:01:59.819) KurobaEx | ChanTicker: kickTicker(false)
D/(22:01:59.819) KurobaEx | ChanTicker: kickTicker() called with catalog descriptor, ticking right away
D/(22:01:59.820) KurobaEx | StartActivity: onCreate() end isFreshStart: true
D/(22:01:59.821) KurobaEx | Chan: ^^^ App went foreground ^^^
D/(22:01:59.822) KurobaEx | ApplicationVisibilityManager: onEnteredForeground() callback execution took 203us, callbacks count: 3
D/(22:01:59.822) KurobaEx | StartActivity: start
D/(22:01:59.864) KurobaEx | BookmarksManager: persistBookmarks async called
D/(22:01:59.868) KurobaEx | ThreadBookmarkLocalSource: persist(44)
D/(22:01:59.874) KurobaEx | ControllerNavigationManager: onCloseAllNonMainControllers()
D/(22:01:59.874) KurobaEx | BrowseController: showThread(TD{4chan/vt/4065855}, false)
D/(22:01:59.875) KurobaEx | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(22:01:59.876) KurobaEx | BookmarksRepository: persist(44) took 6.95ms
D/(22:01:59.931) KurobaEx | ControllerNavigationManager: onControllerSwipedFrom(BrowseController)
D/(22:01:59.931) KurobaEx | ControllerNavigationManager: onControllerSwipedTo(ViewThreadController)
D/(22:01:59.931) KurobaEx | ViewThreadController: loadThread(TD{4chan/vt/4065855})
D/(22:01:59.932) KurobaEx | ThreadPresenter: chanThreadTicker.startTicker(TD{4chan/vt/4065855})
D/(22:01:59.932) KurobaEx | ChanTicker: startTicker(TD{4chan/vt/4065855})
D/(22:01:59.932) KurobaEx | ChanTicker: kickTicker(false)
D/(22:01:59.933) KurobaEx | ChanTicker: StopTicker
D/(22:02:00.020) KurobaEx | AppModuleAndroidUtils: waitForLayout requested a re-layout by returning false
D/(22:02:00.025) KurobaEx | BookmarksManager: subscriptions=4
D/(22:02:00.025) KurobaEx | BookmarksManager: persistBookmarks async finished
D/(22:02:00.026) KurobaEx | ChanTicker: StartOrResetTicker stopping previous job
D/(22:02:00.111) KurobaEx | BookmarkWatcherCoordinator: restartBackgroundWork() called tag=BookmarkWatcherController_Stable
D/(22:02:00.112) KurobaEx | BookmarkWatcherCoordinator: restartBackgroundWork() cannot restart watcher because one of the required settings is turned off (watchEnabled=true, watchBackground=false)
D/(22:02:00.112) KurobaEx | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Stable
D/(22:02:00.115) KurobaEx | FilterWatcherCoordinator: cancelFilterWatching() called tag=FilterWatcherController_Stable
D/(22:02:00.117) KurobaEx | ReplyNotificationsHelper: bookmarksManager.listenForBookmarksChanges(), bookmarkChange=BookmarksInitialized
D/(22:02:00.118) KurobaEx | BookmarkWatcherCoordinator: listenForBookmarksChanges bookmarkChange=com.github.k1rakishou.chan.core.manager.BookmarksManager$BookmarkChange$BookmarksInitialized@743e2ae
D/(22:02:00.119) KurobaEx | ChanTicker: StartOrResetTicker scheduled, waiting 0ms
D/(22:02:00.119) KurobaEx | ChanTicker: StartOrResetTicker run action begin
D/(22:02:00.120) KurobaEx | ThreadPresenter: onChanTickerTick(TD{4chan/vt/4065855})
D/(22:02:00.120) KurobaEx | ThreadPresenter: preloadThreadInfo(TD{4chan/vt/4065855}) begin
D/(22:02:00.153) KurobaEx | BookmarkWatcherCoordinator: onBookmarksChanged() watchBackground is false, stopping background watcher
D/(22:02:00.153) KurobaEx | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Stable
D/(22:02:00.153) KurobaEx | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Stable canceled
D/(22:02:00.154) KurobaEx | BookmarkWatcherCoordinator: restartBackgroundWork() called tag=BookmarkWatcherController_Stable
D/(22:02:00.154) KurobaEx | BookmarkWatcherCoordinator: restartBackgroundWork() cannot restart watcher because one of the required settings is turned off (watchEnabled=true, watchBackground=false)
D/(22:02:00.154) KurobaEx | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Stable
D/(22:02:00.160) KurobaEx | PostHideManager: chanPostHideRepository.preloadForThreadInternal() preloaded 0 post hides
D/(22:02:00.160) KurobaEx | FilterWatcherCoordinator: cancelFilterWatching() work with tag FilterWatcherController_Stable canceled
D/(22:02:00.162) KurobaEx | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Stable canceled
D/(22:02:00.162) KurobaEx | BookmarkWatcherCoordinator: onBookmarksChanged() calling startWatchingIfNotWatchingYet()
D/(22:02:00.163) KurobaEx | BookmarkForegroundWatcher: working == true, calling updateBookmarksWorkerLoop()
D/(22:02:00.163) KurobaEx | BookmarkWatcherCoordinator: restartBackgroundWork() called tag=BookmarkWatcherController_Stable
D/(22:02:00.163) KurobaEx | BookmarkWatcherCoordinator: restartBackgroundWork() cannot restart watcher because one of the required settings is turned off (watchEnabled=true, watchBackground=false)
D/(22:02:00.163) KurobaEx | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Stable
D/(22:02:00.167) KurobaEx | ThreadPresenter: preloadThreadInfo(TD{4chan/vt/4065855}) end
D/(22:02:00.169) KurobaEx | ThreadPresenter: normalLoad(currentChanDescriptor=TD{4chan/vt/4065855}, showLoading=false, chanCacheUpdateOptions=UpdateCache, chanLoadOptions=ChanLoadOptions(chanLoadOption=RetainAll), chanCacheOptions=ChanCacheOptions(options=[StoreEverywhere, CanAddInFrontOfTheMemoryCache]), chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(22:02:00.169) KurobaEx | ChanTicker: StartOrResetTicker run action end
D/(22:02:00.170) KurobaEx | ChanTicker: StartOrResetTicker done, nextTimeoutIndex=1, nextWaitTimeSeconds=20
D/(22:02:00.175) KurobaEx | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Stable canceled
D/(22:02:00.176) KurobaEx | BookmarkWatcherCoordinator: restartBackgroundWork() called tag=BookmarkWatcherController_Stable
D/(22:02:00.176) KurobaEx | BookmarkWatcherCoordinator: restartBackgroundWork() cannot restart watcher because one of the required settings is turned off (watchEnabled=true, watchBackground=false)
D/(22:02:00.176) KurobaEx | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Stable
D/(22:02:00.177) KurobaEx | ChanThreadManager: loadThreadOrCatalog(chanDescriptor=TD{4chan/vt/4065855}, chanCacheUpdateOptions=UpdateCache, ChanLoadOptions(chanLoadOption=RetainAll), ChanCacheOptions(options=[StoreEverywhere, CanAddInFrontOfTheMemoryCache]), ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(22:02:00.178) KurobaEx | ChanThreadManager: loadInternal() Requested thread /TD{4chan/vt/4065855}/
D/(22:02:00.178) KurobaEx | ChanThreadManager: loadInternal() chanThreadsCache.cacheNeedsUpdate(TD{4chan/vt/4065855}, UpdateCache) -> true
D/(22:02:00.179) KurobaEx | ChanThreadLoaderCoordinator: loadThreadOrCatalog(url=https://a.4cdn.org/vt/thread/4065855.json, chanDescriptor=TD{4chan/vt/4065855}, chanCacheOptions=ChanCacheOptions(options=[StoreEverywhere, CanAddInFrontOfTheMemoryCache]), chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647), chanReader=FutabaChanReader)
D/(22:02:00.179) KurobaEx | BookmarkWatcherCoordinator: onBookmarksChanged() watchBackground is false, stopping background watcher
D/(22:02:00.179) KurobaEx | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Stable
D/(22:02:00.180) KurobaEx | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Stable canceled
D/(22:02:00.180) KurobaEx | BookmarkWatcherDelegate: awaitUntilAllDependenciesAreReady()...
D/(22:02:00.180) KurobaEx | BookmarkWatcherDelegate: awaitUntilAllDependenciesAreReady()...done
D/(22:02:00.181) KurobaEx | LastPageNotificationsHelper: showOrUpdateNotifications(5)
D/(22:02:00.181) KurobaEx | LastPageNotificationsHelper: ChanSettings.watchLastPageNotify is disabled
D/(22:02:00.182) KurobaEx | BookmarkWatcherDelegate: BookmarkWatcherDelegate.doWork() called, isCalledFromForeground=true, currentThreadDescriptor=TD{4chan/vt/4065855}
D/(22:02:00.182) KurobaEx | FetchThreadBookmarkInfoUseCase: FetchThreadBookmarkInfoUseCase.execute(5)
D/(22:02:00.195) KurobaEx | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Stable canceled
D/(22:02:00.203) KurobaEx | ProxyStorage: loadProxies()
D/(22:02:00.203) KurobaEx | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(22:02:00.203) KurobaEx | ProxyStorage: proxiesFile does not exist, nothing to load
D/(22:02:00.203) KurobaEx | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(22:02:00.204) KurobaEx | CompositeDnsSelector: lookup okHttpUseDnsOverHttps: false
D/(22:02:00.204) KurobaEx | CompositeDnsSelector: lookup okHttpUseDnsOverHttps: false
D/(22:02:00.204) KurobaEx | Dependency Injection: NormalDnsSelectorFactory created
D/(22:02:00.204) KurobaEx | Dependency Injection: NormalDnsSelectorFactory created
D/(22:02:00.204) KurobaEx | Dependency Injection: Using DnsSelector.Mode.IPV4_ONLY
D/(22:02:00.204) KurobaEx | Dependency Injection: Using DnsSelector.Mode.IPV4_ONLY
D/(22:02:00.208) KurobaEx | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Stable canceled
D/(22:02:00.208) KurobaEx | BookmarkWatcherCoordinator: onBookmarksChanged() calling startWatchingIfNotWatchingYet()
D/(22:02:00.260) KurobaEx | HistoryNavigationManager: notifyAllWaiters throwable==null: true, waiters=0
D/(22:02:00.263) KurobaEx | PageRequestManager: Requesting new board pages for /g/
D/(22:02:00.270) KurobaEx | PageRequestManager: Requesting new board pages for /v/
D/(22:02:00.273) KurobaEx | PageRequestManager: Requesting new board pages for /gif/
D/(22:02:00.275) KurobaEx | PageRequestManager: Requesting new board pages for /vt/
D/(22:02:00.291) KurobaEx | CompositeDnsSelector: lookup okHttpUseDnsOverHttps: false
D/(22:02:00.291) KurobaEx | Dependency Injection: NormalDnsSelectorFactory created
D/(22:02:00.291) KurobaEx | Dependency Injection: Using DnsSelector.Mode.IPV4_ONLY
D/(22:02:00.897) KurobaEx | JsonReaderRequest: Request "Chan4PagesRequest" to "https://a.4cdn.org/g/threads.json" took 630.932343ms
D/(22:02:00.910) KurobaEx | PageRequestManager: Got pages for 4chan/g/
D/(22:02:00.955) KurobaEx | JsonReaderRequest: Request "Chan4PagesRequest" to "https://a.4cdn.org/vt/threads.json" took 679.664792ms
D/(22:02:00.957) KurobaEx | JsonReaderRequest: Request "Chan4PagesRequest" to "https://a.4cdn.org/gif/threads.json" took 679.112916ms
D/(22:02:00.959) KurobaEx | JsonReaderRequest: Request "Chan4PagesRequest" to "https://a.4cdn.org/v/threads.json" took 688.58453ms
D/(22:02:00.961) KurobaEx | PageRequestManager: Got pages for 4chan/gif/
D/(22:02:00.967) KurobaEx | PageRequestManager: Got pages for 4chan/vt/
D/(22:02:00.970) KurobaEx | PageRequestManager: Got pages for 4chan/v/
D/(22:02:01.027) KurobaEx | ThreadPresenter: onChanTickerTick(CD{4chan/vt})
D/(22:02:01.028) KurobaEx | ThreadPresenter: preloadCatalogInfo(CD{4chan/vt}) begin
D/(22:02:01.042) KurobaEx | PostHideManager: chanPostHideRepository.preloadForCatalogInternal() preloaded 0 post hides
D/(22:02:01.064) KurobaEx | ThreadPresenter: preloadCatalogInfo(CD{4chan/vt}) end
D/(22:02:01.064) KurobaEx | ThreadPresenter: normalLoad(currentChanDescriptor=CD{4chan/vt}, showLoading=false, chanCacheUpdateOptions=UpdateCache, chanLoadOptions=ChanLoadOptions(chanLoadOption=RetainAll), chanCacheOptions=ChanCacheOptions(options=[StoreEverywhere, CanAddInFrontOfTheMemoryCache]), chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(22:02:01.064) KurobaEx | ChanThreadManager: loadThreadOrCatalog(chanDescriptor=CD{4chan/vt}, chanCacheUpdateOptions=UpdateCache, ChanLoadOptions(chanLoadOption=RetainAll), ChanCacheOptions(options=[StoreEverywhere, CanAddInFrontOfTheMemoryCache]), ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(22:02:01.064) KurobaEx | ChanThreadManager: loadInternal() Requested catalog /CD{4chan/vt}/
D/(22:02:01.064) KurobaEx | ChanThreadManager: loadInternal() chanThreadsCache.cacheNeedsUpdate(CD{4chan/vt}, UpdateCache) -> true
D/(22:02:01.065) KurobaEx | ChanThreadLoaderCoordinator: loadThreadOrCatalog(url=https://a.4cdn.org/vt/catalog.json, chanDescriptor=CD{4chan/vt}, chanCacheOptions=ChanCacheOptions(options=[StoreEverywhere, CanAddInFrontOfTheMemoryCache]), chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647), chanReader=FutabaChanReader)
D/(22:02:01.161) KurobaEx | FilterWatcherCoordinator: restartFilterWatcherWithTinyDelay() no watch filters found, canceling the work
D/(22:02:01.161) KurobaEx | FilterWatcherCoordinator: cancelFilterWatching() called tag=FilterWatcherController_Stable
D/(22:02:01.162) KurobaEx | ReplyNotificationsHelper: showNotificationForReplies(0)
D/(22:02:01.162) KurobaEx | ReplyNotificationsHelper: showNotificationForReplies() unreadNotificationsGrouped are empty
D/(22:02:01.164) KurobaEx | ReplyNotificationsHelper: closeAllNotifications() closed REPLIES_PRE_OREO_NOTIFICATION_ID notification
D/(22:02:01.170) KurobaEx | ControllerNavigationManager: onCloseAllNonMainControllers()
D/(22:02:01.243) KurobaEx | screensBuiltOnce: SuspendableInitializer initWithValue() called
D/(22:02:01.243) KurobaEx | screensBuiltOnce: notifyAllWaiters throwable==null: true, waiters=0
D/(22:02:01.244) KurobaEx | screensBuiltOnce: SuspendableInitializer initWithValue() done
D/(22:02:01.246) KurobaEx | ControllerNavigationManager: onControllerPushed(MainSettingsControllerV2)
D/(22:02:01.265) KurobaEx | FilterWatcherCoordinator: cancelFilterWatching() work with tag FilterWatcherController_Stable canceled
D/(22:02:01.307) KurobaEx | HistoryNavigationManager: notifyAllWaiters throwable==null: true, waiters=0
D/(22:02:01.461) KurobaEx | screensBuiltOnce: notifyAllWaiters throwable==null: true, waiters=0
D/(22:02:01.473) KurobaEx | screensBuiltOnce: SuspendableInitializer initWithValue() called
D/(22:02:01.473) KurobaEx | screensBuiltOnce: SuspendableInitializer initWithValue() already completed, exiting
D/(22:02:01.605) KurobaEx | BookmarkWatcherDelegate: fetchThreadBookmarkInfo stats: total results=5, errorsCount=0, alreadyDeletedCount=0, notFoundOnServerCount=0, badStatusCount=0, successCount=5
D/(22:02:01.692) KurobaEx | BookmarksManager: persistBookmarksManually() persistBookmarksInternal called
D/(22:02:01.693) KurobaEx | ReplyNotificationsHelper: bookmarksManager.listenForBookmarksChanges(), bookmarkChange=BookmarksUpdated
D/(22:02:01.693) KurobaEx | BookmarkWatcherCoordinator: listenForBookmarksChanges bookmarkChange=com.github.k1rakishou.chan.core.manager.BookmarksManager$BookmarkChange$BookmarksUpdated@1b3a0b6
D/(22:02:01.695) KurobaEx | ThreadBookmarkLocalSource: persist(44)
D/(22:02:01.727) KurobaEx | ThreadBookmarkLocalSource: persist() toInsertOrUpdateBookmarkReplyEntities: 0, toInsertOrUpdateThreadBookmarkEntities: 1
D/(22:02:01.727) KurobaEx | ThreadBookmarkLocalSource: persist() inserted/updated 1 bookmarks, deleted 0 bookmarks
D/(22:02:01.727) KurobaEx | BookmarksRepository: persist(44) took 32.0ms
D/(22:02:01.733) KurobaEx | BookmarksManager: persistBookmarksManually() persistBookmarksInternal finished
D/(22:02:01.734) KurobaEx | ReplyNotificationsHelper: bookmarksManager.listenForBookmarksChanges(), bookmarkChange=BookmarksUpdated
D/(22:02:01.734) KurobaEx | BookmarkWatcherDelegate: BookmarkWatcherDelegate.doWork() success, activeBookmarksCount=5
D/(22:02:01.734) KurobaEx | BookmarkWatcherCoordinator: listenForBookmarksChanges bookmarkChange=com.github.k1rakishou.chan.core.manager.BookmarksManager$BookmarkChange$BookmarksUpdated@4627d24
D/(22:02:01.734) KurobaEx | BookmarkWatcherDelegate: BookmarkWatcherDelegate.doWork() took 1.55s
D/(22:02:01.754) KurobaEx | ParsePostsUseCase: Thread count: 4
D/(22:02:01.755) KurobaEx | NormalPostLoader: persistPosts(TD{4chan/vt/4065855}, ChanReaderProcessor{chanDescriptor=TD{4chan/vt/4065855}, toParse=278}, ChanCacheOptions(options=[StoreEverywhere, CanAddInFrontOfTheMemoryCache]), DefaultPostParser)
D/(22:02:01.757) KurobaEx | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=TD{4chan/vt/4065855}, postsToParseSize=278), internalIds=278, boardDescriptors=79, filters=0
D/(22:02:02.238) KurobaEx | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=TD{4chan/vt/4065855}) -> parsedPosts=278
D/(22:02:02.242) KurobaEx | ChanPostRepository: insertOrUpdateThreadPosts() 278 posts differ from the cache (total posts=278)
D/(22:02:02.249) KurobaEx | ChanThread: Thread cache (TD{4chan/vt/4065855}) Added 278 new posts, updated 0 posts
D/(22:02:02.250) KurobaEx | ChanPostRepository: insertOrUpdateMany(TD{4chan/vt/4065855}) -> 278
D/(22:02:02.257) KurobaEx | ChanThreadLoaderCoordinator: ChanReaderRequest.readJson() stats:
D/(22:02:02.257) KurobaEx | ChanThreadLoaderCoordinator: url = https://a.4cdn.org/vt/thread/4065855.json.
D/(22:02:02.257) KurobaEx | ChanThreadLoaderCoordinator: Network request execution took 1.39s.
D/(22:02:02.257) KurobaEx | ChanThreadLoaderCoordinator: Json reading took 185ms.
D/(22:02:02.257) KurobaEx | ChanThreadLoaderCoordinator: Store new posts took 12.3ms (stored 278 posts).
D/(22:02:02.257) KurobaEx | ChanThreadLoaderCoordinator: Parse posts took = 483ms, (parsed 278 out of 278 posts).
D/(22:02:02.257) KurobaEx | ChanThreadLoaderCoordinator: Total in-memory cached posts count = 278/10240.
D/(22:02:02.257) KurobaEx | ChanThreadLoaderCoordinator: Current thread cached posts count = 278
D/(22:02:02.257) KurobaEx | ChanThreadLoaderCoordinator: Threads with more than one post count = (1/8), total cached threads count = 1.
D/(22:02:02.257) KurobaEx | ChanThreadLoaderCoordinator: fullLocalDuration=681ms, fullGlobalDuration=2.07s
D/(22:02:02.257) KurobaEx | ThreadPresenter: normalLoad() threadLoadResult=ThreadLoadResult.Loaded{chanDescriptor=TD{4chan/vt/4065855}}
D/(22:02:02.258) KurobaEx | ThreadPresenter: onChanLoaderData() called, loadedChanDescriptor=TD{4chan/vt/4065855}
D/(22:02:02.259) KurobaEx | ChanTicker: kickTicker(false)
D/(22:02:02.263) KurobaEx | ChanTicker: StartOrResetTicker stopping previous job
D/(22:02:02.271) KurobaEx | ChanTicker: StartOrResetTicker scheduled, waiting 20000ms
D/(22:02:02.272) KurobaEx | filesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(22:02:02.272) KurobaEx | filesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(22:02:02.272) KurobaEx | filesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(22:02:02.293) KurobaEx | PostsFilter: originalPosts.size=278, retainedPosts.size=278, chanDescriptor=TD{4chan/vt/4065855}
D/(22:02:02.306) KurobaEx | PostingServiceDelegate: listenForPostingStatusUpdates(TD{4chan/vt/4065855})
D/(22:02:02.308) KurobaEx | ReplyPresenter: processPostingStatusUpdates(TD{4chan/vt/4065855}) -> Attached
D/(22:02:02.471) KurobaEx | PostAdapter: setThread() notifyDataSetChanged called, postIndexedList.size=278
D/(22:02:02.498) KurobaEx | NormalPostLoader: persistPosts(CD{4chan/vt}, ChanReaderProcessor{chanDescriptor=CD{4chan/vt}, toParse=151}, ChanCacheOptions(options=[StoreEverywhere, CanAddInFrontOfTheMemoryCache]), DefaultPostParser)
D/(22:02:02.498) KurobaEx | ChanCatalogSnapshotRepository: storeChanCatalogSnapshot(ChanCatalogSnapshot{boardDescriptor=BD{4chan/vt}, chanCatalogSnapshotEntryList=151})
D/(22:02:02.522) KurobaEx | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=CD{4chan/vt}, postsToParseSize=151), internalIds=151, boardDescriptors=0, filters=0
D/(22:02:02.841) KurobaEx | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=CD{4chan/vt}) -> parsedPosts=151
D/(22:02:02.849) KurobaEx | ChanPostRepository: insertOrUpdateMany(CD{4chan/vt}) -> 151
D/(22:02:02.854) KurobaEx | ChanThreadLoaderCoordinator: ChanReaderRequest.readJson() stats:
D/(22:02:02.854) KurobaEx | ChanThreadLoaderCoordinator: url = https://a.4cdn.org/vt/catalog.json.
D/(22:02:02.854) KurobaEx | ChanThreadLoaderCoordinator: Network request execution took 1.21s.
D/(22:02:02.854) KurobaEx | ChanThreadLoaderCoordinator: Json reading took 221ms.
D/(22:02:02.854) KurobaEx | ChanThreadLoaderCoordinator: Store new posts took 10.1ms (stored 151 posts).
D/(22:02:02.854) KurobaEx | ChanThreadLoaderCoordinator: Parse posts took = 319ms, (parsed 151 out of 151 posts).
D/(22:02:02.854) KurobaEx | ChanThreadLoaderCoordinator: Total in-memory cached posts count = 428/10240.
D/(22:02:02.854) KurobaEx | ChanThreadLoaderCoordinator: Threads with more than one post count = (1/8), total cached threads count = 151.
D/(22:02:02.854) KurobaEx | ChanThreadLoaderCoordinator: fullLocalDuration=550ms, fullGlobalDuration=1.76s
D/(22:02:02.868) KurobaEx | ReplyNotificationsHelper: showNotificationForReplies(0)
D/(22:02:02.868) KurobaEx | ReplyNotificationsHelper: showNotificationForReplies() unreadNotificationsGrouped are empty
D/(22:02:02.869) KurobaEx | ReplyNotificationsHelper: closeAllNotifications() closed REPLIES_PRE_OREO_NOTIFICATION_ID notification
D/(22:02:02.884) KurobaEx | ThreadPresenter: normalLoad() threadLoadResult=ThreadLoadResult.Loaded{chanDescriptor=CD{4chan/vt}}
D/(22:02:02.884) KurobaEx | ThreadPresenter: onChanLoaderData() called, loadedChanDescriptor=CD{4chan/vt}
D/(22:02:02.939) KurobaEx | PostsFilter: originalPosts.size=151, retainedPosts.size=151, chanDescriptor=CD{4chan/vt}
D/(22:02:02.949) KurobaEx | PostingServiceDelegate: listenForPostingStatusUpdates(CD{4chan/vt})
D/(22:02:02.949) KurobaEx | ReplyPresenter: processPostingStatusUpdates(CD{4chan/vt}) -> Attached
D/(22:02:03.034) KurobaEx | HistoryNavigationManager: notifyAllWaiters throwable==null: true, waiters=0
D/(22:02:03.106) KurobaEx | PostAdapter: setThread() notifyDataSetChanged called, postIndexedList.size=151
D/(22:02:04.122) KurobaEx | Dependency Injection: NormalDnsSelectorFactory created
D/(22:02:04.124) KurobaEx | Dependency Injection: Using DnsSelector.Mode.IPV4_ONLY
D/(22:02:04.124) KurobaEx | CompositeDnsSelector: lookup okHttpUseDnsOverHttps: false
D/(22:02:04.397) KurobaEx | CompositeDnsSelector: lookup okHttpUseDnsOverHttps: false
D/(22:02:04.397) KurobaEx | Dependency Injection: NormalDnsSelectorFactory created
D/(22:02:04.397) KurobaEx | Dependency Injection: Using DnsSelector.Mode.IPV4_ONLY
E/(22:02:13.862) KurobaEx | Chan: Unhandled exception
E/(22:02:13.862) KurobaEx | Chan: java.lang.IllegalStateException: Unable to create layer for ColorizableEditText
E/(22:02:13.862) KurobaEx | Chan: 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/(22:02:13.862) KurobaEx | Chan: 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/(22:02:13.862) KurobaEx | Chan: 	at android.os.Looper.loop(Looper.java:143)
E/(22:02:13.862) KurobaEx | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:7225)
E/(22:02:13.862) KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(22:02:13.862) KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/(22:02:13.862) KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


------------------------------
Android API Level: 23
App Version: v0.8.9.10581
Development Build: Release
Phone Model: samsung SM-G9006V
------------------------------
Current layout mode: SLIDE
Board view mode: GRID
Prefetching enabled: false
Hi-res thumbnails enabled: false
CloudFlare force preload enabled: true
diskCacheSizeMegabytes: 512
prefetchDiskCacheSizeMegabytes: 1024
diskCacheCleanupRemovePercent: 25
databasePostCachingEnabled: false
WEBM streaming enabled: true
ImageSaver root directory: content://com.android.externalstorage.documents/tree/2030-1C16%3Akuroba
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: true
Watch foreground interval: 60000
Watch foreground adaptive interval: false
Background watcher enabled: false
Filter watch enabled: false
------------------------------
```

**Comment by K1rakishou** [comment]
TBH I have no idea why these happen and googling doesn't really help. It says that it is some kind of a transition issue but I don't even use transitions.  Nothing I can really do here. I'm just gonna close it and forget about it.
