### ISSUE TITLE
Report "Playing video"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#454]
UUID: 79eb68cc2f975d6130ddfea325916c9f
Build flavor: stable
Version name: v0.9.6
OS info: Android 10, sdk version: 29
Report description: Sometimes video wont play, it just show this error:

Decoder init failed: OMX.Exynos.vp8.dec, Format(1, null, null, video/x-vnd.on2.vp8, null, -1, und, [1280, 720, -1.0], [-1, -1])

Need to exit and open the video again to make it works.
Logs:
```
D/(21:38:53.886) KurobaEx | MediaViewerAdapter: doBind(position: 13)
D/(21:38:53.887) KurobaEx | MediaView: onHide(14/15, Remote(urlRaw=https://i.4cdn.org/gif/1624455348442.webm))
D/(21:38:53.889) KurobaEx | MediaView: onShow(13/15, Remote(urlRaw=https://i.4cdn.org/gif/1624454720611.webm))
D/(21:38:53.889) KurobaEx | MediaViewerAdapter: doBind(position: 13), loadedViewsCount=3, boundCount=3, showCount=1
D/(21:38:54.030) KurobaEx | ChanThreadViewableInfoLocalSource: Updating ChanThreadViewableInfo for TD{4chan/gif/20233019}
D/(21:38:54.215) KurobaEx | MediaView: startPreloading(11/15, Remote(urlRaw=https://i.4cdn.org/gif/1624452017295.webm))
D/(21:38:54.241) KurobaEx | ExoPlayerWrapper: getOrCreateExoPlayer() creating a new player, total players count: 4
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: preload() error
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/x-vnd.on2.vp8, null, -1, und, [1920, 1080, -1.0], [-1, -1]), format_supported=YES
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:51)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at android.os.Looper.loop(Looper.java:237)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.vp8.dec, Format(1, null, null, video/x-vnd.on2.vp8, null, -1, und, [1920, 1080, -1.0], [-1, -1])
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:22)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:33)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:11)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:1)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:4)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:7)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:138)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:31)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	... 3 more
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at android.media.MediaCodec.native_configure(Native Method)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at android.media.MediaCodec.configure(MediaCodec.java:2023)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at android.media.MediaCodec.configure(MediaCodec.java:1951)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:3)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:17)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:14)
E/(21:38:54.325) KurobaEx | ExoPlayerWrapper: 	... 10 more
D/(21:38:54.594) KurobaEx | MediaViewerAdapter: doBind(position: 14)
D/(21:38:54.595) KurobaEx | MediaView: onHide(13/15, Remote(urlRaw=https://i.4cdn.org/gif/1624454720611.webm))
D/(21:38:54.596) KurobaEx | MediaView: onShow(14/15, Remote(urlRaw=https://i.4cdn.org/gif/1624455348442.webm))
D/(21:38:54.596) KurobaEx | MediaViewerAdapter: doBind(position: 14), loadedViewsCount=4, boundCount=3, showCount=1
D/(21:38:54.728) KurobaEx | ChanThreadViewableInfoLocalSource: Updating ChanThreadViewableInfo for TD{4chan/gif/20233019}
D/(21:38:55.000) KurobaEx | MediaView: onUnbind(11/15, Remote(urlRaw=https://i.4cdn.org/gif/1624452017295.webm))
D/(21:38:55.000) KurobaEx | MediaViewerAdapter: destroyItem(position: 11), loadedViewsCount=3, boundCount=3, showCount=1
D/(21:38:58.717) KurobaEx | MediaView: onHide(14/15, Remote(urlRaw=https://i.4cdn.org/gif/1624455348442.webm))
D/(21:38:58.793) KurobaEx | MediaViewerAdapter: onDestroy()
D/(21:38:58.794) KurobaEx | MediaView: onUnbind(14/15, Remote(urlRaw=https://i.4cdn.org/gif/1624455348442.webm))
D/(21:38:58.795) KurobaEx | MediaView: onUnbind(13/15, Remote(urlRaw=https://i.4cdn.org/gif/1624454720611.webm))
D/(21:38:58.795) KurobaEx | MediaView: onUnbind(12/15, Remote(urlRaw=https://i.4cdn.org/gif/1624453066432.webm))
D/(21:38:58.796) KurobaEx | MediaView: onUnbind(12/15, Remote(urlRaw=https://i.4cdn.org/gif/1624453066432.webm))
D/(21:38:58.796) KurobaEx | MediaViewerAdapter: destroyItem(position: 12), loadedViewsCount=0, boundCount=0, showCount=0
D/(21:38:58.796) KurobaEx | MediaView: onUnbind(13/15, Remote(urlRaw=https://i.4cdn.org/gif/1624454720611.webm))
D/(21:38:58.797) KurobaEx | MediaViewerAdapter: destroyItem(position: 13), loadedViewsCount=0, boundCount=0, showCount=0
D/(21:38:58.797) KurobaEx | MediaView: onUnbind(14/15, Remote(urlRaw=https://i.4cdn.org/gif/1624455348442.webm))
D/(21:38:58.798) KurobaEx | MediaViewerAdapter: destroyItem(position: 14), loadedViewsCount=0, boundCount=0, showCount=0
D/(21:38:58.798) KurobaEx | ExoPlayerWrapper: releaseAll() releasing 1 / 4 player
D/(21:38:58.831) KurobaEx | ExoPlayerWrapper: releaseAll() releasing 2 / 4 player
D/(21:38:58.840) KurobaEx | ExoPlayerWrapper: releaseAll() releasing 3 / 4 player
D/(21:38:58.842) KurobaEx | ExoPlayerWrapper: releaseAll() releasing 4 / 4 player
D/(21:39:01.621) KurobaEx | ControllerNavigationManager: onControllerSwipedFrom(ViewThreadController)
D/(21:39:01.622) KurobaEx | ControllerNavigationManager: onControllerSwipedTo(BrowseController)
D/(21:39:01.736) KurobaEx | HistoryNavigationManager: notifyAllWaiters throwable==null: true, waiters=0
D/(21:39:02.627) KurobaEx | HistoryNavigationManager: persistNavigationStack async called
D/(21:39:02.674) KurobaEx | HistoryNavigationRepository: persist(84) took 39.8ms
D/(21:39:02.677) KurobaEx | HistoryNavigationManager: persistNavigationStack async finished
D/(21:39:04.874) KurobaEx | ControllerNavigationManager: onControllerPresented(FloatingListMenuController)
D/(21:39:05.862) KurobaEx | ControllerNavigationManager: onControllerUnpresented(FloatingListMenuController)
D/(21:39:06.344) KurobaEx | ControllerNavigationManager: onCloseAllNonMainControllers()
D/(21:39:06.395) KurobaEx | screensBuiltOnce: SuspendableInitializer initWithValue() called
D/(21:39:06.395) KurobaEx | screensBuiltOnce: notifyAllWaiters throwable==null: true, waiters=0
D/(21:39:06.395) KurobaEx | screensBuiltOnce: SuspendableInitializer initWithValue() done
D/(21:39:06.395) KurobaEx | ControllerNavigationManager: onControllerPushed(MainSettingsControllerV2)
D/(21:39:06.502) KurobaEx | screensBuiltOnce: notifyAllWaiters throwable==null: true, waiters=0
D/(21:39:06.508) KurobaEx | screensBuiltOnce: SuspendableInitializer initWithValue() called
D/(21:39:06.508) KurobaEx | screensBuiltOnce: SuspendableInitializer initWithValue() already completed, exiting
------------------------------
Android API Level: 29
App Version: v0.9.6.11917
Development Build: Release
Phone Model: samsung SM-A205F
------------------------------
Current layout mode: SLIDE
Board view mode: GRID
Prefetching enabled: false
Hi-res thumbnails enabled: false
CloudFlare force preload enabled: false
diskCacheSizeMegabytes: 512
prefetchDiskCacheSizeMegabytes: 1024
diskCacheCleanupRemovePercent: 25
databasePostCachingEnabled: false
ImageSaver root directory: content://com.android.externalstorage.documents/tree/3930-6232%3AKuroba
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: false
Background watcher enabled: false
Filter watch enabled: false
------------------------------
```

**Comment by K1rakishou** [comment]
This seems like a bug in vendor video codecs. I doubt that I will be able to fix it.

**Comment by Pentaphon** [comment]
> This seems like a bug in vendor video codes. I doubt that I will be able to fix it.

Not sure about this.  I saw it on a Snapdragon 460 device  running Android 10 and now this device which has an Exynos chip on Android 10. I guess it's possible for Samsung and Qualcomm to have the same "decoder init failed" bug but I'm not sure of those odds. Here's my report so users can connect the two. Maybe it's something that can be solved upstream on Exoplayer? 

https://github.com/K1rakishou/Kuroba-Experimental/issues/443

Edit: the video I had an issue with works fine on mpv-android. I suspect the person who reported this bug will also experience the same result.

**Comment by Pentaphon** [comment]
Just tried my sample file on the Exoplayer-based Justplayer and I get the exact same error. I've reported it to the Exoplayer devs at https://github.com/google/ExoPlayer/issues/9103

**Comment by K1rakishou** [comment]
>I've reported it to the Exoplayer devs at

That's good but if it's actually a bug in codecs then I doubt they will be able to fix this. By the way, IIRC mpv uses ffmpeg which doesn't use platform codecs and that's probably why it can play it. The downside is the apk size because of ffmpeg.

**Comment by K1rakishou** [comment]
swiping through certain webms
UUID: 840891a2c5fb1abec19cc71205787505
Build flavor: stable
Version name: v0.9.6
OS info: Android 10, sdk version: 29
Report description: I'm getting an error message when swiping through several consecutive webms in a thread. It only seems to happen with certain webms. I've tried swiping very fast but I can't seem to pinpoint exactly what triggers it.
This is a screenshot of the error message: https://i.imgur.com/R1qodeh.png

**Comment by Pentaphon** [comment]
@K1rakishou one of the Exoplayer contributors mentioned one of the lines in the KurobaEx log I referred him to. You may want to take a look at his comment here. 

https://github.com/google/ExoPlayer/issues/9103#issuecomment-873136802
