### ISSUE TITLE
Report "Swiping from bookmarks to filter watches crashes the app"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#473]
UUID: cd424cf5b3d63caa18173f796f30b72c
Build flavor: stable
Version name: v0.10.5
OS info: Android 11, sdk version: 30
Report description: Just swipe between bookmark and filter watches quickly and the app crashes

**Comment by K1rakishou** [comment]
This one is about calling requireNavController() in the SavedPostsController.onDestroy()l.

**Comment by K1rakishou** [comment]
```
E/(03:32:06.976) KurobaEx | Chan: Unhandled exception
E/(03:32:06.976) KurobaEx | Chan: java.lang.IllegalArgumentException: navigationController was not set
E/(03:32:06.976) KurobaEx | Chan: 	at com.github.k1rakishou.chan.controller.Controller.requireNavController(Controller.kt:1)
E/(03:32:06.976) KurobaEx | Chan: 	at com.github.k1rakishou.chan.controller.Controller.requireToolbarNavController(Controller.kt:1)
E/(03:32:06.976) KurobaEx | Chan: 	at com.github.k1rakishou.chan.features.my_posts.SavedPostsController.onDestroy(SavedPostsController.kt:2)
E/(03:32:06.976) KurobaEx | Chan: 	at com.github.k1rakishou.chan.controller.Controller.removeChildController(Controller.kt:1)
E/(03:32:06.976) KurobaEx | Chan: 	at com.github.k1rakishou.chan.ui.controller.navigation.TabHostController$ControllerAdapter.destroyItem(TabHostController.kt:2)
E/(03:32:06.976) KurobaEx | Chan: 	at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:25)
E/(03:32:06.976) KurobaEx | Chan: 	at androidx.viewpager.widget.ViewPager$3.run(ViewPager.java:3)
E/(03:32:06.976) KurobaEx | Chan: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
E/(03:32:06.976) KurobaEx | Chan: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
E/(03:32:06.976) KurobaEx | Chan: 	at android.view.Choreographer.doFrame(Choreographer.java:727)
E/(03:32:06.976) KurobaEx | Chan: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
E/(03:32:06.976) KurobaEx | Chan: 	at android.os.Handler.handleCallback(Handler.java:938)
E/(03:32:06.976) KurobaEx | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/(03:32:06.976) KurobaEx | Chan: 	at android.os.Looper.loop(Looper.java:223)
E/(03:32:06.976) KurobaEx | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/(03:32:06.976) KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(03:32:06.976) KurobaEx | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/(03:32:06.976) KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/0160fcc361e1e7707784533ff96d68a0fc5b4606
