### ISSUE TITLE
Crash report "java.lang.IllegalStateException: BoardManager is not ready yet! Use awaitUntilInitialized()"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#544]
Crash report
UUID: 9294d50efc7ed204a9fbeac9cb7d63dd
Build flavor: beta
Version name: v0.12.2
OS info: Android 11, sdk version: 30
Report description: No title
Logs:
```
=== LOGS(2021-09-02 04:54:58 UTC) ===
D/(11:54:57.665) KurobaEx-beta | AppModuleAndroidUtils: Signature hash: 86242978CF53C34361A8C962D0A57107AEB70E10631AE13EB5B006C0CF673FA9
D/(11:54:57.703) KurobaEx-beta | Chan: maxPostsCountInPostsCache: 13107
D/(11:54:57.703) KurobaEx-beta | Chan: maxAmountOfPostsInDatabase: 125000
D/(11:54:57.703) KurobaEx-beta | Chan: maxAmountOfThreadsInDatabase: 12500
D/(11:54:57.703) KurobaEx-beta | Chan: diskCacheCleanupRemovePercent: 25
D/(11:54:57.703) KurobaEx-beta | Chan: userAgent: Mozilla/5.0 (Linux; Android 11; POCO F1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.127 Mobile Safari/537.36
D/(11:54:57.703) KurobaEx-beta | Chan: kurobaExUserAgent: KurobaEx-beta v0.12.2.15499
D/(11:54:57.703) KurobaEx-beta | Chan: isLowRamDevice: false, isLowRamDeviceForced: false
D/(11:54:57.703) KurobaEx-beta | ApplicationMigrationManager: performMigration 1 -> 1 begin
D/(11:54:57.703) KurobaEx-beta | ApplicationMigrationManager: performMigration 1 -> 1 end
D/(11:54:57.703) KurobaEx-beta | Dependency Injection: Using HTTP_2 and HTTP_1_1
D/(11:54:57.706) KurobaEx-beta | ChanPostRepository: ChanPostRepository.initialize()
D/(11:54:57.709) KurobaEx-beta | SiteManager: SiteManager.initialize()
D/(11:54:57.709) KurobaEx-beta | BoardManager: BoardManager.initialize()
D/(11:54:57.709) KurobaEx-beta | BookmarksManager: BookmarksManager.initialize()
D/(11:54:57.711) KurobaEx-beta | HistoryNavigationManager: HistoryNavigationManager.initialize()
D/(11:54:57.711) KurobaEx-beta | BookmarkWatcherCoordinator: BookmarkWatcherCoordinator.initialize()
D/(11:54:57.711) KurobaEx-beta | FilterWatcherCoordinator: FilterWatcherCoordinator.initialize()
D/(11:54:57.711) KurobaEx-beta | ArchivesManager: ArchivesManager.initialize()
D/(11:54:57.711) KurobaEx-beta | ChanFilterManager: ChanFilterManager.initialize()
D/(11:54:57.711) KurobaEx-beta | AnrSupervisorRunnable: onApplicationLoaded() switching to interval 3000ms
D/(11:54:57.711) KurobaEx-beta | Chan: Application initialization took 10ms
D/(11:54:57.719) KurobaEx-beta | SiteManager: loadSitesInternal() start
D/(11:54:57.720) KurobaEx-beta | AnrSupervisorRunnable: ANR supervision started
D/(11:54:57.720) KurobaEx-beta | BoardManager: loadBoardsInternal() start
D/(11:54:57.720) KurobaEx-beta | BoardManager: loadBoardsInternal() siteDataListAsync.get() start
D/(11:54:57.721) KurobaEx-beta | BookmarksManager: initializeBookmarksInternal() start
D/(11:54:57.722) KurobaEx-beta | ArchivesManager: initializeArchivesManagerInternal() start
D/(11:54:57.726) KurobaEx-beta | StartActivity: onCreate() start isFreshStart: true, initializing everything
D/(11:54:57.759) KurobaEx-beta | ControllerNavigationManager: onControllerPushed(ThreadSlideController)
D/(11:54:57.761) KurobaEx-beta | ThreadLayout: ThreadLayout.create(threadControllerType=Catalog)
D/(11:54:57.769) KurobaEx-beta | ArchivesManager: SuspendableInitializer initWithModularResult() called
D/(11:54:57.769) KurobaEx-beta | ArchivesManager: SuspendableInitializer initWithValue() called
D/(11:54:57.769) KurobaEx-beta | ArchivesManager: notifyAllWaiters throwable==null: true, waiters=0
D/(11:54:57.769) KurobaEx-beta | ArchivesManager: SuspendableInitializer initWithValue() done
D/(11:54:57.769) KurobaEx-beta | ArchivesManager: initializeArchivesManagerInternal() done. Loaded 12 archives
D/(11:54:57.769) KurobaEx-beta | ChanFilterManager: loadFiltersInternal() start
D/(11:54:57.772) KurobaEx-beta | ArchivesManager: initializeArchivesManagerInternal() end, took 47.1ms
E/(11:54:57.791) KurobaEx-beta | ThreadPresenter: isBound() currentChanDescriptor == null
D/(11:54:57.794) KurobaEx-beta | StartActivity: createUi took 67.0ms
D/(11:54:57.794) KurobaEx-beta | UpdateManager: autoUpdateCheck()
D/(11:54:57.794) KurobaEx-beta | UpdateManager: runUpdateApi() manual=false
D/(11:54:57.794) KurobaEx-beta | StartActivity: initializeDependencies took 254us
D/(11:54:57.794) KurobaEx-beta | StartActivityIntentHandlerHelper: setupFromStateOrFreshLaunch(intent==null: false, savedInstanceState==null: true)
D/(11:54:57.794) KurobaEx-beta | StartActivityIntentHandlerHelper: onNewIntentInternal() -> false
D/(11:54:57.794) KurobaEx-beta | StartActivityIntentHandlerHelper: restoreFresh(allowedToOpenThread=true)
D/(11:54:57.794) KurobaEx-beta | SiteManager: SiteManager is not ready yet, waiting...
D/(11:54:57.795) KurobaEx-beta | SiteManager: SuspendableInitializer awaitUntilInitialized() called when not initialized, awaiting...
D/(11:54:57.795) KurobaEx-beta | StartActivity: onCreate() end isFreshStart: true
D/(11:54:57.796) KurobaEx-beta | Chan: ^^^ App went foreground ^^^
E/(11:54:57.796) KurobaEx-beta | ThreadPresenter: isBound() currentChanDescriptor == null
D/(11:54:57.796) KurobaEx-beta | ApplicationVisibilityManager: onEnteredForeground() callback execution took 37.3us, callbacks count: 3
D/(11:54:57.796) KurobaEx-beta | StartActivity: start
D/(11:54:57.796) KurobaEx-beta | ChanPostRepository: Not enough posts to start deleting, posts in database amount: 11230, max allowed posts amount: 125000
D/(11:54:57.814) KurobaEx-beta | ThreadBookmarkLocalSource: siteNamesForNewGroups=[], maxOrder=18
D/(11:54:57.819) KurobaEx-beta | UpdateManager: Calling update API for beta (https://api.github.com/repos/K1rakishou/Kuroba-Experimental-beta/releases/latest)
D/(11:54:57.822) KurobaEx-beta | ProxyStorage: loadProxies()
D/(11:54:57.822) KurobaEx-beta | ProxyStorage: proxiesFile does not exist, nothing to load
D/(11:54:57.865) KurobaEx-beta | AppModuleAndroidUtils: waitForLayout requested a re-layout by returning false
D/(11:54:57.866) KurobaEx-beta | SiteManager: SiteManager is not ready yet, waiting...
D/(11:54:57.866) KurobaEx-beta | SiteManager: SuspendableInitializer awaitUntilInitialized() called when not initialized, awaiting...
D/(11:54:57.877) KurobaEx-beta | BookmarksRepository: initialize() -> 219 took 63.6ms
D/(11:54:57.880) KurobaEx-beta | BookmarksManager: SuspendableInitializer initWithValue() called
D/(11:54:57.880) KurobaEx-beta | BookmarksManager: notifyAllWaiters throwable==null: true, waiters=0
D/(11:54:57.880) KurobaEx-beta | BookmarksManager: SuspendableInitializer initWithValue() done
D/(11:54:57.880) KurobaEx-beta | BookmarksManager: initializeBookmarksInternal() done. Loaded 219 bookmarks and 7 active bookmarks
D/(11:54:57.880) KurobaEx-beta | BookmarksManager: initializeBookmarksInternal() end, took 159ms
D/(11:54:57.881) KurobaEx-beta | ChanFilterManager: SuspendableInitializer initWithValue() called
D/(11:54:57.882) KurobaEx-beta | ChanFilterManager: notifyAllWaiters throwable==null: true, waiters=0
D/(11:54:57.882) KurobaEx-beta | ChanFilterManager: SuspendableInitializer initWithValue() done
D/(11:54:57.882) KurobaEx-beta | ChanFilterManager: loadFiltersInternal() done. Loaded 1 filters
D/(11:54:57.882) KurobaEx-beta | ChanFilterManager: loadFiltersInternal() end, took 112ms
D/(11:54:57.884) KurobaEx-beta | SiteRepository: initializeSites() -> 18 took 2.13ms
D/(11:54:57.884) KurobaEx-beta | allSitesLoadedInitializer: SuspendableInitializer initWithModularResult() called
D/(11:54:57.885) KurobaEx-beta | allSitesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(11:54:57.885) KurobaEx-beta | allSitesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(11:54:57.885) KurobaEx-beta | allSitesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(11:54:57.885) KurobaEx-beta | SiteRepository: allSitesLoadedInitializer initialized
D/(11:54:57.888) KurobaEx-beta | ChanPostRepository: Not enough threads to start deleting, threads in database amount: 11235, max allowed threads amount: 12500
D/(11:54:57.888) KurobaEx-beta | ChanPostRepository: SuspendableInitializer initWithValue() called
D/(11:54:57.889) KurobaEx-beta | ChanPostRepository: notifyAllWaiters throwable==null: true, waiters=0
D/(11:54:57.889) KurobaEx-beta | ChanPostRepository: SuspendableInitializer initWithValue() done
D/(11:54:57.901) KurobaEx-beta | SiteManager: SuspendableInitializer initWithValue() called
D/(11:54:57.901) KurobaEx-beta | BoardManager: loadBoardsInternal() siteDataListAsync.get() end
D/(11:54:57.901) KurobaEx-beta | SiteManager: SuspendableInitializer awaitUntilInitialized() called when not initialized, done (diffTime=35ms)
D/(11:54:57.901) KurobaEx-beta | SiteManager: SiteManager initialization completed, took 34.9ms
D/(11:54:57.902) KurobaEx-beta | SiteManager: notifyAllWaiters throwable==null: true, waiters=1
D/(11:54:57.902) KurobaEx-beta | SiteManager: SuspendableInitializer initWithValue() done
D/(11:54:57.902) KurobaEx-beta | SiteManager: siteRepository.initializeSites() done. Loaded 18 sites
D/(11:54:57.902) KurobaEx-beta | CompositeDnsSelector: lookup okHttpUseDnsOverHttps: false
D/(11:54:57.902) KurobaEx-beta | Dependency Injection: Using DnsSelector.Mode.IPV4_ONLY
D/(11:54:57.902) KurobaEx-beta | SiteManager: loadSitesInternal() end, took 182ms
D/(11:54:57.902) KurobaEx-beta | HistoryNavigationManager: initializeHistoryNavigationManagerInternal() start
D/(11:54:57.933) KurobaEx-beta | BookmarkWatcherCoordinator: Calling onBookmarksChanged() watchEnabled setting changed
D/(11:54:57.933) KurobaEx-beta | BookmarkWatcherCoordinator: restartBackgroundWork() called tag=BookmarkWatcherController_Beta
D/(11:54:57.934) KurobaEx-beta | FilterWatcherCoordinator: stopFilterWatcherWork()
D/(11:54:57.934) KurobaEx-beta | FilterWatcherCoordinator: watchFiltersCount=0
D/(11:54:57.934) KurobaEx-beta | FilterWatcherCoordinator: cancelFilterWatching() called tag=FilterWatcherController_Beta
D/(11:54:57.934) KurobaEx-beta | BookmarksManager: persistBookmarks async called
D/(11:54:57.936) KurobaEx-beta | SiteManager: SuspendableInitializer awaitUntilInitialized() called when not initialized, done (diffTime=141ms)
D/(11:54:57.937) KurobaEx-beta | SiteManager: SiteManager initialization completed, took 142ms
D/(11:54:57.937) KurobaEx-beta | StartActivityIntentHandlerHelper: getBoardToOpen(), loadLastOpenedBoardUponAppStart=true
D/(11:54:57.937) KurobaEx-beta | StartActivityIntentHandlerHelper: getBoardToOpen() -> historyNavigationManager.getFirstCatalogNavElement() -> null
D/(11:54:57.937) KurobaEx-beta | StartActivityIntentHandlerHelper: getThreadToOpen(), loadLastOpenedThreadUponAppStart=true
D/(11:54:57.937) KurobaEx-beta | StartActivityIntentHandlerHelper: getThreadToOpen() -> historyNavigationManager.getNavElementAtTop() -> null
D/(11:54:57.937) KurobaEx-beta | StartActivityIntentHandlerHelper: restoreFresh() getBoardToOpen returned null, getThreadToOpen returned null
D/(11:54:57.937) KurobaEx-beta | BrowseController: loadWithDefaultBoard()
E/(11:54:57.938) KurobaEx-beta | Chan: Unhandled exception
E/(11:54:57.938) KurobaEx-beta | Chan: java.lang.IllegalStateException: BoardManager is not ready yet! Use awaitUntilInitialized()
E/(11:54:57.938) KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.manager.BoardManager.firstBoardDescriptor(BoardManager.kt:9)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.presenter.BrowsePresenter$loadWithDefaultBoard$2.invoke(BrowsePresenter.kt:6)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.manager.SiteManager.viewActiveSitesOrderedWhile(SiteManager.kt:9)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.ui.controller.BrowseController.loadWithDefaultBoard(BrowseController.kt:9)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.helper.StartActivityStartupHandlerHelper.restoreFresh(StartActivityStartupHandlerHelper.kt:18)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at com.github.k1rakishou.chan.core.helper.StartActivityStartupHandlerHelper$restoreFresh$1.invokeSuspend(StartActivityStartupHandlerHelper.kt:1)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:11)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:3)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:10)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at android.os.Handler.handleCallback(Handler.java:938)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at android.os.Looper.loop(Looper.java:223)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/(11:54:57.938) KurobaEx-beta | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
D/(11:54:57.956) KurobaEx-beta | HistoryNavigationRepository: initialize() -> 256 took 24.0ms
D/(11:54:57.967) KurobaEx-beta | HistoryNavigationManager: initializeHistoryNavigationManagerInternal() done. Loaded 256 history nav elements
D/(11:54:57.967) KurobaEx-beta | ThreadBookmarkLocalSource: persist(219)
D/(11:54:57.967) KurobaEx-beta | HistoryNavigationManager: initializeHistoryNavigationManagerInternal() end, took 64.7ms
D/(11:54:57.968) KurobaEx-beta | PageRequestManager: Requesting new board pages for /pol/
D/(11:54:57.968) KurobaEx-beta | BoardManager: BoardManager is not ready yet, waiting...
D/(11:54:57.968) KurobaEx-beta | BoardManager: SuspendableInitializer awaitUntilInitialized() called when not initialized, awaiting...
D/(11:54:57.968) KurobaEx-beta | PageRequestManager: Requesting new board pages for /g/
D/(11:54:57.968) KurobaEx-beta | BoardManager: BoardManager is not ready yet, waiting...
D/(11:54:57.968) KurobaEx-beta | BoardManager: SuspendableInitializer awaitUntilInitialized() called when not initialized, awaiting...
D/(11:54:57.968) KurobaEx-beta | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(11:54:57.969) KurobaEx-beta | BookmarksRepository: persist(219) took 1.62ms
D/(11:54:57.978) KurobaEx-beta | BoardRepository: loadAllBoards() -> 129 took 4.09ms
D/(11:54:57.978) KurobaEx-beta | BoardManager: SuspendableInitializer initWithValue() called
D/(11:54:57.979) KurobaEx-beta | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(11:54:57.979) KurobaEx-beta | BoardManager: SuspendableInitializer initWithValue() done
D/(11:54:57.979) KurobaEx-beta | BoardManager: loadBoardsInternal() done. Loaded 129 boards
D/(11:54:57.979) KurobaEx-beta | BoardManager: loadBoardsInternal() end, took 258ms
D/(11:54:57.979) KurobaEx-beta | BoardManager: SuspendableInitializer awaitUntilInitialized() called when not initialized, done (diffTime=11ms)
D/(11:54:57.979) KurobaEx-beta | BoardManager: BoardManager initialization completed, took 11.1ms
D/(11:54:57.979) KurobaEx-beta | BoardManager: SuspendableInitializer awaitUntilInitialized() called when not initialized, done (diffTime=11ms)
D/(11:54:57.979) KurobaEx-beta | BoardManager: BoardManager initialization completed, took 11.2ms
D/(11:54:57.981) KurobaEx-beta | CompositeDnsSelector: lookup okHttpUseDnsOverHttps: false
D/(11:54:57.981) KurobaEx-beta | Dependency Injection: Using DnsSelector.Mode.IPV4_ONLY


------------------------------
Android API Level: 30
App Version: v0.12.2.15499
Build type: Release
Flavor type: Beta
Phone Model: Xiaomi POCO F1
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 256
------------------------------
Current layout mode: PHONE
Board view mode: LIST
Prefetching enabled: false
Hi-res thumbnails enabled: false
CloudFlare force preload enabled: false
diskCacheSizeMegabytes: 1024
prefetchDiskCacheSizeMegabytes: 2048
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3A4chan
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: true
Watch foreground interval: 600000
Watch foreground adaptive interval: true
Background watcher enabled: true
Watch background interval: 7200000
Filter watch enabled: false
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------
```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/ae2069ae9c77c0cfd24170555c61481bef5debe8
