### ISSUE TITLE
Crash report "java.lang.RuntimeException: kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@2e40c8c"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#576]
Crash report
UUID: 4fb25f4f42b94c05c9bc3d1bd60a7d1c
Build flavor: fdroid
Version name: v0.12.6
OS info: Android 8.1.0, sdk version: 27
Report description: No title
Logs:
```
=== LOGS(2021-10-02 22:30:57 UTC) ===
D/(19:30:30.140) KurobaEx-fdroid | BoardRepository: loadAllBoards() -> 777 took 60.518548ms
D/(19:30:30.142) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() called
D/(19:30:30.142) KurobaEx-fdroid | BoardManager: notifyAllWaiters throwable==null: true, waiters=0
D/(19:30:30.142) KurobaEx-fdroid | BoardManager: SuspendableInitializer initWithValue() done
D/(19:30:30.142) KurobaEx-fdroid | BoardManager: loadBoardsInternal() done. Loaded 777 boards
D/(19:30:30.142) KurobaEx-fdroid | BoardManager: loadBoardsInternal() end, took 149.584442ms
D/(19:30:30.165) KurobaEx-fdroid | ControllerNavigationManager: onControllerPushed(ThreadSlideController)
D/(19:30:30.194) KurobaEx-fdroid | ThreadLayout: ThreadLayout.create(threadControllerType=Catalog)
D/(19:30:30.273) KurobaEx-fdroid | ControllerNavigationManager: onControllerSwipedTo(BrowseController)
D/(19:30:30.275) KurobaEx-fdroid | StartActivity: createUi took 232.342627ms
D/(19:30:30.276) KurobaEx-fdroid | UpdateManager: autoUpdateCheck()
D/(19:30:30.276) KurobaEx-fdroid | UpdateManager: Updater is disabled for fdroid builds!
D/(19:30:30.276) KurobaEx-fdroid | StartActivity: initializeDependencies took 490.937us
D/(19:30:30.276) KurobaEx-fdroid | StartActivityStartupHandlerHelper: setupFromStateOrFreshLaunch(intent==null: false, savedInstanceState==null: true)
D/(19:30:30.276) KurobaEx-fdroid | StartActivityStartupHandlerHelper: onNewIntentInternal() -> false
D/(19:30:30.277) KurobaEx-fdroid | StartActivityStartupHandlerHelper: restoreFresh()
D/(19:30:30.277) KurobaEx-fdroid | StartActivityStartupHandlerHelper: getCatalogToOpen(), loadLastOpenedBoardUponAppStart=false
D/(19:30:30.277) KurobaEx-fdroid | StartActivityStartupHandlerHelper: getCatalogToOpen() -> 'BD{4chan/pol}'
D/(19:30:30.277) KurobaEx-fdroid | StartActivityStartupHandlerHelper: getThreadToOpen(), loadLastOpenedThreadUponAppStart=false
D/(19:30:30.277) KurobaEx-fdroid | StartActivityStartupHandlerHelper: restoreFresh() getCatalogToOpen returned CD{4chan/pol}, getThreadToOpen returned null
D/(19:30:30.277) KurobaEx-fdroid | BrowseController: showBoard(CD{4chan/pol}, false)
D/(19:30:30.277) KurobaEx-fdroid | BrowseController: showBoardInternal(CD{4chan/pol}, false)
D/(19:30:30.277) KurobaEx-fdroid | BrowseController: setCatalog(CD{4chan/pol})
D/(19:30:30.278) KurobaEx-fdroid | BrowseController: loadCatalog(CD{4chan/pol})
D/(19:30:30.278) KurobaEx-fdroid | ThreadPresenter: bindChanDescriptor(chanDescriptor=CD{4chan/pol})
D/(19:30:30.278) KurobaEx-fdroid | PageRequestManager: Requesting new board pages for /pol/
D/(19:30:30.287) KurobaEx-fdroid | ProxyStorage: loadProxies()
D/(19:30:30.287) KurobaEx-fdroid | ProxyStorage: proxiesFile does not exist, nothing to load
D/(19:30:30.287) KurobaEx-fdroid | SiteManager: notifyAllWaiters throwable==null: true, waiters=0
D/(19:30:30.288) KurobaEx-fdroid | CompositeDnsSelector: lookup okHttpUseDnsOverHttps: false
D/(19:30:30.288) KurobaEx-fdroid | Dependency Injection: Using DnsSelector.Mode.IPV4_ONLY
D/(19:30:30.292) KurobaEx-fdroid | ThreadPresenter: chanThreadTicker.startTicker(CD{4chan/pol})
D/(19:30:30.292) KurobaEx-fdroid | ChanTicker: startTicker(CD{4chan/pol})
D/(19:30:30.292) KurobaEx-fdroid | ChanTicker: kickTicker(false)
D/(19:30:30.292) KurobaEx-fdroid | ChanTicker: kickTicker() called with catalog descriptor, ticking right away
D/(19:30:30.299) KurobaEx-fdroid | StartActivity: onCreate() end isFreshStart: true
D/(19:30:30.300) KurobaEx-fdroid | Chan: ^^^ App went foreground ^^^
D/(19:30:30.300) KurobaEx-fdroid | ChanTicker: stopTicker(resetCurrentChanDescriptor=false)
D/(19:30:30.300) KurobaEx-fdroid | ApplicationVisibilityManager: onEnteredForeground() callback execution took 118.281us, callbacks count: 3
D/(19:30:30.300) KurobaEx-fdroid | StartActivity: start
D/(19:30:30.423) KurobaEx-fdroid | AppModuleAndroidUtils: waitForLayout requested a re-layout by returning false
D/(19:30:30.426) KurobaEx-fdroid | BookmarksManager: persistBookmarks async called
D/(19:30:30.426) KurobaEx-fdroid | viewModelInitialized: SuspendableInitializer initWithValue() called
D/(19:30:30.427) KurobaEx-fdroid | viewModelInitialized: notifyAllWaiters throwable==null: true, waiters=0
D/(19:30:30.427) KurobaEx-fdroid | viewModelInitialized: SuspendableInitializer initWithValue() done
D/(19:30:30.427) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist(6)
D/(19:30:30.427) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(19:30:30.427) KurobaEx-fdroid | BookmarksRepository: persist(6) took 664.479us
D/(19:30:30.428) KurobaEx-fdroid | ChanTicker: StopTicker
D/(19:30:30.428) KurobaEx-fdroid | ChanTicker: StopTicker
D/(19:30:30.502) KurobaEx-fdroid | BookmarksManager: subscriptions=3
D/(19:30:30.503) KurobaEx-fdroid | BookmarksManager: persistBookmarks async finished
D/(19:30:30.509) KurobaEx-fdroid | BookmarkWatcherCoordinator: restartBackgroundWork() called tag=BookmarkWatcherController_Fdroid
D/(19:30:30.509) KurobaEx-fdroid | BookmarkWatcherCoordinator: restartBackgroundWork() cannot restart watcher because one of the required settings is turned off (watchEnabled=false, watchBackground=false)
D/(19:30:30.510) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Fdroid
D/(19:30:30.511) KurobaEx-fdroid | FilterWatcherCoordinator: cancelFilterWatching() called tag=FilterWatcherController_Fdroid
D/(19:30:30.512) KurobaEx-fdroid | DrawerPresenter: listenForBookmarksChanges bookmarkChange=com.github.k1rakishou.chan.core.manager.BookmarksManager$BookmarkChange$BookmarksInitialized@54759be
D/(19:30:30.512) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() start
D/(19:30:30.513) KurobaEx-fdroid | BookmarkWatcherCoordinator: onBookmarksChanged() watchEnabled is false, stopping foreground watcher
D/(19:30:30.513) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelForegroundBookmarkWatching() called
D/(19:30:30.513) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Fdroid
D/(19:30:30.520) KurobaEx-fdroid | ThreadBookmarkGroupRepository: initialize() -> 2 took 6.116615ms
D/(19:30:30.521) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() done. Loaded 2 bookmark groups
D/(19:30:30.522) KurobaEx-fdroid | ThreadBookmarkGroupManager: loadThreadBookmarkGroupsInternal() end, took 9.488438ms
D/(19:30:30.522) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Fdroid canceled
D/(19:30:30.522) KurobaEx-fdroid | BookmarkWatcherCoordinator: restartBackgroundWork() called tag=BookmarkWatcherController_Fdroid
D/(19:30:30.522) KurobaEx-fdroid | BookmarkWatcherCoordinator: restartBackgroundWork() cannot restart watcher because one of the required settings is turned off (watchEnabled=false, watchBackground=false)
D/(19:30:30.522) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Fdroid
D/(19:30:30.526) KurobaEx-fdroid | FilterWatcherCoordinator: cancelFilterWatching() work with tag FilterWatcherController_Fdroid canceled
D/(19:30:30.528) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Fdroid canceled
D/(19:30:30.531) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Fdroid canceled
D/(19:30:30.531) KurobaEx-fdroid | BookmarkWatcherCoordinator: restartBackgroundWork() called tag=BookmarkWatcherController_Fdroid
D/(19:30:30.531) KurobaEx-fdroid | BookmarkWatcherCoordinator: restartBackgroundWork() cannot restart watcher because one of the required settings is turned off (watchEnabled=false, watchBackground=false)
D/(19:30:30.531) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Fdroid
D/(19:30:30.531) KurobaEx-fdroid | BookmarkWatcherCoordinator: onBookmarksChanged() watchEnabled is false, stopping foreground watcher
D/(19:30:30.531) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelForegroundBookmarkWatching() called
D/(19:30:30.531) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Fdroid
D/(19:30:30.534) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Fdroid canceled
D/(19:30:30.536) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Fdroid canceled
D/(19:30:30.929) KurobaEx-fdroid | HistoryNavigationManager: initializeHistoryNavigationManagerInternal() start
D/(19:30:30.973) KurobaEx-fdroid | HistoryNavigationRepository: initialize() -> 256 took 42.282973ms
D/(19:30:30.974) KurobaEx-fdroid | HistoryNavigationManager: initializeHistoryNavigationManagerInternal() done. Loaded 256 history nav elements
D/(19:30:30.974) KurobaEx-fdroid | HistoryNavigationManager: initializeHistoryNavigationManagerInternal() end, took 44.735682ms
D/(19:30:30.983) KurobaEx-fdroid | DrawerPresenter: loadNavigationHistoryInitial() success
D/(19:30:30.995) KurobaEx-fdroid | JsonReaderRequest: Request "Chan4PagesRequest" to "https://a.4cdn.org/pol/threads.json" took 715.709394ms
D/(19:30:30.997) KurobaEx-fdroid | PageRequestManager: Got pages for 4chan/pol/
D/(19:30:31.503) KurobaEx-fdroid | ThreadPresenter: onChanTickerTick(CD{4chan/pol})
D/(19:30:31.504) KurobaEx-fdroid | ThreadPresenter: normalLoad() start
D/(19:30:31.504) KurobaEx-fdroid | ThreadPresenter: normalLoad(currentChanDescriptor=CD{4chan/pol}
D/(19:30:31.504) KurobaEx-fdroid | ThreadPresenter: showLoading=false
D/(19:30:31.504) KurobaEx-fdroid | ThreadPresenter: chanCacheUpdateOptions=UpdateCache
D/(19:30:31.504) KurobaEx-fdroid | ThreadPresenter: chanLoadOptions=ChanLoadOptions(chanLoadOption=RetainAll)
D/(19:30:31.504) KurobaEx-fdroid | ThreadPresenter: chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache])
D/(19:30:31.504) KurobaEx-fdroid | ThreadPresenter: chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(19:30:31.505) KurobaEx-fdroid | ChanThreadManager: loadThreadOrCatalog(null, null, CD{4chan/pol}, UpdateCache, ChanLoadOptions(chanLoadOption=RetainAll), ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(19:30:31.505) KurobaEx-fdroid | ChanThreadManager: loadInternal() Requested catalog /CD{4chan/pol}/
D/(19:30:31.505) KurobaEx-fdroid | CatalogDataPreloadUseCase: preloadCatalogInfo(CD{4chan/pol}) begin
D/(19:30:31.506) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() Begin(chanDescriptor=CD{4chan/pol})
D/(19:30:31.515) KurobaEx-fdroid | FilterWatcherCoordinator: restartFilterWatcherWithTinyDelay()
D/(19:30:31.515) KurobaEx-fdroid | FilterWatcherCoordinator: restartFilterWatcherWithTinyDelay() no watch filters found, canceling the work
D/(19:30:31.515) KurobaEx-fdroid | FilterWatcherCoordinator: cancelFilterWatching() called tag=FilterWatcherController_Fdroid
D/(19:30:31.517) KurobaEx-fdroid | FilterWatcherCoordinator: cancelFilterWatching() work with tag FilterWatcherController_Fdroid canceled
D/(19:30:31.522) KurobaEx-fdroid | PostHideManager: chanPostHideRepository.preloadForCatalogInternal() preloaded 181 post hides
D/(19:30:31.527) KurobaEx-fdroid | CatalogDataPreloadUseCase: preloadCatalogInfo(CD{4chan/pol}) end, took 21.213440ms
D/(19:30:31.527) KurobaEx-fdroid | ChanThreadManager: loadInternal(), chanDescriptor=CD{4chan/pol} preloadCatalogInfo took 22.135471ms
D/(19:30:31.527) KurobaEx-fdroid | ChanThreadManager: loadInternal() chanThreadsCache.cacheNeedsUpdate(CD{4chan/pol}, UpdateCache) -> true
D/(19:30:31.528) KurobaEx-fdroid | AbstractParsePostsUseCase: Thread count: 8
D/(19:30:31.529) KurobaEx-fdroid | ChanThreadLoaderCoordinator: loadThreadOrCatalog(chanLoadUrl=ChanLoadUrl(url=https://a.4cdn.org/pol/catalog.json, isIncremental=false, page=null), compositeCatalogDescriptor=null, chanDescriptor=CD{4chan/pol}, chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), chanCacheUpdateOptions=UpdateCache, chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647), chanReader=FutabaChanReader)
D/(19:30:31.530) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() Loading(chanDescriptor=CD{4chan/pol})
D/(19:30:31.532) KurobaEx-fdroid | CompositeDnsSelector: lookup okHttpUseDnsOverHttps: false
D/(19:30:31.532) KurobaEx-fdroid | Dependency Injection: Using DnsSelector.Mode.IPV4_ONLY
D/(19:30:32.082) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() Reading(chanDescriptor=CD{4chan/pol})
D/(19:30:32.225) KurobaEx-fdroid | ChanThreadLoaderCoordinator: loadThreadOrCatalog(chanLoadUrl='ChanLoadUrl(url=https://a.4cdn.org/pol/catalog.json, isIncremental=false, page=null)') chanReaderProcessor=ChanReaderProcessor{chanDescriptor=CD{4chan/pol}, toParse=202, closed=false, deleted=false, archived=false, error=null}
D/(19:30:32.226) KurobaEx-fdroid | NormalPostLoader: persistPosts(CD{4chan/pol}, ChanReaderProcessor{chanDescriptor=CD{4chan/pol}, toParse=202, closed=false, deleted=false, archived=false, error=null}, ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), UpdateCache, DefaultPostParser)
D/(19:30:32.227) KurobaEx-fdroid | ChanCatalogSnapshotRepository: storeChanCatalogSnapshot(ChanCatalogSnapshot{catalogDescriptor=CD{4chan/pol}, chanCatalogSnapshotEntryList=202, currentCatalogPage=1, endReached=false})
D/(19:30:32.263) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() ProcessingFilters(chanDescriptor=CD{4chan/pol}, filtersCount=9)
D/(19:30:32.332) KurobaEx-fdroid | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=CD{4chan/pol}, postsToParseSize=202), internalIds=202, filters=9
D/(19:30:32.332) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() ParsingPosts(chanDescriptor=CD{4chan/pol}, postsToParseCount=202)
D/(19:30:32.431) KurobaEx-fdroid | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=CD{4chan/pol}) -> parsedPosts=202
D/(19:30:32.432) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() PersistingPosts(chanDescriptor=CD{4chan/pol}, postsCount=202)
D/(19:30:32.435) KurobaEx-fdroid | ChanPostRepository: insertOrUpdateMany(CD{4chan/pol}) -> 202
D/(19:30:32.436) KurobaEx-fdroid | ChanPostRepository: insertOrUpdateCatalogOriginalPosts() inserting 202 posts into the DB
D/(19:30:32.439) KurobaEx-fdroid | ChanThreadLoaderCoordinator: ChanReaderRequest.readJson() stats:
D/(19:30:32.439) KurobaEx-fdroid | ChanThreadLoaderCoordinator: url = https://a.4cdn.org/pol/catalog.json.
D/(19:30:32.439) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Network request execution took 551.775524ms.
D/(19:30:32.439) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Json reading took 142.847827ms.
D/(19:30:32.439) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Store new posts took 3.702188ms (stored 202 posts).
D/(19:30:32.439) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Parse posts took 99.502354ms (parsed 202 out of 202 posts).
D/(19:30:32.439) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Filter processing took 68.901934ms (filers count: 9).
D/(19:30:32.439) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Total in-memory cached posts count: 202/9830.
D/(19:30:32.439) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Threads with more than one post count: (0/8), total cached threads count: 202.
D/(19:30:32.439) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Total local processing time: 314.954303ms
D/(19:30:32.440) KurobaEx-fdroid | CatalogDataPreloadUseCase: postloadCatalogInfo(CD{4chan/pol}) begin
D/(19:30:32.952) KurobaEx-fdroid | SeenPostsManager: loadForCatalog(CD{4chan/pol}) threadDescriptorsToLoad=202, seenPostsGrouped=0, alreadyLoadedDescriptorsForUnlimitedCatalog=0
D/(19:30:32.952) KurobaEx-fdroid | CatalogDataPreloadUseCase: postloadCatalogInfo(CD{4chan/pol}) end, took 512.551197ms
D/(19:30:32.953) KurobaEx-fdroid | ChanThreadManager: loadThreadOrCatalog(), descriptor=CD{4chan/pol} postloadCatalogInfo took 512.821717ms
D/(19:30:32.953) KurobaEx-fdroid | ThreadPresenter: normalLoad() threadLoadResult=ThreadLoadResult.Loaded{chanDescriptor=CD{4chan/pol}} (currentChanDescriptor=CD{4chan/pol})
D/(19:30:32.953) KurobaEx-fdroid | ThreadPresenter: onChanLoaderData() called, loadedChanDescriptor=CD{4chan/pol}
D/(19:30:32.956) KurobaEx-fdroid | filesLoadedInitializer: SuspendableInitializer initWithValue() called
D/(19:30:32.957) KurobaEx-fdroid | filesLoadedInitializer: notifyAllWaiters throwable==null: true, waiters=0
D/(19:30:32.957) KurobaEx-fdroid | filesLoadedInitializer: SuspendableInitializer initWithValue() done
D/(19:30:32.966) KurobaEx-fdroid | PostsFilter: originalPosts.size=202, retainedPosts.size=175, chanDescriptor=CD{4chan/pol}
D/(19:30:32.967) KurobaEx-fdroid | PostingServiceDelegate: listenForPostingStatusUpdates(CD{4chan/pol})
D/(19:30:32.968) KurobaEx-fdroid | ReplyPresenter: processPostingStatusUpdates(CD{4chan/pol}) -> Attached
D/(19:30:32.968) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() ApplyingFilters(chanDescriptor=CD{4chan/pol}, postHidesCount=0, postFiltersCount=27)
D/(19:30:32.971) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() RefreshingPosts(chanDescriptor=CD{4chan/pol})
D/(19:30:33.033) KurobaEx-fdroid | PostAdapter: setThread() notifyDataSetChanged called, postIndexedList.size=175
D/(19:30:33.033) KurobaEx-fdroid | ThreadLayout: showPostsForChanDescriptor() showPosts(CD{4chan/pol}) -> true applyFilterDuration=1.943855ms, setThreadPostsDuration=66.673965ms, totalDuration=79.720998ms
D/(19:30:33.051) KurobaEx-fdroid | ThreadPresenter: onChanLoaderData(CD{4chan/pol}) end, took 97.724854ms
D/(19:30:33.051) KurobaEx-fdroid | ThreadPresenter: normalLoad() end
D/(19:30:33.052) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() End(chanDescriptor=CD{4chan/pol})
D/(19:30:33.072) KurobaEx-fdroid | CacheHandler: fileCacheDiskSizeMBytes=256
D/(19:30:33.073) KurobaEx-fdroid | CacheHandler: recalculateSize() start
D/(19:30:33.084) KurobaEx-fdroid | Dependency Injection: availableMemoryPercentage=0.15
D/(19:30:33.100) KurobaEx-fdroid | ThreadDownloadManager: initializeThreadDownloadManagerInternal() start
D/(19:30:33.108) KurobaEx-fdroid | ThreadDownloadManager: initializeThreadDownloadManagerInternal() end, took 7.730366ms
D/(19:30:33.242) KurobaEx-fdroid | HistoryNavigationManager: persistNavigationStack async called
D/(19:30:33.242) KurobaEx-fdroid | HistoryNavigationManager: persistNavigationStackInternal navStackCopy.size=256
D/(19:30:33.245) KurobaEx-fdroid | NavHistoryLocalSource: persist(navHistoryStack.size=256)
D/(19:30:33.298) KurobaEx-fdroid | HistoryNavigationRepository: persist(256) took 54.413338ms
D/(19:30:33.313) KurobaEx-fdroid | HistoryNavigationManager: persistNavigationStack async finished
D/(19:30:34.994) KurobaEx-fdroid | ControllerNavigationManager: onCloseAllNonMainControllers()
D/(19:30:35.030) KurobaEx-fdroid | ControllerNavigationManager: onControllerPushed(TabHostController)
D/(19:30:35.057) KurobaEx-fdroid | BookmarksController: Calling reloadBookmarks() because bookmark sorting order was changed
D/(19:30:35.088) KurobaEx-fdroid | BookmarksManager: persistBookmarks async called
D/(19:30:35.089) KurobaEx-fdroid | BookmarksPresenter: calling reloadBookmarks() first time
D/(19:30:35.089) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist(6)
D/(19:30:39.906) KurobaEx-fdroid | ControllerNavigationManager: onCloseAllNonMainControllers()
D/(19:30:39.955) KurobaEx-fdroid | AppModuleAndroidUtils: waitForLayout requested a re-layout by returning false
D/(19:30:43.565) KurobaEx-fdroid | ControllerNavigationManager: onCloseAllNonMainControllers()
D/(19:30:43.578) KurobaEx-fdroid | ControllerNavigationManager: onControllerPushed(TabHostController)
D/(19:30:43.589) KurobaEx-fdroid | BookmarksController: Calling reloadBookmarks() because bookmark sorting order was changed
D/(19:30:43.600) KurobaEx-fdroid | BookmarksPresenter: calling reloadBookmarks() first time
D/(19:30:44.969) KurobaEx-fdroid | ControllerNavigationManager: onCloseAllNonMainControllers()
D/(19:30:45.018) KurobaEx-fdroid | ControllerNavigationManager: onControllerPushed(LocalArchiveController)
D/(19:30:45.029) KurobaEx-fdroid | AppModuleAndroidUtils: waitForLayout requested a re-layout by returning false
D/(19:30:46.056) KurobaEx-fdroid | ControllerNavigationManager: onCloseAllNonMainControllers()
D/(19:30:46.088) KurobaEx-fdroid | ControllerNavigationManager: onControllerPushed(TabHostController)
D/(19:30:46.098) KurobaEx-fdroid | BookmarksController: Calling reloadBookmarks() because bookmark sorting order was changed
D/(19:30:46.104) KurobaEx-fdroid | AppModuleAndroidUtils: waitForLayout requested a re-layout by returning false
D/(19:30:46.105) KurobaEx-fdroid | BookmarksPresenter: calling reloadBookmarks() first time
D/(19:30:46.691) KurobaEx-fdroid | ControllerNavigationManager: onCloseAllNonMainControllers()
D/(19:30:46.717) KurobaEx-fdroid | AppModuleAndroidUtils: waitForLayout requested a re-layout by returning false
D/(19:30:50.776) KurobaEx-fdroid | Chan: vvv App went background vvv
D/(19:30:50.777) KurobaEx-fdroid | ChanTicker: stopTicker(resetCurrentChanDescriptor=false)
D/(19:30:50.777) KurobaEx-fdroid | ApplicationVisibilityManager: onEnteredBackground() callback execution took 503.854us, callbacks count: 3
D/(19:30:50.777) KurobaEx-fdroid | StartActivity: stop
D/(19:30:50.784) KurobaEx-fdroid | ThreadLayout: ThreadLayout.destroy(threadControllerType=Catalog)
D/(19:30:50.784) KurobaEx-fdroid | ThreadPresenter: unbindChanDescriptor(isDestroying=true) currentChanDescriptor=CD{4chan/pol}
D/(19:30:50.784) KurobaEx-fdroid | ThreadPresenter: chanThreadTicker.stopTicker(CD{4chan/pol})
D/(19:30:50.784) KurobaEx-fdroid | ChanTicker: stopTicker(resetCurrentChanDescriptor=true)
D/(19:30:50.790) KurobaEx-fdroid | StartActivity: onDestroy()
D/(19:30:50.794) KurobaEx-fdroid | HistoryNavigationManager: persistNavigationStack async called
D/(19:30:50.794) KurobaEx-fdroid | HistoryNavigationManager: persistNavigationStackInternal navStackCopy.size=256
D/(19:30:56.939) KurobaEx-fdroid | CacheHandler: recalculateSize() end took 23.865670242s, filesOnDiskCount=21517, fullyDownloadedFilesCount=0
D/(19:30:56.939) KurobaEx-fdroid | CacheHandler: clearChunksCacheDirInternal() start
D/(19:30:56.941) KurobaEx-fdroid | CacheHandler: clearChunksCacheDirInternal() end
D/(19:30:56.946) KurobaEx-fdroid | BookmarksManager: persistBookmarks eager called
D/(19:30:56.947) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(19:30:56.947) KurobaEx-fdroid | BookmarksRepository: persist(6) took 21.857717385s
D/(19:30:56.948) KurobaEx-fdroid | BookmarksManager: subscriptions=2
D/(19:30:56.948) KurobaEx-fdroid | BookmarksManager: persistBookmarks async finished
D/(19:30:56.948) KurobaEx-fdroid | BookmarksManager: persistBookmarks async called
D/(19:30:57.045) KurobaEx-fdroid | NavHistoryLocalSource: persist(navHistoryStack.size=256)
E/(19:30:57.045) KurobaEx-fdroid | BaseViewModel: onViewModelReady(StandaloneCoroutine) error
E/(19:30:57.045) KurobaEx-fdroid | BaseViewModel: kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@2e40c8c
E/(19:30:57.045) KurobaEx-fdroid | viewModelInitialized: SuspendableInitializer initWithError() called
D/(19:30:57.045) KurobaEx-fdroid | viewModelInitialized: notifyAllWaiters throwable==null: false, waiters=0
E/(19:30:57.045) KurobaEx-fdroid | viewModelInitialized: SuspendableInitializer initWithError() done
E/(19:30:57.058) KurobaEx-fdroid | Chan: Unhandled exception
E/(19:30:57.058) KurobaEx-fdroid | Chan: java.lang.RuntimeException: kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@2e40c8c
E/(19:30:57.058) KurobaEx-fdroid | Chan: 	at com.github.k1rakishou.chan.core.base.BaseViewModel$2.invokeSuspend(BaseViewModel.kt:13)
E/(19:30:57.058) KurobaEx-fdroid | Chan: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/(19:30:57.058) KurobaEx-fdroid | Chan: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:16)
E/(19:30:57.058) KurobaEx-fdroid | Chan: 	at android.os.Handler.handleCallback(Handler.java:790)
E/(19:30:57.058) KurobaEx-fdroid | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/(19:30:57.058) KurobaEx-fdroid | Chan: 	at android.os.Looper.loop(Looper.java:164)
E/(19:30:57.058) KurobaEx-fdroid | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:6626)
E/(19:30:57.058) KurobaEx-fdroid | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(19:30:57.058) KurobaEx-fdroid | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/(19:30:57.058) KurobaEx-fdroid | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
E/(19:30:57.058) KurobaEx-fdroid | Chan: Caused by: kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@2e40c8c
D/(19:30:57.088) KurobaEx-fdroid | HistoryNavigationRepository: persist(256) took 43.443441ms
D/(19:30:57.095) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist(6)
D/(19:30:57.095) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(19:30:57.095) KurobaEx-fdroid | BookmarksRepository: persist(6) took 864.74us
D/(19:30:57.096) KurobaEx-fdroid | BookmarksManager: persistBookmarks eager finished
D/(19:30:57.096) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist(6)
D/(19:30:57.097) KurobaEx-fdroid | ThreadBookmarkLocalSource: persist() inserted/updated 0 bookmarks, deleted 0 bookmarks
D/(19:30:57.097) KurobaEx-fdroid | BookmarksRepository: persist(6) took 375.938us
```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/c6ab9103fbd076d3e1d258cef8570dcd41d02813
