### ISSUE TITLE
Crash report "java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum -1 is less than minimum 0."

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#595]
Crash report
UUID: ea67cbd7a5646b744bb606843f831fd4
Build flavor: stable
Version name: v1.0.3
OS info: Android 8.1.0, sdk version: 27
Report description: No title
Logs:
```
=== LOGS(2021-10-14 07:13:50 UTC) ===


=== STACKTRACE ===
Called from unhandled exception handler.
java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum -1 is less than minimum 0.
	at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:1)
	at com.github.k1rakishou.chan.ui.cell.ThreadCellData$updateThreadData$3.invokeSuspend(ThreadCellData.kt:20)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)


------------------------------
Android API Level: 27
App Version: v1.0.3.17284
Phone Model: OPPO CPH1909
Build type: Release
Flavor type: Stable
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 384
------------------------------
Current layout mode: SLIDE
Board view mode: GRID
Prefetching enabled: false
Hi-res thumbnails enabled: false
CloudFlare force preload enabled: true
useMpvVideoPlayer: false
asyncPostCellDataCalculation: true
userAgent: Mozilla/5.0 (Linux; Android 8.1.0; CPH1909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.127 Mobile Safari/537.36
kurobaExUserAgent: KurobaEx v1.0.3.17284
maxPostsCountInPostsCache: 16000
maxAmountOfPostsInDatabase: 125000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: null
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: true
Watch foreground interval: 60000
Watch foreground adaptive interval: false
Background watcher enabled: false
Filter watch enabled: true
Filter watch interval: 43200000
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------
```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/7fab76fbbdc6150616514c9004c916115c167d3c
