### ISSUE TITLE
Report "/vt/ sticky killed catalog browsing"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#652]
UUID: f44b3b912cd001e524b0571bec250f98
Build flavor: fdroid
Version name: v1.1.4
OS info: Android 11, sdk version: 30
Report description: Shows only Expected a name but was NUMBER at line 1 column 1780 path $[0].threads[1].sticky_cap instead of actual content

**Comment by K1rakishou** [comment]
Already fixed in v1.1.6 and the fix is out. 
Fdroid is going to take a couple of days to update (like always) so for now you can switch to beta/release versions.

**Comment by K1rakishou** [comment]
cannot load board
UUID: 8ed98d2462e0d3e451fe5915e76d3abb
Build flavor: fdroid
Version name: v1.1.4
OS info: Android 10, sdk version: 29
Report description: theres sticky in board
Logs:
```
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: onChanLoaderError() called
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: com.github.k1rakishou.chan.core.site.loader.ChanLoaderException: com.github.k1rakishou.chan.core.site.loader.ChanLoaderException: java.lang.IllegalStateException: Expected a name but was NUMBER at line 1 column 1862 path $[0].threads[1].sticky_cap
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.github.k1rakishou.chan.core.manager.ChanThreadManager.loadInternal(ChanThreadManager.kt:66)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.github.k1rakishou.chan.core.manager.ChanThreadManager$loadInternal$1.invokeSuspend(ChanThreadManager.kt:1)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at android.os.Handler.handleCallback(Handler.java:900)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at android.os.Looper.loop(Looper.java:219)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at android.app.ActivityThread.main(ActivityThread.java:8387)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at java.lang.reflect.Method.invoke(Native Method)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: Caused by: com.github.k1rakishou.chan.core.site.loader.ChanLoaderException: java.lang.IllegalStateException: Expected a name but was NUMBER at line 1 column 1862 path $[0].threads[1].sticky_cap
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.github.k1rakishou.chan.core.site.loader.ChanThreadLoaderCoordinator$loadThreadOrCatalog$2.invokeSuspend(ChanThreadLoaderCoordinator.kt:82)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: Caused by: java.lang.IllegalStateException: Expected a name but was NUMBER at line 1 column 1862 path $[0].threads[1].sticky_cap
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.google.gson.stream.JsonReader.nextName(JsonReader.java:8)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.github.k1rakishou.chan.core.site.common.FutabaChanReader.readPostObject(FutabaChanReader.kt:19)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.github.k1rakishou.chan.core.site.common.FutabaChanReader$loadCatalog$2$1.invokeSuspend(FutabaChanReader.kt:5)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.github.k1rakishou.chan.core.site.common.FutabaChanReader$loadCatalog$2$1.invoke(FutabaChanReader.kt:2)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.github.k1rakishou.chan.core.site.common.FutabaChanReader.access$iterateThreadsInCatalog(FutabaChanReader.kt:14)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.github.k1rakishou.chan.core.site.common.FutabaChanReader$loadCatalog$2.invokeSuspend(FutabaChanReader.kt:5)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.github.k1rakishou.chan.core.site.common.FutabaChanReader$loadCatalog$2.invoke(FutabaChanReader.kt:2)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.github.k1rakishou.chan.core.site.parser.ChanReader.readBodyJson(ChanReader.kt:6)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.github.k1rakishou.chan.core.site.common.FutabaChanReader.loadCatalog(FutabaChanReader.kt:1)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.github.k1rakishou.chan.core.site.loader.ChanThreadLoaderCoordinator.readPostsFromResponse(ChanThreadLoaderCoordinator.kt:15)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	at com.github.k1rakishou.chan.core.site.loader.ChanThreadLoaderCoordinator$loadThreadOrCatalog$2.invokeSuspend(ChanThreadLoaderCoordinator.kt:45)
E/(19:51:36.636) KurobaEx-fdroid | ThreadPresenter: 	... 4 more
------------------------------
Android API Level: 29
App Version: v1.1.4
Phone Model: HUAWEI VOG-L29
Build type: Unknown
Flavor type: Fdroid
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 384
------------------------------
Current layout mode: SLIDE
Board view mode: LIST
Bottom navigation enabled: true
Prefetching enabled: false
Hi-res thumbnails enabled: false
CloudFlare force preload enabled: false
useMpvVideoPlayer: false
userAgent: Mozilla/5.0 (Linux; Android 10; VOG-L29 Build/HUAWEIVOG-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.45 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx-fdroid v1.1.4
maxPostsCountInPostsCache: 16000
maxAmountOfPostsInDatabase: 125000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3AKuroba
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: false
Background watcher enabled: false
Filter watch enabled: false
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------
```

**Comment by K1rakishou** [comment]
This was fixed and the fix released days ago.
