### ISSUE TITLE
Saving too many threads makes the local thread archive page inaccessible due to a too many SQL variables error

### ISSUE THREAD

**Issue by Vikezor** [K1rakishou/Kuroba-Experimental#723]
Steps to reproduce:
1. save more than SQLITE_LIMIT_VARIABLE_NUMBER (probably 1000) threads
2. observe that the local thread archive page now just shows the SQLite error message shown in the screenshot
![Screenshot_20220117-134047](https://user-images.githubusercontent.com/6238226/149767115-d11add2a-8104-447c-b2d2-d891d8056dd8.jpg)

log:
```
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: getThreadOriginalPostsByDatabaseId() error
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: android.database.sqlite.SQLiteException: too many SQL variables (code 1 SQLITE_ERROR): , while compiling: SELECT *
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel:         FROM chan_thread
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel:         WHERE thread_id IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1570)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1533)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.java:4)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at androidx.room.RoomDatabase.query(RoomDatabase.java:4)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at androidx.room.util.DBUtil.query(DBUtil.java:1)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at com.github.k1rakishou.model.dao.ChanThreadDao_Impl$15.call(ChanThreadDao_Impl.java:3)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at androidx.room.CoroutinesRoom.execute(CoroutinesRoom.kt:8)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at com.github.k1rakishou.model.dao.ChanThreadDao_Impl.selectManyByThreadIdList(ChanThreadDao_Impl.java:14)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at com.github.k1rakishou.model.source.local.ChanPostLocalSource.getThreadOriginalPostsByDatabaseId(ChanPostLocalSource.kt:6)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at com.github.k1rakishou.model.repository.ChanPostRepository$getThreadOriginalPostsByDatabaseId$3$1.invokeSuspend(ChanPostRepository.kt:7)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at com.github.k1rakishou.model.repository.ChanPostRepository$getThreadOriginalPostsByDatabaseId$3$1.invoke(ChanPostRepository.kt:2)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at androidx.room.RoomDatabaseKt$withTransaction$2.invokeSuspend(RoomDatabase.kt:10)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:5)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:21)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:15)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at androidx.room.RoomDatabaseKt$acquireTransactionThread$2$2.run(RoomDatabase.kt:1)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/(13:50:59.467) KurobaEx-fdroid | LocalArchiveViewModel: 	at java.lang.Thread.run(Thread.java:923)
```

maybe you can just increase SQLITE_LIMIT_VARIABLE_NUMBER with sqlite3_limit idk

now perhaps you're wondering "what kind of degenerate saves that many threads" well me apparently

**Comment by K1rakishou** [comment]
Oh yeah this can happen I guess.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/148f70f303cd73be790e4b84cf6cff79c141c356
