### ISSUE TITLE
 Saving too many threads makes the local thread archive page inaccessible due to a too many SQL variables error, Chapter 2

### ISSUE THREAD

**Issue by Vikezor** [K1rakishou/Kuroba-Experimental#737]
Same as #723, but with a different message now.
![Screenshot_20220220-144649](https://user-images.githubusercontent.com/6238226/154848472-582648ec-7c63-4e72-952f-ac2b0c057ec2.jpg)
```
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: getThreadOriginalPostsByDatabaseId() error
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: android.database.sqlite.SQLiteException: too many SQL variables (code 1 SQLITE_ERROR): , while compiling: SELECT `post_id`, `owner_thread_id`, `post_no`, `post_sub_no` FROM (
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel:         SELECT *
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel:         FROM chan_post_id cp_id
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel:         INNER JOIN chan_post cpe
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel:             ON cpe.chan_post_id = cp_id.post_id
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel:         WHERE 
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel:             cp_id.owner_thread_id IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel:         AND 
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel:             cpe.is_op = 1
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel:     )
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1045)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:652)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1570)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1533)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.query(FrameworkSQLiteDatabase.java:4)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at androidx.room.RoomDatabase.query(RoomDatabase.java:4)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at androidx.room.util.DBUtil.query(DBUtil.java:1)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at com.github.k1rakishou.model.dao.ChanPostDao_Impl$17.call(ChanPostDao_Impl.java:3)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at androidx.room.CoroutinesRoom.execute(CoroutinesRoom.kt:8)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at com.github.k1rakishou.model.dao.ChanPostDao_Impl.selectOriginalPostsGrouped(ChanPostDao_Impl.java:19)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at com.github.k1rakishou.model.source.local.ChanPostLocalSource.getThreadOriginalPostsByDatabaseId(ChanPostLocalSource.kt:37)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at com.github.k1rakishou.model.repository.ChanPostRepository$getThreadOriginalPostsByDatabaseId$3$1.invokeSuspend(ChanPostRepository.kt:7)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at com.github.k1rakishou.model.repository.ChanPostRepository$getThreadOriginalPostsByDatabaseId$3$1.invoke(ChanPostRepository.kt:2)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at androidx.room.RoomDatabaseKt$withTransaction$2.invokeSuspend(RoomDatabase.kt:10)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:5)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:21)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:15)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:2)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at androidx.room.RoomDatabaseKt$acquireTransactionThread$2$2.run(RoomDatabase.kt:1)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:1)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/(16:25:05.282) KurobaEx-fdroid | LocalArchiveViewModel: 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/3b197e5b5220ec9c774b9e63f502c2426591041f
