### ISSUE TITLE
App crashes whenever the context menu appears (Miui 13)

### ISSUE THREAD

**Issue by MCorbo7** [K1rakishou/Kuroba-Experimental#742]
Just updated my phone to Miui 13 (Android 12), whenever the context menu has to appear (for selecting text for example) the app crashes immediately.
Already sent crash report through the app.

**Comment by K1rakishou** [comment]
```
E/(23:28:44.683) KurobaEx | Chan: Unhandled exception in thread: main
E/(23:28:44.683) KurobaEx | Chan: android.content.res.Resources$NotFoundException: String resource ID #0x7f120303
E/(23:28:44.683) KurobaEx | Chan: 	at android.content.res.Resources.getText(Resources.java:463)
E/(23:28:44.683) KurobaEx | Chan: 	at android.content.res.MiuiResources.getText(MiuiResources.java:106)
E/(23:28:44.683) KurobaEx | Chan: 	at android.content.res.Resources.getString(Resources.java:556)
E/(23:28:44.683) KurobaEx | Chan: 	at miuix.toolbar.internal.menu.MenuBuilder.add(MenuBuilder.java:453)
E/(23:28:44.683) KurobaEx | Chan: 	at com.github.k1rakishou.chan.features.reply.ReplyLayout$customSelectionActionCallback$1.onCreateActionMode(ReplyLayout.kt:10)
E/(23:28:44.683) KurobaEx | Chan: 	at android.widget.Editor$TextActionModeCallback.onCreateActionMode(Editor.java:4210)
E/(23:28:44.683) KurobaEx | Chan: 	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onCreateActionMode(DecorView.java:3040)
E/(23:28:44.683) KurobaEx | Chan: 	at com.android.internal.policy.DecorView.startActionMode(DecorView.java:1004)
E/(23:28:44.683) KurobaEx | Chan: 	at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:950)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1042)
E/(23:28:44.683) KurobaEx | Chan: 	at android.view.View.startActionMode(View.java:7946)
E/(23:28:44.683) KurobaEx | Chan: 	at android.widget.Editor.startActionModeInternal(Editor.java:2479)
E/(23:28:44.683) KurobaEx | Chan: 	at android.widget.SelectionActionModeHelper.startActionMode(SelectionActionModeHelper.java:305)
E/(23:28:44.683) KurobaEx | Chan: 	at android.widget.SelectionActionModeHelper.startSelectionActionMode(SelectionActionModeHelper.java:281)
E/(23:28:44.683) KurobaEx | Chan: 	at android.widget.SelectionActionModeHelper.lambda$startSelectionActionModeWithSmartSelectAnimation$0$SelectionActionModeHelper(SelectionActionModeHelper.java:335)
E/(23:28:44.683) KurobaEx | Chan: 	at android.widget.SelectionActionModeHelper$$ExternalSyntheticLambda1.run(Unknown Source:4)
E/(23:28:44.683) KurobaEx | Chan: 	at android.widget.SelectionActionModeHelper.startSelectionActionModeWithSmartSelectAnimation(SelectionActionModeHelper.java:343)
E/(23:28:44.683) KurobaEx | Chan: 	at android.widget.SelectionActionModeHelper.$r8$lambda$mMDhXh3JQs_q5UuyTdq2CLenZJk(Unknown Source:0)
E/(23:28:44.683) KurobaEx | Chan: 	at android.widget.SelectionActionModeHelper$$ExternalSyntheticLambda5.accept(Unknown Source:4)
E/(23:28:44.683) KurobaEx | Chan: 	at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:1044)
E/(23:28:44.683) KurobaEx | Chan: 	at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:992)
E/(23:28:44.683) KurobaEx | Chan: 	at android.os.AsyncTask.finish(AsyncTask.java:771)
E/(23:28:44.683) KurobaEx | Chan: 	at android.os.AsyncTask.access$900(AsyncTask.java:199)
E/(23:28:44.683) KurobaEx | Chan: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
E/(23:28:44.683) KurobaEx | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/(23:28:44.683) KurobaEx | Chan: 	at android.os.Looper.loopOnce(Looper.java:210)
E/(23:28:44.683) KurobaEx | Chan: 	at android.os.Looper.loop(Looper.java:299)
E/(23:28:44.683) KurobaEx | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:8138)
E/(23:28:44.683) KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(23:28:44.683) KurobaEx | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
E/(23:28:44.683) KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
```

**Comment by K1rakishou** [comment]
Sounds like a xiaomi bug? I will try to at least suppress it so it doesn't crash. But from the crash it seems it cannot find a string resource so that menu may stop working as expected.

**Comment by K1rakishou** [comment]
>miuix.toolbar.internal.menu.MenuBuilder.add(MenuBuilder.java:453)

Oh yeah this is definitely xiaomi doing some retarded shit. I can't fix it, complain to xiaomi. I can only try to suppress the crash but most likely some of the menu options won't be visible.

**Comment by K1rakishou** [comment]
Oh wait maybe I actually can. The menu build accepts both string id and a string and it crashes because can't find some string by it's id so I can try passing the string itself. Maybe it will fix the crash. Maybe not.

**Comment by K1rakishou** [comment]
https://github.com/K1rakishou/Kuroba-Experimental/commit/bcaf2d5f55e7f3bf5f3ffc7e0148a2060c69e6c3

**Comment by MCorbo7** [comment]
Updated to latest build. I can confirm the issue has been fixed, thank you very much.

**Comment by ykaljshsh** [comment]
I'm miui13 offical developer, how to make this crash, who can give me a screenrecorder?

**Comment by ykaljshsh** [comment]
> Just updated my phone to Miui 13 (Android 12), whenever the context menu has to appear (for selecting text for example) the app crashes immediately. Already sent crash report through the app.

I'm miui13 offical developer, how to make this crash, can you give me a screenrecorder?
