### ISSUE TITLE
{ crush } multitap to select text crush kurobaEX

### ISSUE THREAD

**Issue by baraa272** [K1rakishou/Kuroba-Experimental#754]
Phone : Poco X3 pro 
Android 12 miui 13.03 
Kuroba EX 1.3.9 
Crush report : https://ghostbin.com/5fY86
I tried to send the crush report from within the app but it gives me error response not successful

**Comment by K1rakishou** [comment]
I have already fixed a similar bug, it's the xiaomi doing some weird shit and failing at it.
```
E/(12:31:43.235) KurobaEx | Chan: android.content.res.Resources$NotFoundException: String resource ID #0x7f120303
E/(12:31:43.235) KurobaEx | Chan: 	at android.content.res.Resources.getText(Resources.java:463)
E/(12:31:43.235) KurobaEx | Chan: 	at android.content.res.MiuiResources.getText(MiuiResources.java:106)
E/(12:31:43.235) KurobaEx | Chan: 	at android.content.res.Resources.getString(Resources.java:556)
E/(12:31:43.235) KurobaEx | Chan: 	at miuix.toolbar.internal.menu.MenuBuilder.add(MenuBuilder.java:453)
E/(12:31:43.235) KurobaEx | Chan: 	at com.github.k1rakishou.chan.ui.cell.PostCell$customSelectionActionModeCallback$1.onCreateActionMode(PostCell.kt:5)
```

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/071e61f64752370bcdba9c7bd207ac1c942b78cc

**Comment by baraa272** [comment]
thanks <3
