### ISSUE TITLE
New update Crashes

### ISSUE THREAD

**Issue by hiragashi** [K1rakishou/Kuroba-Experimental#921]
Exception: java.lang.NullPointerException
Message: Parameter specified as non-null is null: method com.github.k1rakishou.chan.features.reply.ReplyLayoutGestureListener.onScroll, parameter e1

Stacktrace
```
java.lang.NullPointerException: Parameter specified as non-null is null: method com.github.k1rakishou.chan.features.reply.ReplyLayoutGestureListener.onScroll, parameter e1
	at com.github.k1rakishou.chan.features.reply.ReplyLayoutGestureListener.onScroll(SourceFile:3)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:728)
	at com.github.k1rakishou.chan.ui.view.ThumbnailView$$ExternalSyntheticLambda0.onTouch(SourceFile:106)
	at android.view.View.dispatchTouchEvent(View.java:14514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3180)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2817)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3186)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2831)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:575)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1889)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4211)
	at com.github.k1rakishou.chan.activity.StartActivity.dispatchTouchEvent(SourceFile:30)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchTouchEvent$androidx$appcompat$view$WindowCallbackWrapper(SourceFile:1)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchTouchEvent(SourceFile:1)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:525)
	at android.view.View.dispatchPointerEvent(View.java:14786)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6760)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6526)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5951)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6015)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5974)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6160)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5982)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6217)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5955)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6015)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5974)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5982)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5955)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8958)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8909)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8860)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9101)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:200)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9046)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9140)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1040)
	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
	at android.view.Choreographer.doFrame(Choreographer.java:784)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1025)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:255)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

```

Logs
```
D/(04:14:11.115) KurobaEx | Chan: ^^^ App went foreground ^^^
D/(04:14:11.115) KurobaEx | ApplicationVisibilityManager: onEnteredForeground() callback execution took 41.769us, callbacks count: 2

```
Additional information
```
------------------------------
Android API Level: 30
App Version: v1.3.26
Phone Model: realme RMX2001
Build type: Release
Flavor type: Stable
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 384
App running time: 126286
System animations state: duration: 1.0, transition: 1.0, window: 1.0
------------------------------
Current layout mode: SLIDE
Board view mode: LIST
Bottom navigation enabled: true
Prefetching enabled: false
Hi-res thumbnails enabled: false
mediaViewerMaxOffscreenPages: 1
CloudFlare force preload enabled: false
useMpvVideoPlayer: true
userAgent: Mozilla/5.0 (Linux; Android 11; RMX2001 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx v1.3.26
maxPostsCountInPostsCache: 16000
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3ADownload%2F4ch
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: false
Background watcher enabled: false
Filter watch enabled: false
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------

```

**Comment by hiragashi** [comment]
Seems ok now
